### ISSUE TITLE
ft_warp_apply not locating spm_invdef

### ISSUE THREAD

**Issue by psrdwy** [fieldtrip/fieldtrip#1021]
When running ft_warp_apply from the tutorial http://www.fieldtriptoolbox.org/tutorial/human_ecog/, specifically with code:

elec_mni_frv = elec_acpc_fr;
elec_mni_frv.elecpos = ft_warp_apply(fsmri_mni.params, elec_acpc_fr.elecpos, 'individual2sn');
elec_mni_frv.chanpos = ft_warp_apply(fsmri_mni.params, elec_acpc_fr.chanpos, 'individual2sn');
elec_mni_frv.coordsys = 'mni';

I ran into a problem where it was having difficulty locating spm_indef:

Undefined function or variable 'spm_invdef'.

Error in individual2sn (line 61)
  [iy(:,:,:,1), iy(:,:,:,2), iy(:,:,:,3)] =
  spm_invdef(Def{1},Def{2},Def{3},VT.dim(1:3),inv(VT.mat),M);

Error in ft_warp_apply (line 189)
  warped = individual2sn(M, input);

Copying spm_indef.m and depositing the copy in the working directory solved the issue easily enough, but just sending for your information.

**Comment by schoffelen** [comment]
have you checked whether SPM is on your matlab path?

**Comment by psrdwy** [comment]
Yes.  Specifically, I had added a path to spm12.  Do you think it was an spm version issue?

 

Patrick

**Comment by schoffelen** [comment]
I noticed that fieldtrip/external/spm8 has the spm_invdef functionality, but not fieldtrip/external/spm12

So indeed, it could be an spm version issue, but in principle it shouldn't.

**Comment by schoffelen** [comment]
So either spm12 does not have this exact function to begin with, or we did not copy it over into the external directory. @StolkArjen do you have a clue about this?

**Comment by StolkArjen** [comment]
Hi both,

Did you use "ft_hastoolbox('spm12', 1)" in order to add spm12 to your path?

I'm asking because the function is contained by the fieldtrip version of
spm12:

which spm_invdef
/Users/arjsto/Documents/MATLAB/fieldtrip/external/spm12/toolbox/OldSeg/spm_invdef.m

Furthermore, the following code works here:

fsmri_acpc = ft_read_mri('freesurfer/mri/T1.mgz');
fsmri_acpc.coordsys = 'acpc';

cfg            = [];
cfg.nonlinear  = 'yes';
cfg.spmversion = 'spm12';
fsmri_mni = ft_volumenormalise(cfg, fsmri_acpc);

load('SubjectUCI29_elec_acpc_fr.mat')
elec_mni_frv = elec_acpc_fr;
elec_mni_frv.elecpos = ft_warp_apply(fsmri_mni.params,
elec_acpc_fr.elecpos, 'individual2sn');
elec_mni_frv.chanpos = ft_warp_apply(fsmri_mni.params,
elec_acpc_fr.chanpos, 'individual2sn');
elec_mni_frv.coordsys = 'mni';

**Comment by psrdwy** [comment]
No, I just added spm12 directly with addpath.  (Which did seem to be working for everything except this.)  Is that the wrong thing to do?

 

Patrick

**Comment by StolkArjen** [comment]
Most "high-level" functions such as ft_volumenormalise already do this
automatically for you, but in case spm hasn't been added yet, then
ft_hastoolbox is your friend.

**Comment by StolkArjen** [comment]
Please close this issue if that fixed it for you
