### ISSUE TITLE
Reproducescript doens't save large cfg fields if old-style field names are used

### ISSUE THREAD

**Issue by matsvanes** [fieldtrip/fieldtrip#1034]
Whenever reproducescript encounters large cfg fields (e.g. headmodel, sourcemodel, neighbours) it will save it as .mat file, thereby reducing the size of script.m (since the cfg option in question is now a single variable name, instead of the complete cfg field). 
However, when the user specified old-style cfg options (e.g. vol, grid), this doesn't work. Reason being that save_large_cfg_fields.m compares the usercfg with a list of (new-style) cfg-field names; only if they match is the large cfg field saved as .mat

I don't know what the best way is to fix this issue. Some simple solutions of which I'm not sure they are prefered are:
- expand the list of items in ignorefields('recursesize') such that it also encompasses old-style field names
- make save_large_cfg_fields.m compare the items in ignorefields('recursesize') with cfg, instead of callinfo.usercfg. 

I'd like your views on this @Spaak @robertoostenveld ?

**Comment by Spaak** [comment]
> * expand the list of items in ignorefields('recursesize') such that it also encompasses old-style field names

This one could work. It has the added benefit that the generated script is more literally close to what the user was providing. At the same time this is a downside, though, since we want the generated script to reflect FT "best practice" and thus not use deprecated/renamed fields.

> * make save_large_cfg_fields.m compare the items in ignorefields('recursesize') with cfg, instead of callinfo.usercfg.

This is probably a bad idea, since the overall cfg can be modified in unexpected ways. Also, we want the generated script to be based on the user's cfg, and not on any defaults used internally.

A third option is to rewrite the `cfg.callinfo.usercfg` explicitly (i.e., rename `grid` into `sourcemodel` etc.) once we get to `save_large_cfg_fields`. It could be argued that in that scenario the usercfg no longer corresponds to the actual user's cfg, but at that stage this is already no longer the case anyway, since a large `struct` input as a cfg field will be changed into a string (reflecting the saved .mat-file).

**Comment by robertoostenveld** [comment]
the ft_preamble that does the saving happens _before_ the ft_checkconfig. Rewriting the `cfg.callinfo.usercfg` would be hard to maintain. Better stay close to the user's specification. Upon execution of the script (depending on `ft_default.checkconfig`) it will complain about the old options.

What are the options ...
- vol
- grid
are there others?

**Comment by Spaak** [comment]
> the ft_preamble that does the saving happens _before_ the ft_checkconfig. Rewriting the `cfg.callinfo.usercfg` would be hard to maintain. Better stay close to the user's specification.

That's how I felt at first as well, but in a reproducescript run there is already some rewriting of `cfg.callinfo.usercfg`, namely in `ft_postamble_savevar`, in code I moved to a [helper function](https://github.com/fieldtrip/fieldtrip/blob/4207bef85b3e6bb81aabaa7e6d5bdb21e28ddb99/utilities/private/save_large_cfg_fields.m#L11).

Not sure that this is the way to go in general, but just pointing out that the `cfg.callinfo.usercfg` is no longer "untouched" anyway when the reproducescript functionality is being used.

**Comment by matsvanes** [comment]
> the ft_preamble that does the saving happens _before_ the ft_checkconfig. Rewriting the `cfg.callinfo.usercfg` would be hard to maintain. Better stay close to the user's specification. Upon execution of the script (depending on `ft_default.checkconfig`) it will complain about the old options.
> 
> What are the options ...
> 
> * vol
> * grid
> 
> are there others?

I don't have a complete list, but I definetely think others might occur. Basically any cfg field that might get large and is renamed in the past. For example "gradfile, optofile, electfile" changed to "grad, opto, elec" respectively. Since I don't have a complete list of which old names might are present in the toolbox, and such a list might become very long, I don't think it's a good idea to extend the list in ignordefields('recursesize'). What do you think is the best solution then @robertoostenveld ?

**Comment by matsvanes** [comment]
#1078

**Comment by robertoostenveld** [comment]
since it is now part of the `reproducescript` branch, this issue can be closed
