### ISSUE TITLE
improve the correct referencing of segmentation methods 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1064]
My idea is that we might want to print information in ft_volumesegment to clarify the specific segmentation method that is used. E.g. "using SPM12 for the segmentation of xxx". This may help to avoid that people are currently saying that they are using *"the FieldTrip segmentation"*.

@mcpiastra what do you think about this?

**Comment by mcpiastra** [comment]
I checked again, when launching ft_volumesegment SPM is mentioned:
`performing the segmentation on the specified volume, using the old-style segmentation

SPM12: spm_preproc (v4916)                         15:41:00 - 01/04/2019
========================================================================
Completed                               :          15:42:17 - 01/04/2019`

I agree that "old-style" is not clear, but SPM12 is already mentioned.
Maybe instead of "old-style", we could write "using the SPM12".

**Comment by schoffelen** [comment]
note that spm itself makes a distinction between old and new type segmentation.
should we be more specific than that?

**Comment by robertoostenveld** [comment]
Well, although "old-style" and  "SPM12" are apparently all mentioned... it seems that people tend to ignore it nevertheless. 

Printing it twice or in ALL-CAPITALS or popping up a GUI dialog with [clippy](https://en.wikipedia.org/wiki/Office_Assistant) "It seems you are using the old-style SPM12 segmentation, are you ok with that?  [yes] [no] [help]" might all help.

But I don't think that we have to go to that length. I consider therefore consider this issue resolved.
