### ISSUE TITLE
ft_checkdata>makessense fails when timelockdata with keeptrials has only 1 timepoint

### ISSUE THREAD

**Issue by matsvanes** [fieldtrip/fieldtrip#1068]
I have the following timelockstructure:
`tlck = `
         `time: 1`
         `label: {370x1 cell}`
         `elec: [1x1 struct]`
         `grad: [1x1 struct]`
         `trial: [350x370 double]`
         `trialinfo: [350x6 double]`
         `cfg: [1x1 struct]`
         `dimord: 'rpt_chan_time'`

When I use `ft_checkdata(tlck)` on this structure, it breaks down because there is an inconsistency between the dimensions of `trial` and the dimensions implied by `dimord`. This is caused because there is only one time point, so an extra dimension is not needed in `trial`. It results in a crash at `makessense line 48`. 
This problem does not arise when I have a similar `freq` structure with
`pow = `
         `freq: 1`
         `label: {370x1 cell}`
         `elec: [1x1 struct]`
         `grad: [1x1 struct]`
         `powspctrm: [350x370 double]`
         `trialinfo: [350x6 double]`
         `cfg: [1x1 struct]`
         `dimord: 'rpt_chan_freq'`
because it skips the erroneous piece of code in `makessense`.

**Comment by robertoostenveld** [comment]
so-called singleton dimensions at the end of a array are squeezed out automatically by MATLAB. E.g. try this

    a = randn(3, 2, 1);

versus

    b = randn(1, 2, 3);

In this case the single time-point gets squeezed out. However, I would expect `getdimord` and `getdimsiz` to work properly on it, since those are aware of the singleton handling.  

Can you make an example script (fine to post that here in the issue) that generates the two timelock and the freq structures (using rand for the data and some channels like `{'1', '2', '3'}` ) and demonstrates the ft_checkdata error?

**Comment by matsvanes** [comment]
### timelock
```
tlck = [];
tlck.dimord = 'rpt_chan_time';
tlck.trial = rand(10,3);
tlck.label = {'1' '2', '3'};
tlck.time = 1;
ft_checkdata(tlck)
```

> Index exceeds matrix dimensions.
> 
> Error in makessense (line 48)
>       nsmp = repmat(dimsiz(strcmp(dimtok, 'time')), [nrpt 1]);
> 
> Error in ft_datatype_timelock (line 72)
>   hassampleinfo = makessense(timelock, 'sampleinfo');
> 
> Error in ft_checkdata (line 270)
>   data = ft_datatype_timelock(data, 'hassampleinfo', hassampleinfo);

### freq

```
freq= [];
freq.dimord = 'rpt_chan_freq';
freq.powspctrm = rand(10,3);
freq.label = {'1', '2', '3'};
freq.freq = 1;
ft_datatype(freq)
```

> ans = 
> 
>         label: {3x1 cell}
>        dimord: 'rpt_chan_freq'
>          freq: 1
>     powspctrm: [10x3 double]
