### ISSUE TITLE
FEM head model with simbio

### ISSUE THREAD

**Issue by tmedani** [fieldtrip/fieldtrip#1093]
Hi , 
I'm trying to reproduce the example of FEM head model from this link

http://www.fieldtriptoolbox.org/tutorial/headmodel_eeg_fem/

but when I arrive to the step "ft_prepare_headmodel"
in which the function call the simbio toolbox 
I get this error : 

Invalid MEX-file 'C:\matlab\fieldtrip-20161231\external\simbio\calc_stiff_matrix_val.mexw64': Missing dependent shared
libraries:
'MSVCR90.dll' required by 'C:\matlab\fieldtrip-20161231\external\simbio\calc_stiff_matrix_val.mexw64'
'svml_dispmd.dll' required by 'C:\matlab\fieldtrip-20161231\external\simbio\calc_stiff_matrix_val.mexw64'.

Error in sb_calc_stiff (line 86)
    [diinsy,cols,sysmat] = calc_stiff_matrix_val(node,elem,cond,mele);

Error in ft_headmodel_simbio (line 90)
headmodel.stiff = sb_calc_stiff(headmodel);

Error in ft_prepare_headmodel (line 430)
    headmodel = ft_headmodel_simbio(geometry, 'conductivity', cfg.conductivity);
 
I tried many version of fieldtrip (2016, 2018 and the last one) but all fail at this point. 

Do you have any idea how can I solve this ? 

my computer configuration is :
----------------------------------------------------------------------------------------------------
MATLAB Version: 9.2.0.556344 (R2017a)
MATLAB License Number: xxxxx
Operating System: Microsoft Windows 7 Professionnel  Version 6.1 (Build 7601: Service Pack 1)
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------
Thank you for you work & for your help
BR 
Takfarinas

**Comment by simonhomoelle** [comment]
Hey Takfarinas,

Changing the fieldtrip version does not help, as the relevant MEX-files do not exist for Windows. However, the MEX-files exist for MacOS and Linux, so if you have access to one of these OS this problem should be solved.

BR
Simon

**Comment by robertoostenveld** [comment]
@simonhomoelle: The mex files do exist for windows, as is clear from the error message and 

```
mac011> find . -name calc_stiff_matrix_val.mexw64
./external/simbio/calc_stiff_matrix_val.mexw64
```

The problem is that those are compiled using an external compiler, which requires the MSVCR90 library (the Microsoft Visual C Runtime library, version 90) on the computer where you want to run the compiled mex file. This is a very common error if you [google for it](https://www.google.com/search?client=safari&rls=en&q=MSVCR90&ie=UTF-8&oe=UTF-8). 

I think that <https://www.lifewire.com/how-to-fix-msvcr90-dll-not-found-or-missing-errors-2623807> provides a good answer, especially "01". 

Searching on the FieldTrip website, I also found this <http://www.fieldtriptoolbox.org/faq/how_can_i_compile_the_mex_files_on_64_bit_windows/>

**Comment by tmedani** [comment]
Hi, 
Thank you Simon & Robert for your answers. 

In mean time I asked also Johannes Vorwerk & Maria Clara Piastra, and the quick solution for that issue is to install
Microsoft Visual C++ 2008 Redistributables and Intel Visual Fortran Redistributables
1- https://www.microsoft.com/en-us/download/details.aspx?id=29
2- https://software.intel.com/en-us/articles/redistributable-libraries-for-intel-c-and-fortran-2019-compilers-for-windows

I tried it and it works perfectly in my windows version.

A+

**Comment by DhawaDong** [comment]
I have tried on R20154a, I am even unable to install simbio to the matlab. Can anybody help me?
