### ISSUE TITLE
ft_dipolefitting fails without Optimization Toolbox and without explanation

### ISSUE THREAD

**Issue by jdien07** [fieldtrip/fieldtrip#1137]
With fieldtrip-20190419 under OS X, ft_dipolefitting fails if the Optimization Toolbox is not installed, with just the message: Undefined function 'fminunc' for input arguments of type 'function_handle'.  Further, it doesn't actually state that it has failed, it simply returns nonsensical coordinates as the solution.  I think we usually try to have FieldTrip functions work even if more specialized toolboxes are not installed, albeit not as well, but at the least there should be an explanatory message, especially that it has failed.

**Comment by robertoostenveld** [comment]
receiving the message "undefined ..." suggests that the error was caught in the try-catch around line https://github.com/fieldtrip/fieldtrip/blob/2dfb68dd1c3642aec004be27a3c2d1647eac586e/ft_dipolefitting.m#L507 or https://github.com/fieldtrip/fieldtrip/blob/2dfb68dd1c3642aec004be27a3c2d1647eac586e/ft_dipolefitting.m#L530

The comments write "catch errors due to non-convergence", not finding the function is an unexpected error.

Rather than keeping the initial guess (from the grid search), it could also return Nan. However, I think that would cause problems for batch-mode dipole fitting in EEGLAB/DIPFIT, where the location of the initial guess is still better than nan. Using the initial guess location, it is possible to refine the dipole fit in the DIPFIT gui. Let me include @arnodelorme for this issue; Arno doppelgänger's you think that Nan as dipole position would work for EEGLAB/DIPFIT?

**Comment by robertoostenveld** [comment]
The underlying problem is that 
https://github.com/fieldtrip/fieldtrip/blob/2dfb68dd1c3642aec004be27a3c2d1647eac586e/inverse/dipole_fit.m#L115
returns True, but that you don't have the function...

I suspect that to be due to you having the license, but not having the toolbox installed. That happens here https://github.com/fieldtrip/fieldtrip/blob/2dfb68dd1c3642aec004be27a3c2d1647eac586e/utilities/ft_hastoolbox.m#L264

I will change it such that it not only checks the license, but also a function from the toolbox (i.e. fminunc).
