### ISSUE TITLE
ft_rejectvisual throws error using metric 'mean'

### ISSUE THREAD

**Issue by eriknemeth** [fieldtrip/fieldtrip#1150]
I use data recorded intracortically on one channel.
Using the function 'ft_rejectvisual' works fine for me as long as I do not use the metric 'min'.
But when I do this is what I get:

> Error using matlab.graphics.axis.Axes/set
> Value must be a 1x2 vector of numeric type
> in which the second element is larger than
> the first and may be Inf
> 
> Error in axis>LocSetLimits (line 272)
>     set(ax,...
> 
> Error in axis (line 101)
>                 LocSetLimits(ax(j),cur_arg,names);
>                 
> Error in rejectvisual_summary>redraw (line
> 278)
>   axis([0.8*xmin 1.2*xmax 0.5 ymax+0.5]);
> 
> Error in rejectvisual_summary (line 141)
>   redraw(h);
> 
> Error in ft_rejectvisual (line 260)
>     [chansel, trlsel, cfg] =
>     rejectvisual_summary(cfg, tmpdata);

Thank you for your help in advance.

**Comment by schoffelen** [comment]
Can you please do a bit more debugging yourself? 

-is this constrained to a particular data structure, or does it happen all the time?
-have you used the debugger (dbstop if error) to investigate what goes wrong: specifically, what is xmin xmax ymax at the moment of the error?
-regarding the previous point, is there anything about your data that might be off? Given the error it seems that ymax is negative...
-does this only happen with the 'min' button, or also with the 'max'?
-is there any asymmetry in the code with respect to handling the 'min' and 'max' case?

Investigating this a bit more could give you handles towards a robust solution, which can be submitted as a pull request to the code. Don't forget to reference this issue in your PR so that we keep all things documented together.

**Comment by schoffelen** [comment]
@eriknemeth any update here?

**Comment by robertoostenveld** [comment]
I can replicate the problem with 

```
data = [];
data.label = {'Cz'};
data.fsample = 1000;
for i=1:100
  data.time{i} = (1:1000) * 1/1000;
  data.trial{i}(1,:) = randn(1,1000);
end

cfg = [];
clean = ft_rejectvisual(cfg, data);
```

Weird that it happens for min, but not for max.

**Comment by robertoostenveld** [comment]
Oh, it is because max and min value are the same (because only one channel), and both are negative. That caused 

```
axes([0.8*xmin 1.2*xmax 0.5 ymax+0.5]);
```
to fail, since 0.8 times a negative value is larger than 1.2 times a negative value.
