### ISSUE TITLE
Change in the way to interpret dimord in getdimord

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1172]
When calling ft_freqstatistics.m, I used to set in my data structure

```matlab
cfg.dimord = 'rpt_chan_freq_time;
```

After much research in the code (no documentation), apparently now, I have to set

```matlab
cfg.powspctrmdimord = 'rpt_chan_freq_time;
```

This is because of the code line 64 of getdimord which I guess is new (as I did not have this problem before).

```matlab
if isfield(data, [field 'dimord'])
  dimord = data.([field 'dimord']);
  return
end
```

Should probably add

```matlab
if isfield(data, 'dimord')
  dimord = data.dimord;
  return
end
```

I put the fix in my code in EEGLAB so that the new field is populated, but this might break other users' code.

Arno

**Comment by schoffelen** [comment]
Hi Arno,
I cannot see in the history of the file that anything relevant has changed recently. Also, starting from line 211 in getdimord the 'normal' way of handling the plain <datastructurename>.dimord is dealt with.

Are you sure it's a problem on our end, and not in terms of the definition of the data structure?

The background information (which apparently is not documented well) is that in general the dimensions of the 'dominant' numeric field in the data is described by the dimord (in combination with the data.freq/data.time/data.label etc fields). Now, at some point we realised that some types of data structures have numeric data that has different 'dimords', hence the possibility of defining a field-specific dimord, e.g. as 'powspctrmdimord', 'crsspctrmdimord'. It could be that the code chokes if the data structure is of mixed type, i.e. containing both a 'dimord' and a '<somethingelse>dimord'. In case of (not to exotic TFR data (with power only) I would have expected just a 'dimord' data.

**Comment by robertoostenveld** [comment]
Hi Arno, in general you never would have had to specify the dimord in the cfg structure, it is an (optional) field in all data structures. 

I guess you found it (and started using it) for ft_freqstatistics, since there it is used (under the hood) to pass some information from  `ft_freqstatistics` -> `ft_statistics_montecarlo` -> `private/clusterstat`. The 1st is doing bookkeeping, the 2nd is data agnostic, but the 3rd needs to know how to do the clustering.

Regarding dimord in data structures, that is as JM said not extensively documented, but already stable for a long time. The idea is that a data structure can have multiple fields (e.g. `timelock.avg` and `timelock.cov`) with conflicting dimords. Describing them with one dimord (as we started off with 15 y ago) therefore does not work. The `data.dimord` is still there for the most important parameter (i.e. the one in the original implementation), but additional `data.xxxdimord` fields can be present to describe `data.xxx`. However, in the implementation it turned out that in many cases we can guess the dimord from the data structure, hence we still are postponing the introduction of xxxdimord in the data structures (since it looks ugly). Rather than copying code to all FT functions, we made the `getdimord` function, which is smart enough for most cases. 

Now onto your case: cfg.dimord is not a field for ft_freqstatistics; that function adds them for the lower level functions. What is your input into ft_freqstatistics? Could you save the cfg and the data (the varargin)? You can do `cfg.debug='saveonerror'`  and ft_freqstatistics will write those to disk upon the error.

**Comment by schoffelen** [comment]
Hi @arnodelorme is this still an issue for you that needs to stay active?
