### ISSUE TITLE
Wrong channels added with ft_preprocessing

### ISSUE THREAD

**Issue by lkandemir** [fieldtrip/fieldtrip#1178]
Hi,

When preprocessing CTF data with the following code: 

    cfg = [];
    cfg.dataset = '....ds';
    data = ft_preprocessing(cfg);
    
    cfg = [];
    cfg.channel = 'MEG';
    data = ft_preprocessing(cfg,data);

349 channels instead of 273 channels including the following ones end up in the data:

'MSTAT101'
'MRSYN101'
'MPLLU101'
'MMSTC101'
'MSTAT103'
'MRSYN103'
'MPLLU103'
'MMSTC103'
'MSTAT104'
'MRSYN104'
'MPLLU104'
'MMSTC104'
...

All of these additional channels start with 'M'. Most are inactive and some of FieldTrip functions do not take them into consideration during calculations but I encountered a problem with this configuration while using freq2timelock function. I got a lot of zeros added to my timelock data. I think this could create a problem for other users as well. 

Levent

**Comment by robertoostenveld** [comment]
Those are channels which are not present in any CTF data sets that I have ever seen. I suspect that they are MEG-site specific, or that these channel names were introduced by non-CTF software exporting to CTF datasets (e.g. exporting from MNE-python).

Please check https://github.com/fieldtrip/fieldtrip/blob/2dfb68dd1c3642aec004be27a3c2d1647eac586e/utilities/ft_channelselection.m#L247

In case your dataset does not comply with manufacturer standards, please use the full specification of the channels you want to include, rather than the easy but functionality-limited short representation "MEG" to select MEG channels.

If you think that the data ought to be supported, please share a (short/small)  dataset with us. See http://www.fieldtriptoolbox.org/faq/how_should_i_send_example_data_to_the_developers/

**Comment by schoffelen** [comment]
hi @lkandemir, what is the status of this. It seems that it's your turn for input. If this issue stays unconfirmed we will close it soon (for the time being), to keep a manageable overview of priorities

**Comment by lkandemir** [comment]
Hi @schoffelen, sorry I forgot to update it here. Yes, apparently those channels are site-specific so I used the full specification of the channels.  Thank you.

Levent

**Comment by schoffelen** [comment]
OK, no worries and thanks.
