### ISSUE TITLE
ft_volumedownsample.m downsampling of volumetric Atlas

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1223]
When downsampling a volumetric Atlas, you want a majority vote for each voxel as to which brain region a voxel belongs to. ft_volumedownsample.m simply downsample. The addition of the code below would allow taking a majority vote for each downsampled region.

    vol -> a 3-D volume containing numerical labels

    sub = 4; % Downsample by 4
    newVolCell = cell(ceil(size(vol)/sub));
    for x = 1:size(vol,1)
        for y = 1:size(vol,2)
            for z = 1:size(vol,3)
                newVolCell{ceil(x/sub), ceil(y/sub), ceil(z/sub)} = [ newVolCell{ceil(x/sub), ceil(y/sub), ceil(z/sub)} vol(x,y,z) ];
            end
        end
    end
    
    % get dominating label for voxel
    newVol = zeros(size(newVolCell));
    for iVol = 1:prod(size(newVolCell))
        uniq = unique(newVolCell{iVol});
        if length(uniq) > 1
            count = histc(newVolCell{iVol}, uniq);
            [~,indMax] = max(count);
            newVol(iVol) = uniq(indMax);
        else
            newVol(iVol) = uniq;
        end
    end

**Comment by arnodelorme** [comment]
I feel though that the offset for the homogenous transformation matrix need to be shifted. In ft_volumedownsample.m, the transformation of coordinate is I follow

x_ori -> ceil(x_ori/cfg.subsample)
with downsampling 4
1 -> 1
5 -> 2
etc..
because voxel 1 in the downsampled version is original voxel 1, voxel 2 in the downsampled version is original voxel 5

In the code above, we now have

x_ori -> ceil(x_ori/cfg.subsample)+ (cfg.subsample-1)/2
with downsampling 4
1 -> 2.5
5 -> 6.5
etc..
because voxel 1 in the downsampled version now represents the values of original voxel 1 to 4

It might actually be simpler to apply a special type of majority spatial filter on the original volume and simply downsample as this is currently done in ft_volumedownsample.m

**Comment by schoffelen** [comment]
Hi Arno,
It sounds as if you are touching upon 2 issues here:
1) an 'interpmethod' for downsampling that takes a 'majority vote' in case of a parcellation, rather than a 'nearest'.
2) some possible issue with the update of the transformation matrix.

Regarding point 1), this sounds like a good plan, yet I realize that you mention ft_volumedownsample, whereas I would employ ft_sourceinterpolate for this purpose. That being said, and looking into the code for ft_volumedownsample, this indeed is a very 'dumb' implementation' where only an integer downsampling is done, after some optional smooting. In addition, we also have a ft_volumereslice function, which probably would be able to do very similar things (where ft_volumereslice is calling ft_sourceinterpolate to do the actual work).
I think we could consider to do something similar for ft_volumedownsample, i.e. let ft_sourceinterpolate take care of the actual data handling (possibly consider adding a smoothing option, which is supported by ft_volumedownsample, but not by ft_sourceinterpolate as far as I know).

Regarding point 2, this is a tricky thing. I was just thinking about this earlier this week, when I encountered a discrepancy between freesurfer's freeview, fsl's fsleyes and FT. I think we need to consider whether or not a 'voxel' coordinate reflects the left lower of the volumetric element, i.e. the actual 'grid point', or whether it is thought to reflect the location of the center of the cubic voxel.

@robertoostenveld, any inclination to chime in?

**Comment by arnodelorme** [comment]
Thank you Jan. Yes, it could be in ft_sourceinterpolate. I am using the code I wrote above and it seems to work ok for me, but it would be great if somebody could check the coordinate transformation.

This solution is especially important for me because I am doing connectivity analysis between Regions Of Interest and I am using the original atlas as source model. However, there are usually more than 1 million voxels at 2mm resolution so I downsample by 4 to get about ~15k voxel which is OK for a source model.

**Comment by schoffelen** [comment]
PR1226 implemented the 'mode' based interpolation in ft_sourceinterpolate. It seems to work fine. See the first few calls to ft_sourceinterpolate in the function test/test_ft_sourceinterpolate to see how it works.

**Comment by arnodelorme** [comment]
I am closing the issue then. Thanks Jan
