### ISSUE TITLE
Compiling part of Fieldtrip using the Matlab compiler

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1247]
When compiling EEGLAB, we compile some of Fieldtrip functions. There are a lot of issues with functions and folders in the "external" folder that would be too long to detail here. There is also a new issue with ft_versions.m under Matlab compiler 2019a. "ver" with a path given as input crashes in compiled code. For compiling, we have changed the code in ft_version.m to 

```
%   a = ver(ftpath);
%   ftver = a.Version;
ftver ='unknown';
```

Arno

**Comment by robertoostenveld** [comment]
We typically use [isdeployed](https://nl.mathworks.com/help/compiler_sdk/ml_code/isdeployed.html) for that, e.g. as in

```
mac036> grep isdeployed *.m
ft_defaults.m:if ~isdeployed
ft_volumenormalise.m:if isdeployed
ft_volumenormalise.m:if isdeployed
ft_volumesegment.m:  if isdeployed
ft_volumesegment.m:  if isdeployed
```

Can you send a pull request that uses `isdeployed` in ft_version?  

You may want to check how we compile FieldTrip, using `utilities/ft_compile_standalone.m` and execute it using `bin/fieldtrip.sh`. I have not used it for some time, but the way that `buildtimestamp` is used might be relevant for the specific issue that you are using. Rather than stamping the compilation moment onto the compiled application, you might want to stamp the version onto it.

PS, please note that we are not responsible for (most) external code; you should address your concerns about that to the original authors and maintainers. FieldTrip itself works fine without the external code, it is just more limited.

**Comment by arnodelorme** [comment]
Issue resolved.
