### ISSUE TITLE
Allowing trial overlap with ft_redefinetrial

### ISSUE THREAD

**Issue by rtheze** [fieldtrip/fieldtrip#1250]
Hi all, 

I am putting an issue here because I am not sure if this was intended, but when calling ft_redefinetrial with cfg.trl and intentionally selecting larger then needed portions of data (for later padding), it does not let me process overlapping trials. 

The issue seems that line 259 in ft_redefinetrial,

`    data.trial{iTrl} = ft_fetch_data(dataold, 'header', hdr, 'begsample', begsample(iTrl), 'endsample', endsample(iTrl), 'chanindx', 1:hdr.nChans, 'skipcheckdata', 1);`

the function ft_fetch_data is called without the option 'allowoverlap' set to neither true or false, which in turn within the function sets it by default to false.  

Manually adding this option 

`    data.trial{iTrl} = ft_fetch_data(dataold, 'header', hdr, 'begsample', begsample(iTrl), 'endsample', endsample(iTrl), 'chanindx', 1:hdr.nChans, 'skipcheckdata', 1, 'allowoverlap', true);`

solved the problem for me, but I am not sure if this true/false setting should be something called from the cfg and thus should not be let to "true" all the time.

**Comment by robertoostenveld** [comment]
this is indeed intended. In case new data is selected from multiple (old) trials, there is the risk that due to (old) preprocessing (e.g. demeaning) there would be jumps in the data between the trials. These would then inadvertently end up as jumps in the middle of the new data. 

If you want, you could suggest a PR that makes the `allowoverlap` option explicit to the end user in the cfg.
