### ISSUE TITLE
Unable to read atlas using ft_read_atlas

### ISSUE THREAD

**Issue by velmurugan01** [fieldtrip/fieldtrip#1280]
When I run to read the standard atlas;
 _**atlas = ft_read_atlas(fullfile(ftpath, 'template/atlas/brainnetome/BNA_MPM_thr25_1.25mm.nii'));**_

Matlab R 2019a throws
Array indices must be positive integers or logical values.

**_Error in ft_read_atlas (line 126)
    atlas.tissuelabel(idx)  = lab;_**

I am using latest git updated fieldtrip as of 13-12-2019 (5pm)

**Comment by schoffelen** [comment]
I cannot reproduce your error (on matlab 2018b)

You appear to be using an old version of ft_read_atlas, because line 126 reads something different in the most recent version. Since the error reported from that line, you probably are running another version of fieldtrip from your matlab path.

Also, check and be sure that the corresponding *.txt file exist in the same location as the .nii.

**Comment by schoffelen** [comment]
@velmurugan01 can this be closed, or is there any new information?
