### ISSUE TITLE
large cfg-fields are not saved seperately by reproducescript.

### ISSUE THREAD

**Issue by matsvanes** [fieldtrip/fieldtrip#1297]
When using reproducescript, large cfg-fields are not written in full in script.m, but rather are saved on disk. However, this does not yet work for all occassions where it might be desirable, which makes script.m very long.
Currently, I think it always save some fields by default (those who are always large, like leadfield). Some fields are not yet saved (like cfg.matrix in ft_math and cfg.neighbours in ft_megplanar). Some, (cfg.trl, cfg.matrix) should probably only be saved on disk when they are very long - too long to write in full in script.

@Spaak suggested (a while ago) to use a helper function to determine if a field should be saved to disk, like should_save_to_disk(cfg, fieldname).
@robertoostenveld @schoffelen

**Comment by robertoostenveld** [comment]
What is currently deciding (in the code) whether it is written to disk or not? Is it a hard-coded list of fields? 

Fields that are written to disk, should also be read in again at the moment that the script is re-executed. That is why I suspect that it currently must be a hard-coded list, since support for reading cfg options from file is not generic.

**Comment by matsvanes** [comment]
Yes, I think the the fields that are saved are in ignorefields.m, case 'recursesize'. Do you think I should just extend this list (with for example 'neighbours', 'trl') or do you prefer something more suffisticated (i.e. let it depend on size/length whether these fields are indeed saved to disk)?

**Comment by robertoostenveld** [comment]
to keep the code from `reproducescript` executable, all variables saved to disk have to be read in  (at another moment) as well. That is now only implemented for some _known_ large fields, and it is implemented explicitly, i.e. in `ft_fetch_sens`, `ft_prepare_headmodel`, `ft_prepare_neighbours` and some others. The implementations are scattered and not very consistent, although much better than it used to be (since Q3/Q4 last year, when we worked on this). 

For many fields we do not have a explicit function to deal with "preparing" it; I also do not look forward to this. I would rather get rid of the scattered file reading in general. 

I think the place to implement generic loading of cfg-fields would be ft_preamble_loadvar, in line with ft_postamble_savevar now being the place where they are written.

**Comment by matsvanes** [comment]
Moved to two seperate issues #1310 and #1311
