### ISSUE TITLE
resampledesign should give warning when cfg.numrandomization is not appropriate

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1313]
The number of possible permutations is limited for within-subject manipulations and a small number of subjects. E.g. in the cluster stats tutorials by @hadrianswall, there are (mostly) 10 subjects with a paired 2-condition design.  In that case there are 2^10=1024 permutations possible permutations.

There should be a warning (or possibly an error) in case when `cfg.numrandomization` >  2^N.

There should be a warning in case when `cfg.numrandomization` is close to  2^N, since in that case `all` would be the better choice.

**Comment by MortyBiomech** [comment]
@robertoostenveld

Hi Robert. I’m running a within-subject cluster permutation test with N=7 subjects and 3 repeated-measures conditions.

I get a warning when using `cfg.numrandomization = 10000` because the number of unique permutations is `3^7 = 2187` (as reported by FieldTrip).

Warning:
the number of randomizations (10000) is larger than the maximum number of unique permutations (2187), better use cfg.numrandomization='all'

I tried to use `cfg.numrandomization = 'all'` (via `stats.fieldtrip.naccu = 'all'` in my wrapper), but I get:
  <paste the exact error text here>
  ("cfg.numrandomization='all' is only supported for two repeated measurements")

Questions:
1) If `cfg.numrandomization` exceeds the number of unique permutations, does FieldTrip automatically cap it at the maximum unique count, or does it sample with replacement (i.e., duplicate permutations)?
2) If duplicates occur, does that affect the resulting p-values / cluster significance, or does it just reduce the effective number of randomizations?
3) For >2 repeated measures, is the recommended approach simply to set `cfg.numrandomization = 2187` manually?
