### ISSUE TITLE
logging of events in ft_read_header

### ISSUE THREAD

**Issue by Brittlambregts** [fieldtrip/fieldtrip#1326]
Hi all, I think I've noticed a bug with regards to writing events into my data using Matlab. For my project, I use an online stream of data (containing output from a gripforce linked to the pc) to which I would like to add events (but the same problem applies to data from disc so its not an on-line problem). When I write events in my data and request the header of the data using ft_read_header, the header states that nEvents = 0. However, when I ask for the events specifically using ft_read_event, it does indeed show me the events that have been marked. Perhaps the logging is incorrect in ft_read_header? 

Enclosed two files: one (_0208) with actual data streamed from the gripforce without events, and one (_0209) with simulated data with events. 
[buffer_examples_events.zip](https://github.com/fieldtrip/fieldtrip/files/4287441/buffer_examples_events.zip)

**Comment by robertoostenveld** [comment]
For reference, I have copied the example data to `/home/common/matlab/fieldtrip/data/test/issue1326`

**Comment by schoffelen** [comment]
When I try to read the test data
ft_read_header + ft_read_event on (_208) works, reporting 0 events
ft_read_header on (_209) fails, due to the offline header reading function not being able to create a hdr.label, ft_read_event works fine, reporting a certain number of events.

Not sure what to do here. Given that the problem statement is a bit vague, and this has been open for 3 years now without anybody apparently suffering from it, I suggest to close. Feel free to reopen
