### ISSUE TITLE
ft_volumesegment: weird results

### ISSUE THREAD

**Issue by ftadel** [fieldtrip/fieldtrip#1327]
I'm testing ft_volumesegment/ft_prepare_mesh against other FEM meshing tools (SimNIBS, brain2mesh) and I obtain very weird results with a few volumes I'm testing.
As an example, the example T1 volume from SimNIBS ("Ernie") gives the following segmentation, the orientation of the skin layer is good, but not the inner layers:

![image](https://user-images.githubusercontent.com/6920058/75973243-2335e100-5ed5-11ea-9745-fb54cdb63246.png)

Here is the volume in FieldTrip format:
[ftMri.zip](https://github.com/fieldtrip/fieldtrip/files/4292389/ftMri.zip)

And the code I used for the segmentation, which obviously gives wrong results.
```
cfg = [];
cfg.output = {'white','gray','csf','skull','scalp'};
segmentedmri = ft_volumesegment(cfg, ftMri);

figure; imagesc(segmentedmri.scalp(:,:,128))
```
![image](https://user-images.githubusercontent.com/6920058/75972841-6774b180-5ed4-11ea-9bb6-db6b19c6b75d.png)

With another volume, I got this (I'm sorry, I can't share this one):
![image](https://user-images.githubusercontent.com/6920058/75972874-7a878180-5ed4-11ea-95cf-b083e1e5ec0e.png)

**Comment by schoffelen** [comment]
this is a user error. The transformation matrix is not consistent with the specification of the coordsys. See the attached screenshot (from ft_determine_coordsys)

<img width="822" alt="Screenshot 2020-03-05 at 11 37 17" src="https://user-images.githubusercontent.com/1517611/75973605-ba029d80-5ed5-11ea-9cda-5b7f61132a2b.png">

The expected X axis is left/right the z axis is pointing down.

**Comment by schoffelen** [comment]
to clarify, if the coordsys is 'ctf', the expected direction of the positive X axis is anterior, and of the positive Z-axis is up. This means that the transformation matrix is wrong.

**Comment by ftadel** [comment]
I see... Let's consider the transformation is not "wrong" as it is the qform matrix from the .nii file. But how should the coordsys field be set to work with this qform matrix?

Does ft_volumesegment work only if the volume has been manually reoriented before?

Thanks!

**Comment by schoffelen** [comment]
The transformation in combination with what you specified to be 'ctf' coordsys is wrong.

ft_volumesegment invokes the spm segmentation tools, which require de volume to be in ACPC-ras (approximately). For a limited set of coordsys specifications (that is the ones that besides the axis orientation also imply the location of the origin of the coordinate system, so generic things like 'ras' or 'lpi' won't work) FieldTrip can approximately convert the coordinate system automatically (which is done in ft_volumesegment). In your case, the coordsys = 'lpi', for which no conversion is possible, since the origin is not defined. Therefore, you first need to use ft_volumerealign to register the image to a well-defined coordsys (e.g. 'ctf', or else 'acpc'), and then call ft_volumesegment

**Comment by ftadel** [comment]
Thanks for the explanations.
I replaced with the qform nifti transformation matrix with the voxel>scs transformation defined in Brainstorm and it works nicely now!
