### ISSUE TITLE
'runica' seems to have some issue

### ISSUE THREAD

**Issue by andylikescodes** [fieldtrip/fieldtrip#1408]
Hi there,

I was running the tutorial here: http://www.fieldtriptoolbox.org/tutorial/networkanalysis/

When I was running this block of code
```
cfg = [];
cfg.method          = 'runica';
cfg.runica.maxstep = 50;
cfg.randomseed = 0;
comp = ft_componentanalysis(cfg, datads);
```

It gives me an error message  below:
```
concatenated data matrix size 274x53600
starting decomposition using runica
runica(): unknown flagOutput argument "sphere" (and maybe others) not assigned during call to "runica".

Error in ft_componentanalysis (line 514)
    [weights, sphere] = runica(dat, optarg{:});

Error in test (line 43)
comp = ft_componentanalysis(cfg, datads);
 ```

I am using the latest version of fieldtrip. There is a similar issue that I found in here: https://github.com/fieldtrip/fieldtrip/issues/1157

But I after I read it I wasn't sure how to fix the issue. It seems like it is a matlab path issue. I tried restarting matlab but the problem persists. Anyone has an idea of how to fix this?

Thank you!

**Comment by robertoostenveld** [comment]
Hi Andy,

The problem seems to be happening in external code, i.e. code that is not maintained by the FT developers themselves. Can you do `which runica` and share its output here?

Subsequently, I propose you do `dbstop if error` prior to executing your code and try to figure out what goes wrong. Perhaps the data that you feed in the function is incorrect, perhaps there is a bug in the runica function from EEGLAB on your platform.

best regards,
Robert

**Comment by andylikescodes** [comment]
> Hi Andy,
> 
> The problem seems to be happening in external code, i.e. code that is not maintained by the FT developers themselves. Can you do `which runica` and share its output here?
> 
> Subsequently, I propose you do `dbstop if error` prior to executing your code and try to figure out what goes wrong. Perhaps the data that you feed in the function is incorrect, perhaps there is a bug in the runica function from EEGLAB on your platform.
> 
> best regards,
> Robert

Thank you for the quick response, Robert.

I tried `which runica` and the output was:
```
F:\HCP\source_test\fieldtrip-20200519\external\eeglab\runica.m
```
This path is the one to the fieldtrip version I am using for this tutorial. I think it is using the right runica under the external folder. It ships with the fieldtrip package.

I also use `dbstop if error` and I locate the problem in from line 512 to 514 of codes in ft_componentanalysis.m:
```
    % construct key-value pairs for the optional arguments
    optarg = [ft_cfg2keyval(cfg.runica) {'reset_randomseed' 0}]; % let FieldTrip deal with the random seed handling
    [weights, sphere] = runica(dat, optarg{:});
```

It seems that it is a similar issue in https://github.com/fieldtrip/fieldtrip/issues/1157, though the person report the issue here found that he was using the wrong version of runica, while on my computer I don't think there are multiple version of runica. Also the `which runica` seems point to the correct directory. 

Any hints would be much appreciated. Thank you!

Best,

**Comment by schoffelen** [comment]
Hi Andy,

Copying over your cfg, and running it on some test data allows me to reproduce your problem.
However, it seems to be that this is a user error, since you made a typo: cfg.runica.maxstep should read cfg.runica.maxsteps. Fieldtrip just passes on the arguments specified in cfg.runica to the lower level function, which (as Robert explained) is coming from, and is maintained by, the EEGLAB folks. Apparently, the runica code does note deal properly with misspecified options.

**Comment by andylikescodes** [comment]
Thank you. I fixed the typo and the code runs without error.
