### ISSUE TITLE
improvements needed following range in handling of pre-computed leadfields

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1410]
**Describe the bug**

With PR #1377 we introduced some changes in the handling of either pre-computed leadfields OR headmodels. Previously headmodels would always be prepared, even if leadfields or filters were already available. Now it only prepares the headmodel if leadfields are needed.

However, we can anticipate a few use cases where the new implementation might not be backward compatible. 

**To Reproduce**

- I suspect that DICS with `refdip` and/or `supdip` will now fail when combined with pre-computed leadfields for the regular grid
- I suspect that scripts using precomputed filters might fail due to the absence of `label` and/or `pos`, see e.g. `test_tutorial_beamformingextended20131122` and corresponding tutorial (which I already updated).
- I am not sure whether pre-computed leadfields and/or filters without a `pos` are handled correctly. It might be that a pos is constructed on the fly that does not match the leadfield or filter.

**Expected behavior**

Backward compatibility with users' existing scripts, or documentation/instructions how to change the scripts to make them work with future FT versions. 

**Environment and versions (please complete the following information):**
 - FieldTrip master branch from 29 May 2020 onward.

**Comment by schoffelen** [comment]
"Expected behavior

Backward compatibility with users' existing scripts, or documentation/instructions how to change the scripts to make them work with future FT versions."

👍 :)

**Comment by schoffelen** [comment]
have you checked the contributing guidelines document?

**Comment by schoffelen** [comment]
How shall we carry this forward? I agree with the concern of backward compatibility in general, but am wondering whether we should pre-empt any potential scenario we could come up with. 

Just thinking about general backward compatibility: I have the feeling that we try to someteimes 'overdo' it, in some way. Specifically, I think that typically users run into 'problems' because they use both outdated scripts/documentation + outdated fieldtrip. Provided the combination of outdated scipts + up-to-date fieldtrip throws (somewhat) informative errors, I think it can be considered to sacrifice backward compatibility, provided it makes the code overall more consistent, and predictably behaved.

With respect to the 3 specific scenarios sketched above:
-point 2 seems somewhat confirmed given the test function failing originally -> the way I'd solve this is to throw an informative error for the missing label, and to think about the necessity of a pos field (which is not necessary, right?)
-points 1 and 3 can be relatively easily confirmed (if true), and a strategy might be devised to minimally deal with it.
-w.r.t. point 1: in my recent clean up of the beamformer_* code, I realised that the way in which a 'refdip' can be defined for DICS is different from PCC. If I recall correctly, in the latter it can only be a 3-element position coordinate. In the former, it can also be a struct with pos/leadfield/filter.

**Comment by robertoostenveld** [comment]
I agree that we sometimes have the tendency to overdo it (e.g. with colormaps, wink-wink). 

However in this case I think we have broken some scenarios that use refdip or subdip, like the methods employed in https://doi.org/10.1016/j.neuroimage.2008.01.045. Improving it overall by making the low-level code better is one solution, but I think that is more work to implement than changing the headmodel preparation in the high-level code.

I will first make a test script that uses refdip and/or subdip. That would be good to have anyway. Searching on the website, I realized that it is not documented anywhere.

**Comment by robertoostenveld** [comment]
I have checked the beamformingextended tutorial, right [here](http://www.fieldtriptoolbox.org/tutorial/beamformingextended/#source-analysis) it would fail if it were to do ft_sourceanalysis with precomputed leadfields. The error that it prints is 


```
Error using ft_sourceanalysis (line 399)
cannot match the channels in the sourcemodel to those in the data 
```

which is due to the data having 153 (MEG plus two EMG) and the leadfield having 151 channels

**Comment by schoffelen** [comment]
Hehe, corticomuscular coherence is sooo 2005

**Comment by robertoostenveld** [comment]
Making the code work both with and without precomputed leadfields, and comparing the outputs in detail, I identified a bug in the currently released implementation. It seems to be a consequence of the change in the handling of the reducerank and backproject options in PR #1377.

With my specifically crafted test script, on line https://github.com/fieldtrip/fieldtrip/blob/1c0e81a25ddd22cd4cfca03f28c51037502bbf41/ft_prepare_leadfield.m#L292 I ran into the situation that `cfg.backproject` is empty, and that `istrue` returns empty, which the if-statement interprets as `false`. Consequently it goes to the section where the leadfield is redistributed in 151x2 sections, rather than 151x3 sections (since in my case the leadfields were rank-reduced and subsequently back-projected).

It is still a bit dificult to oversee under which situations this happenens and how it might affect users (if at all).

With https://github.com/fieldtrip/fieldtrip/commit/1c0e81a25ddd22cd4cfca03f28c51037502bbf41 I have already put a quick band-aid in place, ensuring that `istrue([])` throws an error rather than ending up in ill-defined behavior.

**Comment by schoffelen** [comment]
Aiai, that's a nasty one. I'd guess that in general istrue([]) to return false makes sense, because a not specified default for a parameter (i.e. returning empty on ft_getopt if 'no' is not specified) would be the default behaviour. Now, in case of backproject, the actual expected default would be 'yes', so it seems as if it's not handled well at all locations of the code. 
I'd guess that with the explicit error of istrue([]) some dead bodies may fall out of closets, explicitly unmasking to-be-booleanised options that may have been pre-defined empty

**Comment by robertoostenveld** [comment]
the issue with `cfg.backproject` has been resolved and communicated on http://www.fieldtriptoolbox.org/#24-june-2020

**Comment by robertoostenveld** [comment]
The `test_issue1410.m` script confirmed the issue. It has now been resolved.
