### ISSUE TITLE
Using ft_read_event read same .nex file from tutorial while get different answer

### ISSUE THREAD

**Issue by cucrui** [fieldtrip/fieldtrip#1510]
I'm following the tutorial from this [link](http://www.fieldtriptoolbox.org/tutorial/spike/#procedure), and I download file `p029_sort_final_01.nex` from ftp server. The version of fieldtrip is `fieldtrip-20200607` also download from ftp server.

when I run the code
```
spike = ft_read_spike('p029_sort_final_01.nex');

cfg              = [];
cfg.spikechannel = {'sig002a_wf', 'sig003a_wf'}; % select only the two single units
spike = ft_spike_select(cfg, spike);
```
I got the same result as tutorial.  But when I run
```
event = ft_read_event('p029_sort_final_01.nex')
```
I got the result
```
event = 
361626×1 struct array with field
    sample
    value
    timestamp
    type
    duration
    offset
```
which is different result with the tutorial
```
event =
37689x1 struct array with field
    sample
    value
    timestamp
    type
    duration
    offset
```
Beside, when I run the code with same input file `p029_sort_final_01.nex`, I got `spikeCleaned` struct with different timestamp size from tutorial.
```
cfg             = [];
cfg.fsample     = 40000;
cfg.interpolate = 1; % keep the density of samples as is
[wave, spikeCleaned] = ft_spike_waveform(cfg,spike);
```
I can not figure out what is wrong, any reply are appreciate, thanks.

**Comment by schoffelen** [comment]
I can confirm the discrepancy between the results computed from the current version of the code, as compared to what is displayed in the tutorial. I think none of the two is more 'true'. In order to avoid further confusion, I suggest to replace the information in the tutorial with the latest insights. Please go ahead to make the necessary textual changes on the website. If figures need to be updated, let us know because to get this sorted out, you need to fool around with the github repo of the website (rather than just in place editing of text).

**Comment by schoffelen** [comment]
@cucrui are you going to work on this anytime soon?

**Comment by cucrui** [comment]
> @cucrui are you going to work on this anytime soon?
Sorry, I used another lib for my project, and I dont try new tutorial again.

**Comment by schoffelen** [comment]
It's a pity then that I needed to spend time on this without any benefit. It would be great if nonetheless you could contribute as well

**Comment by schoffelen** [comment]
And it would have been nice if you had notified me about this before I spent time on this.
