### ISSUE TITLE
label rejection during ft_preprocessing

### ISSUE THREAD

**Issue by Nichalas** [fieldtrip/fieldtrip#1541]
[dat.zip](https://github.com/fieldtrip/fieldtrip/files/5200605/dat.zip)
Hi, 
It seems that ft_preprocessing function rejects labels from the data structure (dat; attached)
**To Reproduce**
Code for reproducing: 
        
cfg=[];      
cfg.length=2;      
data2=ft_redefinetrial(cfg,dat);
        
cfg=[];     
cfg.demean='yes';             
data3=ft_preprocessing(cfg,data2);

**Expected behavior**
data3 should contain the same amount of labels as starting dat.

**Environment and versions (please complete the following information):**
 - Operating System: Ubuntu 18.04.4 LTS
 - MATLAB version R2019b
 - FieldTrip version most recent master branch from github"

**Comment by schoffelen** [comment]
dear @Nichalas

This is probably not the most appropriate place to ask this question. Have your read our contributing guidelines? 

https://github.com/fieldtrip/fieldtrip/blob/master/.github/CONTRIBUTING.md

I think you should ask this on the discussion list (if this hasn't been reported before), and you should be a little bit more informative about the problem that you perceive. 'it seems that ft_preprocessing function rejects labels from the data structure' is a bit too vague. At least, it doesn't inspire me to download the zip-file and look into it.

**Comment by robertoostenveld** [comment]
I did download the data and had a look at it. I can confirm that `data2` still has 12 channels, but that `data3` only has 6. That is caused by the original `dat` having duplicate channel names:

```
>> dat.label'
ans =
  12×1 cell array
    {'Hippocampus_L_1'     }
    {'Hippocampus_L_2'     }
    {'Hippocampus_L_3'     }
    {'Hippocampus_L_1'     }
    {'Hippocampus_L_2'     }
    {'Hippocampus_L_3'     }
    {'Cerebellum_Crus1_L_1'}
    {'Cerebellum_Crus1_L_2'}
    {'Cerebellum_Crus1_L_3'}
    {'Cerebellum_Crus1_R_1'}
    {'Cerebellum_Crus1_R_2'}
    {'Cerebellum_Crus1_R_3'}
```

**Comment by schoffelen** [comment]
So, in other words, this is a user error, right?

**Comment by robertoostenveld** [comment]
It is difficult to say whether this qualifies as a bug in the code, or a bug in the data. I would say that the data is incorrect. 

When using `ft_preprocessing`, this line https://github.com/fieldtrip/fieldtrip/blob/5b82f4bd82e20e587a276b664ebb1ffc5cf93b75/fileio/ft_read_header.m#L2802 would have ensured that all labels in `hdr.label` are unique, which would feed further down in the pipeline.

A solution (for this unexpected behaviour in the FT code) would be to add something similar to the data checks, like 

```
if length(unique(data.label))~=length(data.label)
  ft_error('channel labels must be unique')
end 
```

This is already in `ft_appendspike`. To ensure this test being done always, it should be added to `ft_datatype_raw`, `ft_datatype_timelock`, and `ft_datatype_freq` (which are all called by ft_checkdata).
 
However, it is likely (given the channel labels) that this data does not simply originate from a file on disk. So besides making the code more rubust for incorrect ijnput data, we might also want to know where this data came from. Since perhaps there is a downstream FT function in the pipeline function that needs to be improved as well.

**Comment by robertoostenveld** [comment]
> So, in other words, this is a user error, right?

Don't know, since it is not yet clear whether a FT function generated this data structure. E.g. perhaps this the result of ft_sourceparcellate, with an external atlas on disk, then I would say that the error is in ft_read_atlas which should have checked that the atlas is valid.

**Comment by schoffelen** [comment]
Sorry Nikos, at first I did not realize it was you posting here. I think Nikos and Joachim used a subcortical atlas, and then a parcellation scheme to reduce the number of dipoles per parcel, to be subjected to a connectivityanalysis (I am educated guessing this from our recent e-mail exchanges). 
@Nichalas can you confirm that you hand-crafted the labels of the reduced dimensionality parcels?

**Comment by Nichalas** [comment]
It seems that this was my error. Thank you for looking into it! 
The data structure was manually constructed, without using a FT function.. I can confirm now that using a correct labelling the output of ft_preprocessing function is correct.
Many thanks again!

**Comment by robertoostenveld** [comment]
You would now get an explicit error in your pipeline like this 
```
>> data3=ft_preprocessing(cfg,data2);
Error using ft_datatype_raw (line 86)
channel labels must be unique
Error in ft_checkdata (line 267)
  data = ft_datatype_raw(data, 'hassampleinfo', hassampleinfo);
Error in ft_preprocessing (line 288)
  data = ft_checkdata(data, 'datatype', {'raw+comp', 'raw'}, 'hassampleinfo', 'yes'); 
```

This is a general improvement that will help to prevent this confusion in the future.
