### ISSUE TITLE
error in electrodes_tsv.name when running ft_read_data > ft_read_header

### ISSUE THREAD

**Issue by dvanblooijs** [fieldtrip/fieldtrip#1601]
In my BIDS dataset, I have both an electrodes.json and an electrodes.tsv. The electrodes.tsv contains the electrode's names, position etc. The electrodes.json contains the description of the fieldnames in electrodes.tsv. 

When running ft_read_data, it runs ft_read_header and within ft_read_header, bids_sidecar.m loads an electrodes-file of which electrodes_tsv.name is used later on in ft_read_header. The bids_sidecar.m searches for the accompanying electrodes.json OR electrodes.tsv. It then loads the electrodes.json based on alphabethical order instead of the electrodes.tsv. This results in an error later in ft_read_header, because name is not a field in the electrodes_tsv variable when the electrodes.json is loaded.

I propose to remove '.json' in line 127 of bids_sidecar.m to resolve this error. 

https://github.com/fieldtrip/fieldtrip/blob/9a6153cf7dd568efc532cf224e05286b1c3551a9/fileio/private/bids_sidecar.m#L127

**Comment by robertoostenveld** [comment]
Hi Dorien, thanks for reporting. 

Let me see if I understand this properly: `ft_read_header` reads the EEG file, which is in BIDS and is therefore matched with  a `channels.tsv` and a `eeg.json`. So far so good, right?

And then it continues and also figures out that there is are corresponding `electrodes.tsv` and `electrodes.json` files that go with the data. We want the content of those to be represented in `hdr.elec`, or after ft_preprocessing in `data.elec`. And this is where it fails, correct?

I am not sure whether your proposed fix is appropriate, since it would cause the json sidecars to be ignored on https://github.com/fieldtrip/fieldtrip/blob/9a6153cf7dd568efc532cf224e05286b1c3551a9/fileio/ft_read_header.m#L298

I think there might be something wrong with the way I designed the code. Would it be possible for you to share a piece of your dataset? E.g. a single `sub-xx/eeg` directory?

**Comment by dvanblooijs** [comment]
Hi Robert, 

thanks for looking into this. You understand my issue correctly. What would be the easiest way to share a single sub-xx/ieeg directory?

**Comment by dvanblooijs** [comment]
we put part of our dataset online on openneuro.org: https://openneuro.org/datasets/ds003399/versions/1.0.1. I think you will encounter the problem I described when you use this dataset.

**Comment by robertoostenveld** [comment]
that's a cool dataset, thanks for sharing (in general)! I am downloading it now. 

Some suggestions (not about this issue, but the dataset): I propose you update the BIDSVersion from BEP010 to 1.4.1 (the current version). And can you change in the participants age the comma `","` as decimal separator into a point `"."`? I don't know whether it is a BIDS requirement per see, but it is much more common.

**Comment by robertoostenveld** [comment]
also `sub-RESP0521_ses-1_task-SPESclin_run-021231_ieeg.eeg` and `sub-RESP0521_ses-1_task-SPESclin_run-021231_ieeg.eeg` are missing.

But there is another one which allows me to reproduce your issue:
```
>> ft_read_header('sub-RESP0521_ses-1_task-Sleep_run-060307_ieeg.vhdr')
found matching BIDS sidecar '/Volumes/Samsung T3/data/issue1601/ds003399-download/sub-RESP0521/ses-1/ieeg/sub-RESP0521_ses-1_task-Sleep_run-060307_ieeg.json'
found matching BIDS sidecar '/Volumes/Samsung T3/data/issue1601/ds003399-download/sub-RESP0521/ses-1/ieeg/sub-RESP0521_ses-1_task-Sleep_run-060307_channels.tsv'
found matching BIDS sidecar '/Volumes/Samsung T3/data/issue1601/ds003399-download/sub-RESP0521/ses-1/ieeg/sub-RESP0521_ses-1_electrodes.json'
Warning: Column headers from the file were modified to make them valid MATLAB identifiers before creating variable names for the table. The original column headers are saved in the VariableDescriptions property.
Set 'VariableNamingRule' to 'preserve' to use the original column headers as table variable names. 
Error using ft_read_header (line 2831)
Unrecognized table variable name 'name'. 
````

**Comment by robertoostenveld** [comment]
could you change 
```
	"x_y_z": "X, y and z position of the electrode on the brain of the subject",
```
in the electrodes.json file into a separate description for the x, y and z? Each column in the tsv should have a corresponding field in the json, so combining the, like this is not correct.

**Comment by robertoostenveld** [comment]
there is no `coordsystem.json`, hence it is not clear how to interpret the electrode locations.

**Comment by robertoostenveld** [comment]
I have fixed it in `bids_sidecar` by ensuring that it returns the electrodes.tsv file (which is more important) rather than the electrodes.json file.  I also made some other improvements inspired by your dataset. Please do consider the suggestions that I gave above for further improving that dataset.

**Comment by dvanblooijs** [comment]
Thank you for all the suggestions on our dataset, I will work on it to improve it!

**Comment by dvanblooijs** [comment]
thank you for your nice suggestions! I will look at it when improving the dataset. And thanks for fixing this issue!
