### ISSUE TITLE
Implementing two atlases

### ISSUE THREAD

**Issue by neurofractal** [fieldtrip/fieldtrip#1612]
Hi Fieldtrip Team, 

I am planning on implementing two atlases:

1. Melbourne Subcortical Atlas https://github.com/yetianmed/subcortex/tree/master/Group-Parcellation/3T
2. _(more experimental)_ HCPMMP 1.0 on volumetric grid (Similar pipeline to: https://figshare.com/articles/HCP-MMP1_0_projected_on_MNI2009a_GM_volumetric_in_NIfTI_format/3501911)

Looking at ft_read_atlas there seem to be a variety of formats (e.g. AAL has 'tissue' and 'tissuelabel' fields, whereas other atlases have other fields).

Before implementing I wanted to check whether there is now a standard 'way' for organising/loading parcellations into Fieldtrip?

**Comment by robertoostenveld** [comment]
Thanks for checking! 

The expected representation in memory is explained in https://github.com/fieldtrip/fieldtrip/blob/master/utilities/ft_datatype_segmentation.m for volumetric and in https://github.com/fieldtrip/fieldtrip/blob/master/utilities/ft_datatype_parcellation.m for surface-based atlases. Both have the requirement that there is a `xxx` and a `xxxlabel` field. The naming of `xxx` is not fixed, and there can also be multiple. An example of that is the AFNI template atlas, which has lobes in one, and Brodmann labels in the other. 

The ft_read_atlas function reads it from disk, and where needed applies some "magic" in mapping the (probably) integer values in the voxels to the labels. If you have some original representation of the data and metadata (i.e. labels), you may want to add it to that function. 

But if not, I propose you try to use the logic that starts here
https://github.com/fieldtrip/fieldtrip/blob/fa437b8783491c8df8a31db6adfad4f620fde162/fileio/ft_read_atlas.m#L108
i.e. simply store it in a mat file. That should allow using `ft_read_atlas` but also loading it directly using `load`. 

Especially when you convert the original representation to another one, but also in general: please also provide some documentation in the style of https://github.com/fieldtrip/website/blob/master/template/atlas.md so that the provenance of the atlas is represented somewhere, inlcuding links to original publications etc.

**Comment by schoffelen** [comment]
this can be closed, I think

**Comment by j-tseng** [comment]
Hey @neurofractal - did you ever end up implementing the MMP atlas? That's something I'm looking into as well.

**Comment by neurofractal** [comment]
Hey :) Yes - think I did, but not in a very consistent way. Drop me an email (rob.seymour@ucl.ac.uk) and I'll attach a work in progress copy!
