### ISSUE TITLE
ft_volumewrite option cfg.scaling='no' overwritten for ints

### ISSUE THREAD

**Issue by DanielMiklody** [fieldtrip/fieldtrip#1618]
In ft_volumewrite, the output is scaled no matter if cfg.scaling='no'  for ints because the value is overwritten, in line 116:
[https://github.com/fieldtrip/fieldtrip/blob/b626fbc5f7ffda59e8fb4c9d60f23ee140c7eb09/ft_volumewrite.m#L115](https://github.com/fieldtrip/fieldtrip/blob/b626fbc5f7ffda59e8fb4c9d60f23ee140c7eb09/ft_volumewrite.m#L115)

**Comment by schoffelen** [comment]
True that. What's the desired behavior? I guess that the code now assumes double/single precision in the data matrix, which would require scaling if the datatype of the file is different.
Can you confirm that you want to write something explicitly as an integer?

**Comment by DanielMiklody** [comment]
It is okay/good as a default behavior, but if you explicitly set scaling to 'no' this is unfair ;)
I wanted to write labels as integers. 
Thanks!

**Comment by schoffelen** [comment]
agreed. this is a usecase which was not anticipated when the function was written (and last looked at in detail) an estimated 15 years ago.

My suggestion for a fix would be to build in a check for the (type and) range of the numeric input data, and if this does not exceed the constraints imposed by the requested output datatype, honor the scaling = 'no' option. Otherwise, throw a warning, and apply the scaling (for backward compatibility).

Can you make a first suggestion for these changes, and file a PR for this?

**Comment by DanielMiklody** [comment]
I can do that, yes.
I suggest just checking if scaling is explicitly set to 'no' before default normalization. Like this the behavior is more predictive and if people want no scaling they can just manually set that. I would then additionally add this info to the help, that the default is normalization for int out...

**Comment by schoffelen** [comment]
OK, but in that case the data still needs to be casted into the proper type, right? (or is that also done elsewhere in the code?)

**Comment by DanielMiklody** [comment]
its done later: https://github.com/fieldtrip/fieldtrip/blob/b626fbc5f7ffda59e8fb4c9d60f23ee140c7eb09/ft_volumewrite.m#L195

**Comment by DanielMiklody** [comment]
I realized, the help is already up to date:
% By default, integer datatypes will be scaled to the maximum value of the
% physical or statistical parameter, floating point datatypes will not be
% scaled. This can be modified with
%   cfg.scaling       = 'yes' or 'no'
