### ISSUE TITLE
Rotated channel locations when importing EEGLAB files

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#1674]
From the mailing list

"I performed preprocessing steps of my eegdata (Epoc+) using EEGLAB.
As channel configurations, I considered a specific .ced file for Epoc+ and in EEGLAB I visualized the correct position of sensors in 2D plot.
When I use FieldTrip for the spectral analysis, I imported the .set file.
cfg = [];
cfg.dataset     = 'MyDataset.set';
data_eeg        = ft_preprocessing(cfg)

When I visualize the result of ft_topoplotER, the configuration of sensors is rotated.
In particular, the sensors O1 and O2 are on the left ear and nose on the right ear."

I have faced similar issue when converting EEGLAB dataset to fieldtrip format (using eeglab2fieldtrip) for two different systems.

I use this code (EEGLAB function) to solve this issue before conversion.

EEG = pop_chanedit (EEG, 'nosedir', '-Y');

----
EEGLAB always has +X as the direction for the nose. I believe the import function for EEGLAB should automatically rotate electrode locations.

**Comment by robertoostenveld** [comment]
`ft_prepare_layout` has the option `cfg.rotate` which can be e.g. -90, 0, or 90 degrees. The standard outline of the head with the nose at the top and ears on the left and right of the screen is always the same, so that is why the user can specify how to rotate his/her 3D electrode positions around the z-axis. 

The default for cfg.rotate is `[]` which will try to do it automatically, but that does not always work. The code for this is at 

https://github.com/fieldtrip/fieldtrip/blob/d8e913aa20a7478946d90af66e41a5a8d8afb76d/ft_prepare_layout.m#L1276

**Comment by robertoostenveld** [comment]
now looking at the code, and considering that since 2007 (when this function was introduced) we have made improvements elsewhere, I would nowadays in first instance not use `ft_senstype` to determine how it should be rotated,  but look at `sens.coordsys` instead. Assuming that eeglab2fieldtrip would add the coordsys to the output elec/sens structure, that would allow for robust automatic rotating.

**Comment by robertoostenveld** [comment]
more specifically: `sens.coordsys` could be combined with https://github.com/fieldtrip/fieldtrip/blob/master/private/coordsys2label.m to determine the optimal rotation. Something like

```
if isempty(cfg.rotate)
  % in the 2D layout the nose is usually pointing to the top of the screen, which is the +y direction
  [labelx, labely, labelz] = coordsys2label(sens.coordsys, 1, false);
  % the following code assumes that labelz is 'superior', i.e. the +z axis going to the top of the head
  if strcmp(labely, 'anterior')
    cfg.rotate = 0;  
  elseif strcmp(labely, 'right')
    cfg.rotate = 90; 
  elseif strcmp(labely, 'posterior')
    cfg.rotate = 180;
  elseif strcmp(labely, 'left')
    cfg.rotate = 270;
  else
    ft_warning('cannot determine automatic rotation')
  end
end
```
I am not 100% sure about the numbers, those should be tested..

**Comment by robertoostenveld** [comment]
@arnodelorme do you want to extend eeglab2fieldtrip such that it includes the `elec.coordsys` field (with a known value)? 

I can then update ft_prepare_layout.

If you want to use "eeglab" as the coordinate system rather than to reuse an existing one (like "ctf"), it should be added on this line 

https://github.com/fieldtrip/fieldtrip/blob/d8e913aa20a7478946d90af66e41a5a8d8afb76d/private/coordsys2label.m#L81

**Comment by robertoostenveld** [comment]
in that case we also should document the "eeglab" coordinate system on https://www.fieldtriptoolbox.org/faq/how_are_the_different_head_and_mri_coordinate_systems_defined/

**Comment by arnodelorme** [comment]
Thanks Robert, I have made 2 pull requests for the web site and the code. I have tried adding elec.coordsys to eeglab2fieldtrip.m but it did not make a difference (even when entering an unknown keyword). This is probably because it is not relevant to the ft_dipolefitting() function that follows. Anyway, if you agree I will make the change in Fieldtrip and EEGLAB (they share the same function, but I try to make sure it stays consistent). 

I will also make the change in this function https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/read_eeglabheader.m

**Comment by schoffelen** [comment]
Hi @arnodelorme could you please review the associated PR? According to the info on the EEGlab wiki (https://eeglab.org/tutorials/ConceptsGuide/coordinateSystem.html), I added an coordsys field to the electrode structure upon import. This coordsys is based on the interpretation of the nosedir. I think it already leads to much more robust correctly oriented layouts, without the need of the code changes to ft_prepare_layout suggested by @robertoostenveld
