### ISSUE TITLE
ft_preproc_dftfilter gives error due to rounding

### ISSUE THREAD

**Issue by Emma-k-ward** [fieldtrip/fieldtrip#1770]
**Describe the bug**
When I run line noise removal, I get an error that I have the wrong number of samples, while this is not the case and only seems to be the case due to a rounding error. The error reads:
"Spectrum interpolation requires that the data length fits complete cycles of the powerline frequency, e.g., exact multiples of 20 ms for a 50 Hz line frequency (sampling rate of 1000 Hz)."

**To Reproduce**
My data have trials with 1750 samples, at 500Hz sampling frequency. I then run this code:

lineFreq=50;

goodLength = round(floor(size(datasetIn.trial{1,1}, 2) .* lineFreq./datasetIn.fsample) * datasetIn.fsample./lineFreq);
if size(datasetIn.trial{1,1}, 2) > goodLength
    beginTrial = datasetIn.time{1,1}(1);
    endTrial = datasetIn.time{1,1}(goodLength);
    cfg=[];
    cfg.latency = [beginTrial endTrial];
    datasetIn = ft_selectdata(cfg, datasetIn);
end
%% Line noise filter
cfg = [];
cfg.dftfilter               = 'yes'; %apply line noise filter with spectrum interpolation
cfg.dftfreq                 = [lineFreq lineFreq*2]; %line noise and harmonic
cfg.dftreplace              = 'neighbour'; %spectral interpolation
cfg.dftbandwidth            = [1 2]; %width of window to be interpolated
cfg.dftneighbourwidth       = [2 2]; %width of window from which to interpolate
lineNoiseRemoved = ft_preprocessing(cfg, datasetIn);

The lines in ft_preproc_dftfilter that lead to the error are:
  n = round(floor(nsamples .* Fl./Fs) * Fs./Fl);
  if n ~= nsamples
    ft_error('Spectrum interpolation requires that the data length fits complete cycles of the powerline frequency, e.g., exact multiples of 20 ms for a 50 Hz line frequency (sampling rate of 1000 Hz).');
  end

and when I evaluate those arguments in debug mode, Fs = 500.000, and if I run the same line hardcoding Fs=500 then the error would not be triggered

K>> round(floor(nsamples .* Fl./Fs) * Fs./Fl)

ans =

        1740
        1745

K>> round(floor(nsamples .* Fl./500) * 500./Fl)

ans =

        1750
        1750

I implemented a check on the number of samples before running ft_preprocessing, to avoid the situation where this could happen, and when I evaluate datasetIn.fsample in the higher level script it is equal to 500 so I think the problem is that ft_preproc_dftfilter is reading that value from sample data rather than taking the value that has been defined. This means that defining the sampling frequency explicitly in the higher level script does not help.

**Environment and versions (please complete the following information):**
 - Operating System: Windows 10
 - MATLAB version: 9.9.0.1524771 (R2020b) Update 2
 - FieldTrip version: fieldtrip-20210529
 - Example data: https://surfdrive.surf.nl/files/index.php/s/PJ5p1ow3YYCracP

Thanks for your help!

**Comment by Emma-k-ward** [comment]
While this is being looked at, I get an error every time I try to use padding with this function, maybe that's also something that could be improved? If I specify only "cfg.padding = 6;" for example, I get an error that the function does not support mirror padding, and if I try to specify cfg.padtype, I still get the same error.

**Comment by robertoostenveld** [comment]
loading the shared example data and executing this 
```
%% Line noise filter
lineFreq=50;

cfg = [];
cfg.dftfilter = 'yes'; %apply line noise filter with spectrum interpolation
cfg.dftfreq = [lineFreq; lineFreq*2]; %line noise and harmonic
cfg.dftreplace = 'neighbour'; %spectral interpolation
cfg.dftbandwidth = [1 2]; %width of window to be interpolated
cfg.dftneighbourwidth = [2 2]; %width of window from which to interpolate
lineNoiseRemoved = ft_preprocessing(cfg, exampleData);
``` 
I can reproduce the error
```
Error using ft_preproc_dftfilter (line 155)
Spectrum interpolation requires that the data length fits complete cycles of the powerline
frequency, e.g., exact multiples of 20 ms for a 50 Hz line frequency (sampling rate of 1000 Hz).
Error in preproc (line 499)
    dat     = ft_preproc_dftfilter(dat, fsample, cfg.dftfreq, optarg{:});
Error in ft_preprocessing (line 375)
    [dataout.trial{i}, dataout.label, dataout.time{i}, cfg] = preproc(data.trial{i}, data.label,
    data.time{i}, cfg, begpadding, endpadding);
```

Stopping with the debugger on line 154 (one before the error), I see that 

```
K>> n
n =
        1740
        1745
K>> nsamples
nsamples =
        1750
```
and the code is comparing these two in an if-statement. I suspect that the implementation of the `neighbour` method did not consider the possibility of specifying more than one frequency (like 50 and 100) as done here. However, changing the option to `cfg.dftfreq = [50]` still gives an error. 

the error happens on line 153 where the `floor` causes 175.000 (which happens to be _just_ a tiny bit smaller than 175) to be rounded off to an integer 174.

**Comment by schoffelen** [comment]
Perhaps the check that causes the error is a bit too enthusiastic, @sabineleske and @sarangnemo might want to chime in.

**Comment by robertoostenveld** [comment]
comparing the `zero` to the `neighbour` implementation I see that for `zero` the data is trimmed from 1750.000 (but just a tiny bit smaller) to 1740 samples, and therefore from _almost_ 175 cycles to 174 cycles. Although the rounding off error still applies, the consequence for the (original) `zero` implementation is not problematic. 

The trimming of the data to the nearest (lower) number of integer cycles is missing from the `neighbour` implementation.

**Comment by sarangnemo** [comment]
After offline discussion with @sabineleske, it seems to us that the sampling rate in the example data is indeed exactly 500 Hz, so we believe that it wouldn't be the proper solution to round down to the next integer. As @emma-k-ward points out, `preproc.m` attempts to calculate the sampling rate from the data, rather than trusting the provided `fsample`.

But somehow MATLAB gives machine precision errors even with simple well-defined calculations, which (to me) is surprising. The actual time vector in the provided example data is indeed precisely 500 Hz:
```
>> format long g   % format numbers for spotting machine precision errors
>> exampleData.time{1}(1490:1510)
>> exampleData.time{1}(1490:1510)

ans =

  Columns 1 through 7

                     1.978                      1.98                     1.982                     1.984                     1.986                     1.988                      1.99

  Columns 8 through 14

                     1.992                     1.994                     1.996                     1.998                         2                     2.002                     2.004

  Columns 15 through 21

                     2.006                     2.008                      2.01                     2.012                     2.014                     2.016                     2.018
```
Yet... at around sample 1500, the example data starts to deviate from an exact difference of 0.002
```
>> diff(exampleData.time{1}(1490:1510))

ans =

  Columns 1 through 7

                     0.002                     0.002                     0.002                     0.002                     0.002                     0.002                     0.002

  Columns 8 through 14

                     0.002                     0.002                     0.002                     0.002       0.00199999999999978       0.00200000000000022       0.00199999999999978

  Columns 15 through 20

       0.00200000000000022       0.00199999999999978       0.00200000000000022       0.00199999999999978       0.00200000000000022       0.00199999999999978
```

Which of course leads to the slight deviations from 500 Hz in the sampling rate calculation:
```
>> 1./diff(exampleData.time{1}(1490:1510))

ans =

  Columns 1 through 7

                       500                       500                       500                       500                       500                       500                       500

  Columns 8 through 14

                       500                       500                       500                       500          500.000000000055          499.999999999944          500.000000000055

  Columns 15 through 20

          499.999999999944          500.000000000055          499.999999999944          500.000000000055          499.999999999944          500.000000000055
```

OK, maybe that tiny difference in machine precision could possibly happen due to reading in some types of data from the original data files. But actually, it happens even for very simple and well-defined calculations where (to me) I wouldn't expect it. For example, try:
```
>> format long g
>> 2.002 - 2
```
I get `0.00199999999999978` !!

I suspect this might even vary by CPU, operating system, or Matlab version. :open_mouth:  [In case anybody wants to compare, I used Matlab 2020a on linux with an Intel i7-9700.]

Anyway, given that reality, I wonder if `preproc.m` should just be revised to allow use of the known sampling frequency instead of attempting to re-calculate it?

**Comment by robertoostenveld** [comment]
Numerical (in)accuracies have been discussed more than once before. The FT code has its current design and implementation for a reason, and don't see the argument here strong enough to reconsider that (as that would require updating all known data structures, not only "raw"). 

If the real sampling rate were 499.9999 Hz, the problem with the current code would still exist. Also if the sampling rate were exactly 50 Hz, and the user would pass a data segment that is 1001 samples long, it should be truncated to 1000 samples (50 full cycles) to avoid spectral leakage in the DFT estimate. That is demonstrated with

```
>> dat = randn(1, 1001);
>> ft_preproc_dftfilter(dat, 1000, 50, 'dftreplace', 'neighbour')
Error using ft_preproc_dftfilter (line 165)
Spectrum interpolation requires that the data length fits complete cycles of the powerline frequency, e.g., exact multiples of 20 ms for a 50 Hz line frequency (sampling rate of 1000 Hz). 
```

Let's fix that first, the problem that Emma faces then also disappears, and the discussion on numerical accuracies can be shelved again (until it resurfaces, which it certainly will).

**Comment by schoffelen** [comment]
This discussion related to numerical precision of floating point numbers has occurred several times over the past 15 years or so, and is notoriously difficult to address. 
Specific to @sarangnemo 's comment, rather than putting a band-aid at a higher level of the code, I suggest to handle the issue at the level of code where it occurs. Adding a little bit of leniency to the calculation of 'n' in ft_preproc_dftfilter solves it.
See the associated PR I just created

**Comment by schoffelen** [comment]
OK, Robert's comment was more or less synchronised with mine.
I think that the spectrum interpolation currently cannot deal with 1001 sample segments is related to the requirement of doing an FFT, do some voodoo, followed by an IFFT (and then returning the real part of this result). If the operations are done on the truncated to 1000 samples segments, the returned data are incomplete. 
Hence the original error message I guess.

It leaves to be argued whether the FFT needs to hit the Linfreq spot on, or if some leniency is allowed there...

**Comment by robertoostenveld** [comment]
I would say that some leniency should be allowed. Otherwise we'll never be able to dftfilter data from the Glasgow MEG system.

**Comment by sabineleske** [comment]
As @schoffelen pointed out, trimming the data as it is done for the zero dft implementation (only for the estimation of the amplitude) is not an option for the neighbour implementation, since the returned data would be trimmed as well.
To allow for some leniency can result in spectral leakage and might introduce respective artefacts.

This is an example script to demonstrate the effect of having 1 or 2 samples off from the full cycle (the number of samples can be changed in the first line of the script). (To make this run, the error check within the dft function has to be commented out.)

%% 50 Hz sinusoid of constant amplitude added to Gaussian signal
    
    samples_off = 2; % samples to add, so a full 50 Hz cycle doesn't fit
    
    lengthsec= 4;  % data length in seconds
    fs = 1000; % sampling rate
    acfreq = 50; % set the powerline frequency, e.g., 50 or 60 Hz    

    datlength = (lengthsec*fs);
    dat = gausswin(datlength, round(datlength/100) )'; 
    t= (0:(length(dat)-1))/fs;
    noise = cos( 2 * pi * acfreq * t );
    
    % spectrum interpolation 
    filt_spec = ft_preproc_dftfilter(dat + noise, fs, acfreq, 'dftreplace', 'neighbour', ... 
    'dftbandwidth', 2, 'dftneighbourwidth', 2 );
    
    % add samples to the data to introduce leakage
    datlength2 = (lengthsec*fs) + samples_off;  % LEAK, add samples, so a full cycle doesn't fit
    dat2 = gausswin(datlength2, round(datlength2/100) )'; 
    t2 = (0:(length(dat2)-1))/fs;
    noise2 = cos( 2 * pi * acfreq * t2 );

    % comment out error message in the dftfilter function, before running this
    filt_spec_leak = ft_preproc_dftfilter(dat2 + noise2, fs, acfreq, 'dftreplace', 'neighbour', ... 
    'dftbandwidth', 2, 'dftneighbourwidth', 2 );
   
    figure;
    hold all
    plot( t , dat + noise,'k')
    ylabel('Amplitude (a.u.)')
    xlabel('Time (s)')
    ylim( [ -1.25 2.05 ] )
    xlim( [ 0 4.005 ] )
    legend('Gaussian with 50 Hz line noise')
    title('Gaussian with added 50 Hz sinusoid of constant amplitude - 4.003 s')
    
    figure;
    hold all
    plot( t , filt_spec, 'b')
    plot( t2 , filt_spec_leak,'r')
    plot(t, dat,'k')
    xlabel('Time (s)')
    ylabel('Amplitude (a.u.)')
    legend('Spectrum Interpolation Full Cycle', 'Spectrum Interpolation Not Full Cycle', ... 
    'Original Clean Gaussian')
 
    ylim( [ -0.5 1.5] )
    xlim( [ 0 4 ] )
    title(['DFT neighbour function used for mixed signal (gaussian + line noise)  - Data length = ' ... 
    num2str(datlength/fs) ' s and ' num2str(datlength2/fs) ' s'])
%%

In point of view it would be better to keep the enthusiastic error check. But it's hard for me to predict the severeness of the leakage and artefacts, since it depends on the data and line noise. Or is there a way to ensure that the leakage artefacts always stay neglectable for small sample deviations (1 or 2 samples) ? 
(I remember that it can look severe for some deviations)
Maybe a suggestion on how to trim the data (output of the respective formula) following the error message would help the user (e.g. how to trim for the Glasgow MEG system) ?  
Or a message informing about the sampling rate that has been computed inside the preproc.m function ? (so the user knows what is going on in case another rounding error occurs?)
This of course doesn't solve Emma's problem and the rounding error per se. I'm sorry, but right now I'm not sure what the best solution looks like.

**Comment by schoffelen** [comment]
Thanks for sending the test code. I added it to the test_ft_preproc_dftfilter in the PR. To be honest, I don't think that the results look bad, at least when using the version ft_preproc_dftfilter that uses zero-padding (by adjusting nfft) to ensure  Fl is 'hit'. I don't know how the result would look without zero padding, but I could imagine that it's much worse.

**Comment by robertoostenveld** [comment]
Since the DFT estimation and subtraction assumes stationarity of the line noise (and with 'replace' also of the neighbouring frequencies), the trimming itself (by less than a 50Hz cycle) is not a problem in the estimation.  The estimate must of course be subtracted from the whole segment, not just the trimmed part. That is the same as doing a baseline estimate in the pre-stim ERP window and subtracting it from the whole ERP.

We should consider the starting situation that people *do* have line noise in their data (otherwise there is no need for them to filter) and that the line noise might not be stationary, nor that the sampling rate might be precisely specified by the manufacturer (500 Hz sampling rate might be between 499.500  and 500.499). Consequently, the recommendation in https://www.fieldtriptoolbox.org/faq/why_is_there_a_residual_50hz_line-noise_component_after_applying_a_dft_filter/ of using a bandstop filter might apply.

The fact that a trimmed segment may be needed to estimate the line noise to the best of our abilities, or that even with trimming the line noise cannot be estimated due to an unfavourable relation between sampling and line frequencies, could be communicated to the user with a warning (using "warning once").

**Comment by schoffelen** [comment]
I agree, and would like to add that - rather than disallowing the spectral interpolation method if certain favourable conditions are not met - I think that the next best solution (i.e. zero-padding) is good enough in practical use cases. We may want to warn the users, but they should anyhow carefully check the output of the analysis steps.

**Comment by sabineleske** [comment]
The zero-padding was initially not included as an option for neighbour, since the signal output deviates slightly from zero for the "zero-samples" that are added for padding (if I remember correctly, it has been quite a while). Probably these values contain residual noise from the adjacent frequencies around 50 Hz, which are interpolated as well (usually 49-51 Hz or 48-52 Hz is replaced), but I have not tested this assumption, so I don't know.
I'm not sure if this is a problem per se. Back then I thought it might change the signal in some unwanted way, so I excluded this option. But maybe these deviations are not an issue after all?

**Comment by schoffelen** [comment]
I would like to resolve the open issue and merge the PR: the current status seems that there is some (unmotivated by testcode) reluctance to accept the zero padding solution. I took it out of the 'neighbour' method in ft_preproc_dftfilter, also partly motivated by the fact that padding with zeros is actually inconsistent with the way in which the 'zero' method deals with it (i.e. by truncation). 

An alternative implementation - and a mathematically wholly equivalent one - can be achieved by doing a dft on the relevant frequency bins. Another good point is that this approach will honour the name of the function (dftfilter) and will not require an (i)fft, which is potentially memory and time greedy. Thus, I suggest to push this forward by making a dft transform based spectral interpolation. I have already pushed this to the PR. 

dftreplace can now be:
'zero' -> the original implementation
'neighbour' -> dft-based spectral interpolation
'neighbour_fft' -> fft-based spectral interpolation with strict error check and very limited leniency towards non-standard Fs / data length etc.

Some test code need to be written/evaluated still. Minimal requirements will be that the dft-based method performs the same as the fft-based method in the allowed conditions.
