### ISSUE TITLE
Make a test script for all low-level functions in each module (except fileio)

### ISSUE THREAD

**Issue by malinINCF** [fieldtrip/fieldtrip#1789]
a. Make a test script for all low-level functions in the preproc module
b. Make a test script for all low-level functions in the plotting module
c. Make a test script for all low-level functions in the forward module
d. Make a test script for all low-level functions in the specest module
e. Make a test script for all low-level functions in the connectivity module

**Comment by robertoostenveld** [comment]
Since this issue will likely not be addressed by @LucaLaFisca or anyone else this summer, I have assigned it to myself. Below you can see the breakdown and links to the PRs:

a. Make a test script for all low-level functions in the preproc module https://github.com/fieldtrip/fieldtrip/pull/1811 
b. Make a test script for all low-level functions in the plotting module (seems to be mostly done already)
c. Make a test script for all low-level functions in the forward module
d. Make a test script for all low-level functions in the specest module https://github.com/fieldtrip/fieldtrip/pull/1812 
e. Make a test script for all low-level functions in the connectivity module (working on it)
