### ISSUE TITLE
cortex_light does not work as a color in ft_plot_mesh

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#1831]
**Describe the bug**

@ssanchezalonso noticed in #1826 that `cortex_light` does not work any more in `ft_plot_mesh`. 

**To Reproduce**

I thought that the following would reproduce it, but it does not...

```
>> cd ~/matlab/fieldtrip/plotting/private/
>> [mesh.pos, mesh.tri] = mesh_sphere(12000);
>> ft_plot_mesh(mesh)
```

**Expected behavior**

It should work, since that color is the default for meshes that have more than 10000 triangles.

**Comment by robertoostenveld** [comment]
If I also do `camlight`, then this is what I get

<img width="672" alt="Screenshot 2021-07-11 at 13 47 22" src="https://user-images.githubusercontent.com/899043/125193777-916b8000-e24e-11eb-88d8-96dba0846989.png">


@ssanchezalonso can you try the code above? And perhaps change to another directory after creating the spherical mesh, and try again?

**Comment by JiamingCao** [comment]
I think it's worth mentioning the Matlab versions. I can confirm that I can replicate the error using the codes above on Matlab version '9.10.0.1710957 (R2021a) Update 4', on both Linux and Windows machines. The error message is as follows:

> Unrecognized function or variable 'cortex_light'.
> 
> Error in ft_plot_mesh (line 196)
>   facecolor = eval(facecolor);

This is quite strange, because when I pause at line195 and execute `exist([facecolor '.m'], 'file')` in the command line, it gives me "2" correctly, but I'm unable to evaluate the function, either by typing it in the command window or continuing in the ft_plot_mesh function. I have no issues with my 2018a version, where "cortex_light" would execute correctly after pausing whether I use the command line or let "ft_plot_mesh" continue. The official Matlab documentation for private functions doesn't appear to be any different and I can run the suggested testing code (https://www.mathworks.com/help/matlab/matlab_prog/private-functions.html) just fine, but somehow cortex_light does not work anymore in ft_plot_mesh.

I'm happy to help run more tests to help track down the issue.

**Comment by LJWilliams** [comment]
I'm having this problem too with Matlab 2021a.  Unfortunately, I don't have an older version of Matlab that I can use.  The version of FieldTrip I am using was downloaded on August 18, 2021.  

Thank-you.

**Comment by schoffelen** [comment]
hmmm, I can confirm the issue with matlab2021a. If I replace eval with feval(facecolor) it goes away.
I need to check whether this is good enough with the older matlab versions, but this would be a way forward, right?

**Comment by robertoostenveld** [comment]
does the same apply to `'red'` and the others in this list?

```
% This returns a predefined color as [red green blue] values
%   red               = [255   0   0]/255;
%   green             = [  0 192   0]/255;
%   blue              = [  0   0 255]/255;
%   magenta           = [255 255   0]/255;
%   cyan              = [  0 255 255]/255;
%   yellow            = [255 255   0]/255;
%   white             = [255 255 255]/255;
%   black             = [  0   0   0]/255;
%
%   skull             = [140  85  85]/255
%   cortex            = [255 213 119]/255;
%   cortex_light      = [199 194 169]/255;
%   cortex_dark       = [100  97  85]/255;
%   skin              = [249 223 192]/255;
%   skin_light        = [249 223 192]/255;
%   skin_medium_light = [225 194 158]/255;
%   skin_medium       = [188 142 106]/255;
%   skin_medium_dark  = [155 102  65]/255;
%   skin_dark         = [ 91  71  61]/255;
```

**Comment by robertoostenveld** [comment]
https://nl.mathworks.com/help/matlab/ref/eval.html mentions at the bottom _"Behavior changed in R2021a"_. Comparing it to https://nl.mathworks.com/help/matlab/ref/feval.html, I would say that `feval` is just as appropriate in this use case. Hence I propose to change `eval` by `feval`.

**Comment by schoffelen** [comment]
OK, on it.
