### ISSUE TITLE
ft_freqinterpolate - linear method

### ISSUE THREAD

**Issue by LucaLaFisca** [fieldtrip/fieldtrip#1835]
Need linear method to be implemented in a similar fashion than ft_preproc_dftfilter

**Comment by schoffelen** [comment]
I am not sure what is intended here, and what would be the idea to have a 'similar fashion' to ft_preproc_dftfilter. This function at hand is I think very rarely used (I cannot come up with a use case for which this function would make much sense to use), and its functionality is not really covering its name in case 'nan' interpolation is used. I'd rather deprecate this function, or move it to contrib, rather than improving its functionality.

**Comment by schoffelen** [comment]
This is not going to be addressed anytime soon. Closing for now: feel free to reopen and suggest a PR with the intended functionality

**Comment by LucaLaFisca** [comment]
The proposition was just to implement what this fonction is supposed to do, namely an interpolation. But you are right, the increase of spectral resolution can be done by increasing the number of points used to perform the FFT. I agree with the fact that this function could be deprecated.
