### ISSUE TITLE
ft_timelockbaseline on individual trials returns matrix instead of cell array

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#1838]
**Describe the bug**
If ft_timelockbaseline is run with cfg.parameter = 'trial', which does a baseline normalization for each trial separately, the trial field of the output is now a matrix of odd dimensions (trials X channels X timepoints), instead of a cell array (1 X trials). 

This is because line 144 assigns using parentheses rather than curly braces:
`timelock.(par)(i,chansel,:) = ft_preproc_baselinecorrect(shiftdim(timelock.(par)(i,chansel,:),1), tbeg, tend);`

As a matter of fact, this will also throw an error if trials do not have the same duration.

**To Reproduce**
I think its easily visible in the code, but I can produce testing data if need.

**Expected behavior**
I suppose ft_timelockbaseline should return the usual trial field with a cell array rather than matrix.

**Environment and versions (please complete the following information):**
 - Operating System: CentOS 7
 - MATLAB version: R2018b
 - FieldTrip version: 20210623, but the code is still the same in the current master version

**Comment by NirOfir** [comment]
Also, and I'm not sure that this should be touched because of #1837, the returned timelock structure doesn't have an fsample field.

**Comment by schoffelen** [comment]
I am surprised that the function actually somewhat works on 'raw' data as input. Given the name, I'd expect it to only robustly work on 'timelock' data. Ft_checkdata silently converts a data structure with a trial cell-array into a 'timelock' structure (and thus with the data in a matrix, rather than in a cell-array). However, the function does not convert back.
I'd recommend to use ft_preprocessing(cfg, data) if you want to achieve a per trial baseline. This needs to be specified with cfg.demean = 'yes', and cfg.baselinewindow = [minval maxval]. Should also work with variable length trials.

Note:
- functions like ft_megplanar (and possibly some others) have some code in place which keeps track of whether data was converted from a timelock/raw representation (or vice versa), and convert back at the end of the function. We could consider (although I would incline to be against it here) to do something similar in ft_timelockbaseline
- rather, I'd build in a check to prohibit conversion to a timelock structure in this case, and also more explicitly mention in the documentation the type of input data.

**Comment by NirOfir** [comment]
Aha, thanks for the tip, it does work better. So, should I just remove the option to set cfg.parameter = 'trial' instead of just preventing the transformation to a timelock structura? It sound like that would be the most straightforward, because there is a better alternative. In that case, should I also add a message, if someone did try to use ft_timelockbaseline that way, that they should use ft_preprocessing instead?

**Comment by schoffelen** [comment]
Not sure. A timelock structure with a 3D 'trial' field would be a valid input, no?

**Comment by NirOfir** [comment]
I made a PR for this now. Out of curiosity, how often is ft_checkdata used as a data conversion function? And what is the reason for not going directly through the functions that create those data types?
Thanks!

**Comment by schoffelen** [comment]
Thank, I'll check it out soon.

I don't understand your question: what do you mean with 'not going directly through the functions that create those data types?'?

In general, each high level fieldtrip function calls ft_checkdata at the beginning of the function, in order to ensure that the input data is conform the function's requirements. If the data type does not match, a (silent) conversion is attempted, which most of the time works well enough, without the user even noticing it.

**Comment by NirOfir** [comment]
Thanks, that pretty much answers my question. I was wondering why users are allowed to pass data of the wrong type rather than forcing them to go through the relevant function first (say ft_timelockanalysis in this case). If the conversion works well enough I guess it makes sense to be a bit "lax" about the input data type.
