### ISSUE TITLE
Reordering of channels in ft_channelrepair

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#1840]
Hi, I noticed that ft_channelrepair() reorders the channels in the data structure by their appearance in the sens field of the cfg, at least when using spline interpolation. This is on top of pushing the interpolated channels to the end of the list. The only reason I noticed that is that EEGLAB apparently has an issue with subjects that have their electrodes in different order. I wrote a bit of code that will reorder the data again according to a uniform layout I use for all subjects.

I wondered whether this is a feature of ft_channelrepair we don't care too much about, because whenever the "channel" dimension is used, channels are found by their position in the label field of the data structure (i.e. when we are averaging the ERP of one channel over subjects)?

Thanks!

**Comment by schoffelen** [comment]
Could this be solved in an alternative way, e.g. by including an option in fieldtrip2eeglab that forces a certain channel order. The reason I ask is that FT should not care about channel order to begin with, because of its focus on bookkeeping and multiple checks and balances at the high and intermediate code level. Adding an extra option feels a bit like a band aid on the wrong limb.

**Comment by NirOfir** [comment]
Sounds good to me! Thanks.
