### ISSUE TITLE
Small issues with open_figure()

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#1861]
**Describe the bug**
Hardly a bug, but I noticed a couple of things about open_figure:

1. open_figure can be given a 'renderer'  which isn't used later in the function. Should something like set(h, 'Renderer', cfg.renderer) be added or should this input be removed?
2. Of the few instances this function is called, it is sometimes called with the unused input 'clearfigure'. I suppose this is a leftover from some previous version of the code. Should I clean this bit out?
3. Functions that call open_figure() don't include in their help section an explanation of the inputs, making it harder for users to take advantage of this. I thought of making a unified doc which we can then add to all relevant functions. Something like:
'Figure options:
cfg.figure - 'yes' (default), 'no' .... controls whether a new figure is created.
cfg.visible - 'yes' (default) .... Controls wheter a figure is visible.
....
' 

What do you think?

**Comment by robertoostenveld** [comment]
Re 1: you are right, the renderer option was somehow forgotten when migrating all the code to the new figure handling. There is still one occurrence here https://github.com/fieldtrip/fieldtrip/blob/5221d497f8f8e383c04be6ff9be139374c744271/private/topoplot_common.m#L731 but also there it should have been dealt with in `open_figure` on line 206.

Could you make a pull request to fix this?

At the moment (between two meetings) I don't have time to look at the other 2 issues you raised, but will do later. Thanks!

**Comment by NirOfir** [comment]
Done! Now I see that topoplot_common() sets the figure name inside, rather than by open_figure()...

**Comment by robertoostenveld** [comment]
Re 2: yes, I don't see a reason for `clearfigure`, so that can be cleaned up.

Re 3: yes, that is a good idea. In the past, the figure handling was also not properly documented, and it was inconsistent. It is now (more) consistent, which makes it easier and more valuable for it also to be documented. The best example of consistent and copied documentation that we now have is for `cfg.inputfile/outputfile`. Before you make a PR for this, let's discuss the common explanation here. The default should go at the end of the line, not immediately following the option, and the datatype (string, figure handle, integer, etc) should preferably be specified.

**Comment by NirOfir** [comment]
I made a PR for 2.

That sounds good to me! There are 2 possibilities I can think of. One is to have a unified bit copied over the relevant functions. The second is to refer users to open_figure from all functions (something like "for figure options see open_figure"), and then we only need to maintain the doc in open_figure itself. That would be sort of like what is already done with ft_selectdata. I'm leaning to the 2nd option, but what's your opinion?

**Comment by robertoostenveld** [comment]
That does not work out of the box, because `open_figure` is a private function. Let me share some general considerations first...

We are using the "see also" strategy for `ft_channelselection`, `ft_prepare_layout`, and for some other high-level FT functions that the user can interact with directly and that are on the path. However, the user actually never interacts with `ft_channelselection` by itself; it just happens to be that the help is too long to be included in the other (main) FT functions. 

With `ft_selectdata` (which is used by a lot of end-user oriented and high-level FT functions) we mainly copy the relevant section from its help into the main FT function that calls it. 

We also have a few functions that mainly exist because of the documentation. Besides `ft_channelselection` that would also be `ft_datatype_raw` etc. Those functions actually do NOT contain a "use as" section , which is on purpose: we don't want people using them directly. 

Making functions public has the disadvantage that people can start calling them from their scripts, and then we (the developers) cannot change them any more. Backward compatibility with the main FT functions (those with a cfg) is manageable. For the modules (fileio, plotting, etc) it is also manageable, because the functions follow a clear design. But a function such as `open_figure` is rather ad-hoc, and we might want to totally change it in a year from now.

It is good that you are raising the suggestion of the "see also", because it makes clear that elsewhere in the code (sometimes dating 15 years back) we do it differently and not consistent. It is mainly the `utilities` directory that is a bit of an inconsistent mess. Renaming/moving `open_figure` from private to `ft_figure` in utilities would not make the mess much bigger if you ask me, but the mess remains - and I am now more aware of it. 

What do you think?

**Comment by NirOfir** [comment]
Ah, much clearer now. I think moving open_figure() to a public folder is probably not too helpful, because it really isn't that useful as a function. Even if it will be extended, I feel like it's still going to be just a wrapper around matlab's figure(), in which case my opinion is that users should use figure(), and set cfg.figure = 'gcf', and then they can do whatever they want. So, I change my opinion to just copy the relevant text to the ~15 functions that use open_figure().

**Comment by robertoostenveld** [comment]
ok, please go ahead!

**Comment by NirOfir** [comment]
Thanks for your clear explanations! I think that for me this raises 2 points:

1. Should we keep the string options at all? If they're only for internal consistency, it doesn't sound like a lot of work to edit the ~15 functions that use open_figure() to use handles directly, and then we can remove those from open_figure() completely.
2. We are mixing here figure and axes handles. I think that's not a problem currently, because most FT plotting functions don't use the handles directly when creating the actual plots (via plot() or whatever). However, if in the future this is supposed to change, and handles should be used consistently in all plotting calls, then I think we'll need to only allow axes handles (matlab's plot() only takes an axes handle as an input). I guess users that are going to use the cfg.figure input can be expected to know the difference, and users that won't shouldn't care, because FT will take care of that internally.

**Comment by NirOfir** [comment]
On second thought, point 2 is not entirely accurate. Let's say I want to call ft_topopltER() to draw several time windows on the same figure, it makes sense to pass a figure handle, and not a bunch of axes handles for each subplot. I do think open_figure() itself should output axes handles, but I'm not sure about the general API here. Does the following make sense?
1. Single data structure to plot -> single figure or axes handle.
2. Single data structure, multiple windows -> single figure (always subplots)
3. Multiple data structures to plot -> same number of figure or axes handles (depending on whether the user wants them as subplots or figures) or a single figure handle.

**Comment by robertoostenveld** [comment]
> Should we keep the string options at all?

It would be better to phase them out. Stage 1 is to prevent users from using them by not documenting them in the help, and explaining in the low-level code that these options are deprecated. Stage 2 is to prevent their use in the FT code itself. Removing support is only done once we know for sure that both users and FieldTrip code do not rely on it any more, that would not be the case for the next 5 years or so. See also https://www.fieldtriptoolbox.org/development/deprecated/

**Comment by robertoostenveld** [comment]
Some thoughts: Within a figure you can make one or multiple axes. Within an axis you cannot make multiple axes (at least not in MATLAB-style, that is why we have ft_plot_vector and ft_plot_matrix). 

Some FT functions make use of multiple axes (e.g. ft_sourceplot, or ft_topoplotIC), others do not. 

Some FT functions that themselves only make use of a single axis probably expect the axis to fill the complete figure. E.g., when selecting interactively in ft_multiplotER, I suspect that won't work if it were in a subplot.  

Most FT functions also allow the specification of the figure name, and add the FieldTrip option to the figure menu.  The "figure name"  should not be confused with the "axis title". 

Some functions store information in the figure using https://nl.mathworks.com/help/matlab/ref/guidata.html or using https://nl.mathworks.com/help/matlab/ref/setappdata.html. These two have probably not been used consistently by FT contributors over the years (I hardly understand the difference between them myself). 

I am hesitant changing code that now works just for the sake of cleaning it up. I am all in favor of improving documentation. If it becomes clear (e.g. when writing documentation) that the current code is confusing, then I see a motivation to update the code.

**Comment by NirOfir** [comment]
That all sounds right to me. The main advantage I see for handles except for keeping things in order is speed, if we are updating the plots frequently. That was the case for rejectvisual_trial/channel, for which accessing the handles YDATA property directly is much quicker than calling plot() again, but I'm sure it won't always save time.

In summary, The only thing that is needed to close this issue is to use ft_checkconfig() for the deprecated strings, along with a doc of the handles and other options. I will work on that.

**Comment by NirOfir** [comment]
I still didn't get to it, but when I do, I'll also make sure open_figure() focuses to the requested handle. It make incorporating FT graphics in other matlab code easier (without the focusing, if you initialize a bunch of axes/figures at the beginning, and then just assign them to cfg.figure when calling specific plots, they don't end up where you want them to).
