### ISSUE TITLE
problem openning .fif file

### ISSUE THREAD

**Issue by ninenko** [fieldtrip/fieldtrip#1908]
**Describe the bug**
Problem openning .fif file with FILE-IO 

**To Reproduce**
1. Go to 'FIle'
2. Click on 'Import data'
3. Scroll down to 'Using the FILE-IO interface
4. Choose file with .fif extention. 

**Expected behavior**
I expect EEGLAB to load file. It has been previously loaded with python MNE lab and it works fine.

**Screenshots**

![image](https://user-images.githubusercontent.com/28632595/139265332-e06d652f-5930-4fe0-ba51-190f07917cbb.png)

**Environment and versions (please complete the following information):**
 - Windows 10
 - MATLAB version [R2021b
 - FieldTrip version auto installed via EEGLAB

**Additional context**

**Comment by schoffelen** [comment]
hi @ninenko, what is the status of this? can the issue be closed?

**Comment by schoffelen** [comment]
Closing, due to lack of response by the prime stakeholder @ninenko. Feel free to re-open if you feel that the issue has not yet been adequately dealt with (i.e. it could work for your specific use-case, but a generic solution has not yet been reached). In that case, please help and remind us what still needs to be done.
