### ISSUE TITLE
xdf file issue

### ISSUE THREAD

**Issue by paria-samimi** [fieldtrip/fieldtrip#1913]
Dear Fieldtrip team 

I had made a new mobile EEG device for my project. The problem is that whenever I record EEG with my device and want to open the .XDF file with "xdf2fieldtrip" function, the file has been shown empty, and I just get the events. I am sure that the file is not empty, and it would be greatly appreciated if you could kindly guide me on how I can use your codes for opening my file.
Please find the attached files.
If you need further information please feel free to ask.
Yours Sincerely;
Paria Samimi
<img width="531" alt="Screenshot 2021-11-08 at 10 25 40" src="https://user-images.githubusercontent.com/55695322/140716957-54c901f1-0986-4573-b3e2-d8a406f8f9cd.png">
<img width="925" alt="Screenshot 2021-11-08 at 10 27 13" src="https://user-images.githubusercontent.com/55695322/140716960-5225707f-d2c2-4a5d-b703-2fcae807e70d.png">

**Comment by schoffelen** [comment]
Sorry for the slow reply. We do not generally monitor these question related issues, because we expect people kind of to ask them on the discussion list platform. That has a much larger readership, and therefore a higher probability of being picked up. I suggest you to subscribe to the discussion list and ask your question there, if it is still relevant.

Also, I highly recommend to check the screen output in matlab: are there any messages printed on the screen?

Also, I highly recommend considering to use a direct installation of fieldtrip, and not one which has been shipped with MNE-python. We don't have any explicit version control on that code.

**Comment by robertoostenveld** [comment]
thanks Jan-Mathijs for picking this up, this issue also slipped my attention - and I originally wrote xdf2fieldtrip.

The `xdf2fieldtrip` function makes some assumptions about the XDF file, which I guess are not met here. One assumption is that the desired output representation `dat` is Nchans*Nsamples, i.e. with an equal sampling rate and equal length over all continuous channels. Another is that data is sampled regularly and that the nominal sampling rate is non-zero. Streams (or channels) without a nominal sampling rate are assumed to contain event markers, and get represented in the `event` output.

I suggest you look into the code of `xdf2fieldtrip`, for example using the [MATLAB debugger](https://nl.mathworks.com/help/matlab/matlab_prog/debugging-process-and-features.html). Perhaps you are better off using the `load_xdf` function directly.
