### ISSUE TITLE
channel 255 will always X166?

### ISSUE THREAD

**Issue by drunkpig** [fieldtrip/fieldtrip#1916]
https://github.com/fieldtrip/fieldtrip/blob/a3b6ac5ec74af35658a72f519d7c7ee4f3f047ff/external/brainstorm/in_channel_nk.m#L102

line 102 will never works.

```matlab

%below line will catch case 255, make channel(255).Name='X166'
case num2cell(105:255), ChannelMat.Channel(i).Name = sprintf('X%d', i - 89);   ChannelMat.Channel(i).Type = 'EEG';
case 255,  ChannelMat.Channel(i).Name = 'AVG';                       ChannelMat.Channel(i).Type = 'MISC';   % never works
```

@StolkArjen

**Comment by schoffelen** [comment]
this is a brainstorm function.

also, what is the purpose of your question? please elaborate if you think that we can help you with this.

**Comment by drunkpig** [comment]
> this is a brainstorm function.
> 
> also, what is the purpose of your question? please elaborate if you think that we can help you with this.

hi,

I just felt a little confused.  I don't if this is a bug.

switch i{
case num2cell(105:255)  print("I am here");
case 255, print("I am there");
}

then when i is 255, "I am there will never be printed".

So the right code will be :

```matlab
case num2cell(105:254), ChannelMat.Channel(i).Name = sprintf('X%d', i - 89);   ChannelMat.Channel(i).Type = 'EEG';
case 255,  ChannelMat.Channel(i).Name = 'AVG';                       ChannelMat.Channel(i).Type = 'MISC'; 
```

OR

```matlab
case num2cell(105:255), ChannelMat.Channel(i).Name = sprintf('X%d', i - 89);   ChannelMat.Channel(i).Type = 'EEG';
case 256,  ChannelMat.Channel(i).Name = 'AVG';                       ChannelMat.Channel(i).Type = 'MISC'; 
```

Am I right?

**Comment by robertoostenveld** [comment]
If it is a bug, it should be reported to https://github.com/brainstorm-tools/brainstorm3. The `fieldtrip/external` directory contains code that we are not maintaining ourselves. See https://www.fieldtriptoolbox.org/faq/external/ (although that page is a bit outdated).

Once it is fixed in BrainStorm (i.e. "upstream"), it would be nice if you can report that here, so that we can include an updated version of the function in `fieldtrip/external`.

**Comment by schoffelen** [comment]
https://github.com/brainstorm-tools/brainstorm3/pull/456

**Comment by drunkpig** [comment]
Thank you all guys, I have more bugs to report and I will report to brainstorm3.

**Comment by schoffelen** [comment]
Note that I already filed a PR in the brainstorm repo. For the next time, it would be helpful if you provide a little bit more context, rather than just copy-and-paste in a few lines of code. Robert and I have just finished our morning coffees and have just fed the cats (R) and birds (JM), so we need a more gentle start of our day...

**Comment by ftadel** [comment]
Merged!
Thanks for reporting
