### ISSUE TITLE
ft_write_tsv.m gives error with datetime type of table element

### ISSUE THREAD

**Issue by duygu-sahin** [fieldtrip/fieldtrip#1942]
**Describe the bug**
When creating BIDS data structure for Brain Vision EEG data, ft_write_tsv.m gives error with datetime type of table elements for the scans.tsv creation.

**To Reproduce**
1) Load brain vision data
2) Go to data2bids and run the codes till 2052
3) From here go to ft_write_tsv and see the bug with the subfunction

**Expected behavior**
The data to be written correctly or no pauses at isnan(val) part of the subfunction.

**Environment and versions (please complete the following information):**
 - Operating System: Windows 10
 - MATLAB version: R2021b
 - FieldTrip version: the most recent master branch from github downloaded 27.12.2021

**Solution proposal
1) The codes work well without applying the subfunction output_compatible or 
2) Adding isdatetime elseif statement in the subfunction.

**Comment by duygu-sahin** [comment]
Using datestr instead of datetime works flawlessly.

**Comment by robertoostenveld** [comment]
I believe this issue has not been resolved yet. I only installed MATLAB 2021b this week, so was not able to look into it earlier. 

I think it has to do with https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#scans-file which specifies `acq_time` in a specific format. The acquisition time is not determined by FieldTrip at the moment (although it can be present in a vhdr file), which suggests that you specified it like this 

```
cfg = [];
cfg.dataset = 'Untitled.vhdr';
cfg.bidsroot = 'tmp';
cfg.sub = 'unknown';
cfg.datatype = 'eeg';
cfg.method = 'copy';

cfg.scans.acq_time = datetime('now');

data2bids(cfg)
```

That does give an error in `output_compatible`
```
Undefined function 'isnan' for input arguments of type 'datetime'.
```
which I think is the one you ran into.

When I specify it as string
```
cfg.scans.acq_time = '1877-06-15T13:45:30'
```
then it works. I suppose this is also the work-around that you found yourself. 

However, using a `datetime` object would make sense, especially since it allows for easy shifting of the acquisition for deidentification purposes. Also it can help to ensure that the correct [RFC3339](https://tools.ietf.org/html/rfc3339)-like format is used. See https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#units for details on the format.

I will add an `if isdatetime` clause to the subfunction to convert datetime to the correct format.

**Comment by robertoostenveld** [comment]
@duygu-sahin thanks for reporting this, I hope that the code now works better for you.
