### ISSUE TITLE
Include the possibility to apply signal space projection vectors to Neuromag data

### ISSUE THREAD

**Issue by ualsbombe** [fieldtrip/fieldtrip#1952]
**Is your feature request related to a problem? Please describe.**
Data from neuromag MEG systems have signal space projection (SSP) vectors. These can be applied to data to project out stable noise patterns from the environment

**Describe the solution you'd like**
It would be good if the SSP vectors could be projected our from the data set. Maybe something similar to _ft_denoise_pca_ could be used to facilitate it.

**Additional context**
SSP should not be done after maxfiltering

```%% reading neuromag data 

restoredefaultpath
addpath /home/lau/matlab/fieldtrip/
ft_defaults

path = '/home/lau/mne_data/MNE-sample-data/MEG/sample';
filename = 'sample_audvis_raw.fif'; %% any non-maxfiltered neuromag data will do

hdr = ft_read_header(fullfile(path, filename));

%%
hdr.orig.projs %% has the projections and the data associated with it
```

**Comment by schoffelen** [comment]
That's an awesome idea. Not new, still awesome :).

http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=2109

**Comment by ualsbombe** [comment]
Haha :)

**Comment by schoffelen** [comment]
Would you like having a first shot at it?

**Comment by ualsbombe** [comment]
To be honest - not at this moment - I promised to post it for someone who could make use of it.
If it also doesn't work for you now, I may be able to pick it up after teaching finishes in May (long term,I know)

**Comment by schoffelen** [comment]
Tell this person to sign up on github, and do it him/her/etc self

**Comment by ualsbombe** [comment]
Afraid they don't have the skills yet - I'll check how much they need it and return

**Comment by schoffelen** [comment]
For inspiration: fieldtrip/external/mne/mne_make_projector creates a projection matrix and returns the spatial topographies of the ssp's. For consideration, one could also hand craft a comp - like structure (i.e. one that contains topo/mixing etc) that can be used in ft_rejectcomponent. 

Alternatively, one could indeed use the projection matrix right away in ft_denoise_ssp. One thing to consider is to first visualize the topographies, because it is not clear to me whether they should always all be applied, or whether a user needs to investigate that first.

**Comment by schoffelen** [comment]
Hi Lau @ualsbombe is there any news on this front? I think from a didactical point of view you might consider nudging the person that would like this functionality implemented to sign up on github, and gets a subscription to this issue :) (at a reduced fee). Then I can send you my address details where the øl can be sent, and we could work on this together.

**Comment by ualsbombe** [comment]
Hi Jan-Mathijs
No news yet, I will ask the person to sign up. I would love to send you some øl (and preferably drink some with you)

**Comment by ualsbombe** [comment]
It won't be no, but I will torture you with it

**Comment by gdemarchi** [comment]
Guys, I stumbled upon this discussion,  'lurking' through the issues of fieldtrip ... I like the fact that other people have issues  .... makes my life happier  😄 
Anyway, I have an old function lying around that used to work and do exactly this, then life took over, and we went down the Dark Path of full-blown Maxfilter 😢  so eventually we did not care of SSP & friends anymore, though I regard it as a more 'gentle'  approach to the data ...

The basic idea is to 'activate' the projectors

```
for j=1:size(hdr.orig.projs,2) % we have usually 13
    hdr.orig.projs(j).active = 'true';
end
```

and then use the mne_make_projector function to create the real projection matrix

`[ megproj, nproj,U] = mne_make_projector(hdr.orig.projs,data_meg.label,hdr.orig.bads);
`

and then multiply them on a trial-by-trial basis

```
for iTrial=1:length(datatossp.trial)
    datatossp.trial{iTrial} = megproj*datatossp.trial{iTrial};
end
```

The function amazingly still works, as expected has a bigger effect on MAGS 

![image](https://user-images.githubusercontent.com/33806066/153893862-3afb04ca-0841-4694-a397-94f3239f48fe.png)

If you e.g. @ualsbombe would share the burden of making the old function  fieldtrip (JM) proof and maintaining it, I would be more than happy to share it ... as said we moved more and more towards SSS & friends ...

Re: this 

> Alternatively, one could indeed use the projection matrix right away in ft_denoise_ssp. One thing to consider is to first visualize the topographies, because it is not clear to me whether they should always all be applied, or whether a user needs to investigate that first.

This would be the Brainstorm approach, i.e. create your extra (EOG, ECG, whatever) projectors based on the topographies and the apply/project them out. The Neuormag/Elekta/MEGIN projectors are created and stored once per year during the maintenance by the company guys, inspecting visually time course and topography, and with the hope that most of the background noise would stay constant for one year long (ah ah ... wishful thinking ... 😆 )

PS: wtf, serously? I cannot attach a .m file here in the chat? I've to git branch commit push for it ... otherwise I could copy and paste the content here 😈 
[obob_apply_ssp.m.txt](https://github.com/fieldtrip/fieldtrip/files/8062084/obob_apply_ssp.m.txt)

**Comment by ualsbombe** [comment]
Wow @gdemarchi , that is amazing - all good comes to whoever waits. Thanks for sharing. I would be happy giving this a go. @schoffelen: would you have any comments before I give it a go? Should we create a separate function, or should it be included in one of the existing functions?

**Comment by schoffelen** [comment]
I think that it would be nice to have it in a separate function ft_denoise_ssp. Great if you could have a stab at it.

You could take ft_denoise_synthetic as example.

Note that the for-loop and left-multiplication with the trial data in JM-approved style would have to be done by ft_apply_montage. The latter approach requires a specification of the from-/to- labels so that some bookkeeping can be done on the consistency of the order of the channels (e.g. if a user decides to define some other channels as 'bad' in comparison to what has been stored in the header information). Also: the same projection needs to be applied to the grad structure. This can also be achieved by ft_apply_montage

**Comment by robertoostenveld** [comment]
I think it is important to mention that for the design of `ft_denoise_ssp` similar to `ft_denoise_synthetic` the SSP projectors are to be read with the header (`ft_read_header`) or grad (`ft_reads_sens`, the two call each other, I don't know which one it would be here precisely) and stored in the format of a "montage" (see `ft_apply_montage`) under `grad.balance`. That allows us to keep the SSP projectors aligned with pre whitening and/or ICA projectors.

**Comment by ualsbombe** [comment]
Would this have to be part of reading the data @robertoostenveld? That is,`ft_preprocessing` should store a montage for _neuromag_ data? Or where does that normally happen?

**Comment by robertoostenveld** [comment]
`ft_preprocessing` calls `ft_read_header`, which calls `fileio/private/mne2grad` with the info that is returned from `fiff_read_meas_info`. I would hope that that "info" contains them; if not, something extra would have to be passed into `mne2grad`. 

If you look at the CTF implementation, it is `ft_preprocessing` that calls `ft_read_header` that calls `fileio/private/ctf2grad` where the projections are converted and added to the `grad.balance` structure. 

These projections are kept throughout the whole analysis (since `hdr.grad` is retained throughout as `data.grad`), so that upon computing forward models the projection can also be applied to the lead fields.

**Comment by ualsbombe** [comment]
yes, the info contains the ssp - So I would also have to make changes to `ft_read_header`, right?
And add a `balance` field based on @gdemarchi's code?
![image](https://user-images.githubusercontent.com/17312936/154060696-cdef92a9-dab1-445f-9cf0-9d759c5018e4.png)

**Comment by schoffelen** [comment]
inspiration can be obtained from lines 281 and beyond in ctf2grad

**Comment by robertoostenveld** [comment]
how about adding this to the end of mne2grad (just prior to emptying it in case the number of labels is 0)?

```
% construct the SSP projectors, these can be applied later to the data and grad structure using FT_DENOISE_SSP
grad.balance = [];
grad.balance.current = 'none';
for i=1:length(hdr.projs)
  hdr.projs(i).active = 'true';
  montage = [];
  montage.transform = mne_make_projector(hdr.projs(i), hdr.ch_names, []);
  montage.labelorg = hdr.ch_names;
  montage.labelnew = hdr.ch_names;
  grad.balance.(fixname(hdr.projs(i).desc)) = montage;
end
```

**Comment by schoffelen** [comment]
yes, looks good, apart from that montage.transform should probably read montage.tra

**Comment by ualsbombe** [comment]
I am building a test script - do you have a preferred fif file with projectors in it at DCCN I could test on?

**Comment by schoffelen** [comment]
On the file system at DCCN we have easy access to the 'Henson and Wakeman' dataset.

**Comment by robertoostenveld** [comment]
any dataset that is on the fieldtrip ftp is also fine,. e.g. some of the natmeg data.

**Comment by ualsbombe** [comment]
I just created a pull request - apologies if it could somehow have been linked to this issue. If that can be done, then I can make a new one.

**Comment by robertoostenveld** [comment]
> I just created a pull request 

Perfect, that is how it works! This issue is now linked to the PR. We'll review your suggested code changes.

**Comment by ualsbombe** [comment]
So sorry, Gianpaolo - I try my best not to butcher names, but this one slipped. I did not want to imply that you were Brazilian ;-) I would be impressed if your mother did check :-)

**Comment by ualsbombe** [comment]
Haha - nice that you got it :-)
