### ISSUE TITLE
Parsing detectflank conistently for trialfun and ft_read_events

### ISSUE THREAD

**Issue by mcvinding** [fieldtrip/fieldtrip#1972]
One define detectflank = [] which leads to automatic detection of whether trigger flank is up or down in ft_read_trigger. Gave inconsistent behavior between ft_read_events and ft_define_trials for Neuromag data with STI101 and STI102 trigger channels.  

The option was implemented to deal with problematic EDF (?) files. Should probably be moved to EDF specific section in ft_read_events.

commit: fde31b5bd5

http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3207

**Comment by mcvinding** [comment]
I opened this issue after discussing it with @robertoostenveld , I am not sure how to fix it in the FT code. Robert mentioned that the part defaulting to reading up/down flank, that seemed to give an error with Neuromag data with both STI101 and STI102 channels in the datafile, was added due to some previous issue with EDF files (that I do not know about).

My workaround was to read the events first with 'detectflank', 'up' and parse that to ft_definetrial.

````Matlab
eve = ft_read_event(filelist_ps{ff}, 'detectflank', 'up');
           
cfg = [];
cfg.event               = eve;
cfg.dataset             = my_data.fif;
cfg.trialfun            = 'ft_trialfun_general';
cfg.trialdef.eventtype  = 'STI101';
% ....etc.
cfg = ft_definetrial(cfg);
````

**Comment by schoffelen** [comment]
@mcvinding, what would be the way forward here? Is there anything that needs to/can be done?

Thanks for sharing the code, but I still don't see what problem the addition of ..., 'detectflank', 'up') solved for you. What was it that was inconsistent in the output (w.r.t. expectations) when it was not used? Is there an example fif-file lying around that can be used to demonstrate this? If I read the code, it seems as if the default 'detectflank', being [], leads to an attempt to determine whether it should be 'up' or 'down' according to the first sample in the data matrix that contains the trigger channel data. This happens from line 244 onwards in read_trigger. What I hear you say implicitly, is that - as soon as a fif-file (is that any fif-file, or a particular one that gave the problem for you?) contains both an STI101 and STI102 channel - things behave differently from when the fif-file only has a STI101 channel. Is that true? And - as you write - the difference shows up when inspecting/comparing the output of:

ft_read_event

and 

ft_definetrial  

To reiterate, what is the difference you observe?

And, as a potential solution, should the default of detectflank be made fileformat dependent? (i.e. [] for EDF and 'up' for neuromag) Or should the 'automatic' conversion of [] into 'up'/'down' be reconsidered (and made smarter)?

**Comment by mcvinding** [comment]
I cannot remember the exact details of where I found the error. I re-read the file with the two trigger channels (STI101 and STI102). With the following code: 
````Matlab
eve = ft_read_event(filelist_ps{ff}, 'detectflank', 'up');
           
cfg = [];
cfg.event               = eve;
cfg.dataset             = filename;
cfg.trialfun            = 'ft_trialfun_general';
cfg.trialdef.eventtype  = 'STI101';
cfg.trialdef.prestim    = 2.5;
cfg.trialdef.poststim   = 2.5;
cfg.trialdef.eventvalue = values;
````
It correctly creates the cfg.trl structure. But with the following:

````Matlab
cfg = [];
% cfg.event               = eve;
cfg.dataset             = filename;
cfg.trialfun            = 'ft_trialfun_general';
cfg.trialdef.eventtype  = 'STI101';
cfg.trialdef.prestim    = 2.5;
cfg.trialdef.poststim   = 2.5;
cfg.trialdef.eventvalue = values];
````

I get the message "Error using ft_definetrial no trials were defined, see FT_DEFINETRIAL for help".

**Comment by schoffelen** [comment]
@mcvinding in order to resolve this: Did you use the debugger to inspect the cause of the error? If not, can you send us a small file with 2 trigger channels, or let me know where I can obtain one?

**Comment by mcvinding** [comment]
Strange. Perhaps it is specific to the dataset I have. I will send you an email with a link to the dataset.

**Comment by schoffelen** [comment]
OK, thanks for sending the data. I can confirm the issue on this particular dataset. Since it is a > 1GB file, I trimmed it to the first 25 seconds, and renamed it as issue1972.fif, I will upload it into the DCCN filesystem for reference and take it from there. The smaller file shows the same problem as the larger, original one.

For reference, I truncated the file as follows:

info = fiff_setup_read_raw(<fname-largefile>,1);
fiff_write_raw_segment(<fname-smallfile>,info,100000,125000); % note that 100000 was the first time-stamped sample in the original file.

**Comment by schoffelen** [comment]
OK, this particular dataset fails, because the STI101 channel has an offset of 14592, which makes the automatic determination of 'detectflank' in read_trigger to return 'down', and hence a failed trl-matrix generation. 

ft_definetrial can be supplied with cfg.trialdef.detectflank = 'up', which resolves the issue. 

Alternatively, I can make line 247 in read_trigger a bit more robust by replacing:

if all(dat(:,1)==0)

with 

if all(dat(:,1)-mode(dat,2)==0)

This would make the code more robust for this particular use case, and I don't see many side effects.

@robertoostenveld what do you think? Do we keep the responsibility with the user, or shall I make this change to the code?

**Comment by robertoostenveld** [comment]
I don't understand the rationale of the following code 

```
if isempty(detectflank)
  % look at the first value in the trigger channel to determine whether the trigger is pulled up or down
  % this fails if the first sample is zero and if the trigger values are negative
  if all(dat(:,1)==0)
    detectflank = 'up';
  else
    detectflank = 'down';
  end
end
```

It seems to assume that if the first sample is 0, that all triggers are positive (hence detect=up) and otherwise that the first value must be larger than 0 and therefore detect the downing flanks. However, what if trigger channel contains negative values? 

Since you refer to using the mode, would it be an idea to implement this as (here for one channel)

```
if all((dat-mode(dat))>=0)
  % the occasional TTL pulses are upward going
  detectflank = 'up'
elseif all((dat-mode(dat))<=0)
  % the occasional TTL pulses are downward going
  detectflank = 'down'
else
  % give an error or warning?
end
```

**Comment by robertoostenveld** [comment]
or is there a guarantee that the trigger channel is always positive, e.g. because it is an uint32 or so?

**Comment by schoffelen** [comment]
> or is there a guarantee that the trigger channel is always positive, e.g. because it is an uint32 or so?

No, it is not guaranteed. Basically the 'dat'  variable is the output of ft_read_data, and possibly ad-hocly post-processed by the various fix<something> options. I think that the above suggestions will do no harm, so I will implement it. 

Alternatively, we could consider having a channel specific 'up'/'down' functionality, but I think that this is a bit of an overkill
