### ISSUE TITLE
ft_timelockstatistics with statistic=ft_statfun_actvsblT

### ISSUE THREAD

**Issue by Charl0ttedeB93** [fieldtrip/fieldtrip#1973]
Hi,

We want to run ft_timelockstatistics with statfun=actvsBlT, as suggested in [FT_STATFUN_ACTVSBLT](https://www.fieldtriptoolbox.org/reference/ft_statfun_actvsblT/). The data does not contain a frequency axis. Nevertheless, ft_statfun_actvsblT performs a dimord configuration check that results in an error if the data does not contain a frequency axis (see code snippet below). 

```
% calculate the number of time samples
switch cfg.dimord
  case 'chan_freq_time'
    nchan = cfg.dim(1);
    nfreq = cfg.dim(2);
    ntime = cfg.dim(3);
    [nsmpls,nrepl] = size(dat);
  otherwise
    ft_error('Inappropriate dimord.');
end
```

We've been able to work around the issue by replacing the trials in the baseline condition with baseline trial average, assigning the activation time-axis, and running with ```cfg.statistic = 'ft_statfun_depsamplesT'``` instead.
The attachments contains example data from a public source, and a script to re-create the error, along with the hacked solution.

It seems that similar issues have been reported before:
* [ft_statfun_actvsblT & ft_timelockstatistics error](https://mailman.science.ru.nl/pipermail/fieldtrip/2016-January/022844.html)
* [ft_statfun_actvsblT only for freq data?](http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=3471)
* [Using ft_statfun_actvsblt for time domain data](https://mailman.science.ru.nl/pipermail/fieldtrip/2019-August/039512.html)
* [Active versus Baseline statisitic on time-domain data](https://mailman.science.ru.nl/pipermail/fieldtrip/2017-May/024413.html)

Kind regards,
Charlotte and Eric
[Bugreport.zip](https://github.com/fieldtrip/fieldtrip/files/8033861/Bugreport.zip)

**Comment by schoffelen** [comment]
So it seems that the person who wrote the function (who happens te be called Eric too) considered it needed to throw an error if the dimord did not contain a frequency axis. Also, in the follow up of one of the e-mails on the discussion list (question: why did you not ask your question there?) I have already replied about the inconsistency between the documentation (i.e. the help in the code suggests that time-domain data might be allowed as input), and the functional behavior of the code (i.e. the code suggests that non-frequency domain data is not allowed in the input). 

Nobody has followed up on this after my reply to one of the above threads: https://mailman.science.ru.nl/pipermail/fieldtrip/2021-March/040722.html

Have you read that reply? 

To reiterate what I wrote back then: I don't care too much about this particular statfun (because nobody has ever convinced me that it's a useful test to begin with, and especially I don't think it makes sense to use it on time domain data). 

Solving this issue to me would in the first place mean to discuss whether it makes sense to use this function at all on time domain data. I suggest to escalate this to the e-mail discussion list, so that other people can chime in, and share their thoughts. Hopefully, somebody who's willing to make her hands dirty will pick this up and provide a 'fix' in a PR to the code base.

This fix in my opinion should be a change to the docstring in ft_statfun_actvsblT which makes explicit that the test statistic 'actvsblT' only makes sense in the context in time-frequency data. Also, the website need to be checked so that this is made explicit.

**Comment by Charl0ttedeB93** [comment]
> why did you not ask your question there?

The errors seemed a longer standing issue - which I why I reported it here. I wasn't aware of the discussion. Thanks for pointing this out.

> Have you read that reply?

I wasn't familiar with that message. The discussions seems to revolve around the usefulness of an activation vs baseline analysis on time domain data, and that the result will depend on the window of temporal integration. I suppose that checking whether _any_ effect occurs after stimulus presentation can be a useful sanity check, especially within a time window of interest or using a sliding window. I will forward this topic to the discussion list.

**Comment by schoffelen** [comment]
But what does Eric say (since he is in the loop and since he contributed the original function)?

**Comment by schoffelen** [comment]
To get this out of my system I made a suggested change to the code, and used the live script + associated data as a test case.

After discussing with Eric, he pointed out that the intended functionality of ft_statfun_actvsblT is not restricted to timefrequency data. Although it could not be found back in the code when the cfg.dimord check was introduced (probably it predates github, and was added in svn or even cvs time), it was agreed that consistency between code and documentation should be achieved by changing the code, and not the documentation.

As an added note: in order for the live-script code to work correctly, it is still needed to 'artificially' update the tlckprestim time-axis, because otherwise ft_timelockstatistics (rather: ft_selectdata) throws away all time points that do not overlap across the input arguments. Also, in order to do a correct post minus pre comparison, the '1' and '2' should be swapped in the design (in comparison to the original).
