### ISSUE TITLE
Read brainvision data encoded as vectorized int32

### ISSUE THREAD

**Issue by jonrbrennan** [fieldtrip/fieldtrip#1987]
The brainvision data files distributed with [this OSF repository](https://osf.io/eyzaq/) are encoded as binary vectorized int32. These are the data from [Nieuwland et al. 2018, eLife](https://elifesciences.org/articles/33468).

Neither fieldtrip's [read_brainvision_eeg](https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/read_brainvision_eeg.m) nor EEGLAB's [pop_loadbv](https://github.com/arnodelorme/bva-io/blob/master/pop_loadbv.m) seems to handle this particular sub-format.

**Proposed Solution**

0. Update read_brainvision_eeg as follows
1. Include "int_32" as a possible format to accept along with vectorized data (ln 97)
2. set sampletype to int32 when reading binary data (ln 113)
3. scale the resulting data by the per-channel brainvision calibration factor, stored as hdr.resolution (add before ln 121) 

That returns data in microvolts which I checked against data read in using MNE's [mne.io.read_raw_brainvision](https://mne.tools/stable/generated/mne.io.read_raw_brainvision.html). Output looked to be the same up to a difference in scaling from volts to microvolts and rounding errors hovering around 3^-13.

Here's a copy of the patch I put together, beginning at ln 97 of [read_brainvision_eeg.m](https://github.com/fieldtrip/fieldtrip/blob/master/fileio/private/read_brainvision_eeg.m)

```matlab

elseif strcmpi(hdr.DataFormat, 'binary') && strcmpi(hdr.DataOrientation, 'vectorized') && any(strcmpi(hdr.BinaryFormat, {'int_32', 'ieee_float_32]'}))

  switch lower(hdr.BinaryFormat)
    case 'int_32'
      sampletype = 'int32';
    case 'ieee_float_32'
      sampletype = 'float32';
  end % case

  fid = fopen_or_error(filename, 'rb', 'ieee-le');
  fseek(fid, 0, 'eof');
  hdr.nSamples = ftell(fid)/(4*hdr.NumberOfChannels);
  fseek(fid, 0, 'bof');
  numsamples = (endsample-begsample+1);
  for chan=1:hdr.NumberOfChannels
    fseek(fid, (begsample-1)*4, 'cof');                 % skip the first N samples
    [tmp, siz] = fread(fid, numsamples, sampletype);     % read these samples
    fseek(fid, (hdr.nSamples-endsample)*4, 'cof');      % skip the last M samples
    dat(chan,:) = tmp(:)';
  end
  % JRB: scale int32 data to microvolts with the calibration factor
  if strcmp(sampletype, 'int32')
    dat = dat .* hdr.resolution; 
  end
  fclose(fid);

```

Thank you!!!

**Comment by schoffelen** [comment]
Dear Jon,

Thanks for this! Could I ask you to file this functionality as a PR to read_brainvision_eeg? 
For the sake of consistency, do you happen to know  whether vectorized int16 formatted data also is a permitted file format? It would be nice if the first if-statement on line 46 could be 'mirrored' on line 97.

Also, while you're at it :), you may consider to take the switch-box on line 48-58 out of the if-loop, so that the code for sampletype and samplesize definition does not need to be duplicated.

**Comment by robertoostenveld** [comment]
Hi @jonrbrennan 

The format is documented here https://www.brainproducts.com/productdetails.php?id=21&tab=5, but my original implementation predates the sharing of that documentation. 

The BVCDF-1.0_DocVersion-2.5_2019-12-12.pdf does not mention `INT_32` at all, whereas my implementation does have it for multiplexed data. I am quite confident that I implemented it because I encountered files in that binary format. I would therefore be fine with also adding `INT_32` for vectorized files.

Your proposed patch looks almost ok. Could you look into `hdr.resolution` to check whether than can/should be code-wise consistent between the multiplexed and vectorized formats? I suspect hdr.resolution to be 1 for `float_32` formats.

Oh, and could you also point to a specific example file in the OSF repo  that we can use for testing? I looked at it but realized that there is more than one of the labs that used BrainVision, and I don't want to download all of them.

**Comment by jonrbrennan** [comment]
Thanks both for your feedback!  

The files I've been testing with are seg_noxfo1 ([dat](https://osf.io/mvuzt/), [vhdr](https://osf.io/c6yq7/), [vmrk](https://osf.io/6qu4y/)). I don't have a license for BrainVision Recorder myself, so I don't know under what conditions this format is generated (it's not the default format I get from BrainVision recorder, which we've just started using, nor PyCorder, which we previously used).

I'll see about cleaning up the use of switch and check on hdr.resolution.

I guess It's time to figure out how to do a PR!

Jon
