### ISSUE TITLE
Getting the coil-channel correspondence from grad.tra

### ISSUE THREAD

**Issue by ftadel** [fieldtrip/fieldtrip#2040]
This problem is connected to a previous issue: https://github.com/fieldtrip/fieldtrip/issues/507

A user reported on the Brainstorm a bug related with reading a FieldTrip .mat MEG+EEG recordings file:
https://neuroimage.usc.edu/forums/t/importing-fieldtrip-data/33631/4

The link to the dataset:
https://bwsyncandshare.kit.edu/s/ytfa2okF3fNNm2m

To read correctly this file I had to adjust the Brainstorm reader, which needs to reconstruct the coil-channel correspondence independently from any other mixing matrix (CTF gradient compensation, ICA, SSP...). 
https://github.com/brainstorm-tools/brainstorm3/commit/a83914bc934a169bd6406d810b383b182584aadc

As suggested a few years ago by @schoffelen, I start by reverting the mixing documented in the `balance` field, to get the "original" `tra` matrix.

```
ftData = load('FCD-PA07-LCMV-TC-PCA-combined-sleep-Tr1.mat');
% Plot the original tra matrix
grad = ftData.dat.grad;
figure; imagesc(grad.tra);

% Get the list of montages to undo
montageList = {grad.balance.current};
if isfield(grad.balance, 'previous') && ~isempty(grad.balance.previous)
    montageList = cat(2, montageList, grad.balance.previous{:});
end
% Undo montages one by one
for iMontage = 1:length(montageList)
    % Make sure the montage is defined in the structure
    mont = montageList{iMontage};
    if ~isfield(grad.balance, mont)
        continue;
    end
    % Remove all the fields that may cause incompatibility issues
    % Fix proposed by JMS for importing the HCP pre-processed files
    for f = {'chanunitnew' 'chanunitold' 'chanunitorg' 'chantypenew' 'chantypeold' 'chantypeorg'}
        if isfield(grad.balance.(mont), f{1})
            grad.balance.(mont) = rmfield(grad.balance.(mont), f{1});
        end
    end
    % Reverse transformation
    grad = ft_apply_montage(grad, grad.balance.(mont), 'keepunused', 'yes', 'inverse', 'yes');
    % Plot "original" tra matrix
    figure; imagesc(grad.tra);
end
```

The code above produces the following figures:
![image](https://user-images.githubusercontent.com/6920058/171406453-0aacc088-bf80-4358-9700-db08a5452412.png)
![image](https://user-images.githubusercontent.com/6920058/171406561-0fd0d6b8-9bb2-4e42-ac32-fad27fdb805a.png)
![image](https://user-images.githubusercontent.com/6920058/171406579-ef498182-b246-4a87-9840-242225d55a86.png)

My problem here: there are still lots of values that are not close to zero at all after inverting all the montages.
**Am I not supposed to obtain something very close to a binary matrix simply indicating the correspondence between the channels and the coils? What am I missing?**

If this cannot be improved, I would need to reconstruct the coil-channel adjacency matrix by binarizing the "original" tra matrix above.
I came up empirically with the following code:

```
diagVal = max(abs(grad.tra),[],2);
coilChan = bst_bsxfun(@rdivide, grad.tra, diagVal);
coilChan(abs(coilChan) < 0.7) = 0;
coilChan = round(coilChan);
figure; imagesc(coilChan);
```

**Does this make any sense?
Would you have any better suggestion?**

Thanks

**Comment by schoffelen** [comment]
Hi Francois, for me the link to the data does not work, so I can only guess a bit here:

- figure 3 suggests that there is still higher order balancing (e.g. third order gradient or so), which has not been undone.
- given that the reversal of the balancing continues to be non-robust, and given the fact that Brainstorm somehow expects a 'channel position' in the data, wouldn't it be an idea to implement a generic fallback strategy to obtain those positions from the coil positions? I mean: for the majority of MEG devices the coil-to-channel mapping is static. E.g. for ctf axial gradiometers a pair of coils with the same orientation but ~5 cm apart belong to the same channel, for 4D magnetometers there's a 1-to-1 mapping etc.

**Comment by ftadel** [comment]
> for me the link to the data does not work, so I can only guess a bit here:

The file has been posted again here:
https://bwsyncandshare.kit.edu/s/faA7smobMdxsZtg

> figure 3 suggests that there is still higher order balancing (e.g. third order gradient or so), which has not been undone.

Would you be able to check if there is anything that I'm not doing correctly with it?

> wouldn't it be an idea to implement a generic fallback strategy to obtain those positions from the coil positions?

If possible, I would prefer a very generic piece of code that does not require any a priori knowledge on the types of sensors that are handled.
With MEG: in the `tra`, the weights for the balancing (i.e. the leftover after reverting everything) are always going to be relatively small compared to the weights used to define the two coils of a gradiometer, right? 
Could you think of any obvious case where the last piece of code I shared (threshold at 0.7/max) would not work?

Thanks!

**Comment by schoffelen** [comment]
Hi Francois,

I tried to undo the balancing on my end, but the latest FT-code fails on this data object. It complains about something related to the data's units, which I think could be a safety check that has been built into the code at some point in time after you adopted my suggestion for the unbalancing.

This being said, reverting the balancing by hand, I can indeed confirm that the original tra does not go back to a matrix with only 1's and 0's. I suspect that this is by mathematical design, since the 'reject' step essentially removed one (or a few) components from the data, so these cannot be anymore recovered.

Long story short, I guess that there's no way to go unequivocally back to an all 0/1 matrix if spatial components have been removed, once the information about the mixing/unmixing topographies is lost)

As to your solution, I think it's an empirical question as to whether 70% of the max is a good enough heuristic. I guess that this depends on the amount of enthusiasm with which the user has rejected topographies, or applied reference sensor balancing. I think that this could work most of the time, until we encounter a use case in which this doesn't work anymore. In the given example, it seems that the reference coils are potentially problematic, so it may be worthwhile to consider a strategy that discards them when considering the gradiometers (i.e. only look at the first 2*ngrad columns in the tra for the binarization). If you don't want to make strong assumptions about which of the columns (i.e. the coilpos) in the tra matrix correspond with the sensor coils, you may consider some elimination procedure, where - in a sorted for-loop across the rows - you incrementally eliminate columns (across the whole tra matrix) based on whether those coils already reflect a given (reference) sensor (i.e. the current instance). If you manage to start the for loop such that you handle the reference first (e.g. by starting with the rows that are closest to having only 0/1 values) then this might be a winner. This of course assumes the 'native' grad.tra to consist of only 0 and 1's, which is probably not true for e.g. elekta data...

**Comment by ftadel** [comment]
Thanks for the tests and the explanations.
I'll leave it like this until someone else complains. 
I added the links to this discussion in the code, so that we can resume the discussion easily.
