### ISSUE TITLE
Missing files in specest/private for Hilbert transfoms

### ISSUE THREAD

**Issue by NirOfir** [fieldtrip/fieldtrip#2070]
Hi, I was trying to use the Hilbert transform on data through ft_freqanalysis(), and noticed that two files that are used by ft_preproc_bandpassfilter() which are found in preproc/private are missing from specest/private, causing errors. The files are 'kaiserbeta.m' and 'isalmostequal.m'. Copying them over to specest/private solved that. Should I open a PR?

By the way, I thought that private functions would be determined by the current calling function (like ft_preproc_badpassfilter() in this case), but apparently they are determined by the first calling function (ft_freqanalysis()). Is the only solution really having to maintain a whole bunch of copies of the local functions?

Thanks!

**Comment by robertoostenveld** [comment]
MATLAB is not particularly good at dealing with dependencies, or dependencies of dependencies, etc. This [FAQ](https://www.fieldtriptoolbox.org/faq/why_are_so_many_of_the_interesting_functions_in_the_private_directories/) explains why we use private directories.

The problem you identified is a consequence of our attempts to keep the modules separate and independent of each other, see https://www.fieldtriptoolbox.org/development/module/. 

`ft_specest_xxx` functions are not supposed to access functions outside of `specest` but can access private functions in `specest\private`. Since we want regular users to use `ft_preproc_bandpassfilter` from the preproc module, we keep a copy of it in `specest/private`. Consequently, the dependencies of `ft_preproc_bandpassfilter` must also be in `specest/private`, which failed here.

Maintaining these dependencies as private functions is a bit of a hassle, but luckily they do not change that often. In the  [fieldtrip/automation](https://github.com/fieldtrip/automation) repository we have a number of scripts that help us with this, combined with some cronjobs and webhooks. On [this line](https://github.com/fieldtrip/automation/blob/824f13f3b896ee9a65d3408acd79146e9d8abed7/update-github.sh#L18) the synchronization of multiple files over the private directories is implemented. You can see this for example in 85109d0b2e23d1dddbd876951d26c8b274bc6687.

I would appreciate you doing a PR to fix this.  Please add the missing m-files to `specest/private` AND add them to the  [synchronize-private.sh](https://github.com/fieldtrip/fieldtrip/blob/master/bin/synchronize-private.sh) BASH script.

**Comment by NirOfir** [comment]
Thanks for the explanation!

I'll work on a PR.
