### ISSUE TITLE
Fieldtrip not running on the lab computer

### ISSUE THREAD

**Issue by Yidan-Zhu** [fieldtrip/fieldtrip#2083]
![fieldtrip issue](https://user-images.githubusercontent.com/47349193/182663566-3dc8a54e-f27a-4cba-a5c6-782971133e3e.jpg)

Hi developers! 

Our Fieldtrip is not running properly on the lab computer. There isn't more than one Fieldtrip version in the path, like a previous issue question mentioned: https://github.com/fieldtrip/fieldtrip/issues/1344

It runs well on my personal computer. What could the problem be and how can we solve it?
Thanks!

-Eden

**Comment by schoffelen** [comment]
Hi Eden,

Difficult to comment on this. It sounds as if there is a difference in the overall matlab setup (perhaps a version difference, of different toolboxes installed, or different external code on the matlab path) between your lab computer and your PC. Since the screenshot mentions that an infinite recursion happens when the isrow function is called, I'd first check which version of isrow you are using (by typing 'which isrow' on the matlab command line).

**Comment by schoffelen** [comment]
Is there any news on this? If not I suggest to close

**Comment by Yidan-Zhu** [comment]
We are trying to get a new computer, it might be some other problems. 

Thanks for the debugging suggestions!
