### ISSUE TITLE
ft_artifact_zvalue error

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#2095]
Issue when trials boundaries are not integer
```
Error using zeros
Size inputs must be integers.

Error in ft_artifact_zvalue (line 580)
boolvec = zeros(1,max(opt.trl(:,2)));
```

**Comment by schoffelen** [comment]
Hi @arnodelorme do you have a code and data example handy? Typically, I wouldn't expect the values in opt.trl to be non-integer to begin with...

**Comment by arnodelorme** [comment]
I do, but it will be complex to post. Simply take any data structure and make one of the data.sampleinfo fractional. I imported data, and this is the state it was in.

Note that this works with ft_preprocessing

**Comment by schoffelen** [comment]
OK, well I think that data.sampleinfo should never be fractional, so I don't know where those data came from?

Given that it works in ft_preprocessing, it sounds as if some checks and balances are performed there, but for some unknown reason these are not performed in ft_artifact_zvalue. Rather than putting a band-aid there, I think it would be good to investigate whether there are potential other locations where this might happen and/or think of a principled solution (e.g. in ft_checkdata -> round to nearest integer if not integer). Perhaps this check already exists, but ft_artifact_zvalue bypasses this somehow. In that case, a band aid would be in order. 

Now that I have your ear: would you mind having a quick peek at the coordsys related PR I posted yesterday (for eeglab2fieldtrip)? 

Merci.

PS: don't bother uploading the data, your point is clear :)

**Comment by arnodelorme** [comment]
OK, yes, I rounded the values and it woks fine now. Let me look at eeglab2fieldtrip

**Comment by schoffelen** [comment]
Hi @arnodelorme can you - on second thought - point me to where you imported the data from?

**Comment by arnodelorme** [comment]
Sure. I think it is this file.

https://openneuro.org/crn/datasets/ds002680/snapshots/1.2.0/files/sub-002:ses-01:eeg:sub-002_ses-01_task-gonogo_run-1_eeg.set

Unless it is this one

https://openneuro.org/crn/datasets/ds002718/snapshots/1.0.5/files/sub-002:eeg:sub-002_task-FaceRecognition_eeg.set

**Comment by schoffelen** [comment]
OK, when I download the data provided in the links above, and 'import' the data using ft_preprocessing (cfg.dataset = '<somename>.set',

I get two data structures with a single trial and integer sampleinfo. Hence, something else needs to be done in order to reproduce I guess

**Comment by arnodelorme** [comment]
Oh yes, sorry. You need to extract trials.

```
cfg                         = [];
cfg.dataset                 = fileNameIn;
cfg.trialfun                = 'ft_trialfun_eeglabdemo'; % this is the default
cfg.trialdef.eventtype      = { 'trigger' 'stimulus' 5 17 'animal_target' 'animal_distractor' }; % the values of the stimulus trigger for the three conditions
cfg.trialdef.eventvalue     = conditions; % the values of the stimulus trigger for the three conditions
cfg.trialdef.prestim        = 0.3; % in seconds
cfg.trialdef.poststim       = 0.7; % in seconds

cfg = ft_definetrial(cfg);
data = ft_preprocessing(cfg);
```
[ft_trialfun_eeglabdemo.m.zip](https://github.com/fieldtrip/fieldtrip/files/9396119/ft_trialfun_eeglabdemo.m.zip)

**Comment by schoffelen** [comment]
OK, thanks. The non-integer sample indices are not caused by FT, but they are inherent in the EEG data structure: the events are extracted from the EEG struct, because read_eeglabheader (in fieldtrip/fileio/private) stores the EEG struct in hdr.orig. Next, read_eeglabevent (in fieldtrip/fileio/private) copies over the event's latency (EEG speak) into the event's sample (FT speak), on line 76.

**Comment by arnodelorme** [comment]
Correct but the ft_artifact_zvalue crash while the ft_preprocessing function returns:

```
Warning: The filter type you requested is not recommended for neural signals, oreading and preprocessing trial 208 from 300
Warning: rounding "begsample" to the nearest integer 
Warning: rounding "endsample" to the nearest integer 
Warning: The filter type you requested is not recommended for neural signals, oreading and preprocessing trial 209 from 300
Warning: rounding "begsample" to the nearest integer 
Warning: rounding "endsample" to the nearest integer 
Warning: The filter type you requested is not recommended for neural signals, oreading and preprocessing trial 210 from 300
Warning: rounding "begsample" to the nearest integer 
Warning: rounding "endsample" to the nearest integer 
Warning: The filter type you requested is not recommended for neural signals, oreading and preprocessing trial 211 from 300
Warning: rounding "begsample" to the nearest integer 
Warning: rounding "endsample" to the nearest integer 
```

For consistency, ether you crash in both cases or handle both cases.

**Comment by robertoostenveld** [comment]
Thanks both for working on this. For reference, I think that there are a few situations that can cause sample numbers (for `trl` and `sampleinfo`) to become non-integers. One is BIDS datasets with an `events.tsv` that lists the events in seconds (with potential rounding off errors). Another is similar: if events are stored in the original file as timestamps or time (in seconds) and not samples, this might be the case in XDF, but also in BrainVision vmrk files. I expect that most FT readers will round it already off in those cases, but just to be aware of the possible occurrence.

Technically in the code it would be better to do the rounding off at the location where the integers are required, and not at the location where the original data is being read. But I don't see a reason to now search through all code to make that change.
