### ISSUE TITLE
Should I divide the blackrock data with 4?

### ISSUE THREAD

**Issue by Jinboasltw** [fieldtrip/fieldtrip#2102]
Hi,
When I read the code of the openNSx.m code provide by blackrock, I found they say (line 962 of openNSx.m)：
```matlab
        disp('The data is in unit of 1/4 uV. This means that 100 in the NSx file equals to 25 uV. All values must be divided by 4.');
```
So, if i imported the data with fieldtrip, shoud i dividie the data with 4, before any analysis.

**Comment by schoffelen** [comment]
In principle, the code in external/npmk is not under control of the FieldTrip team. I guess that you need to check with the blackrock folks directly about this.

By the way: the version of openNSx.m that is in this repository (in external/npmk) has less than 962 lines (I might be wrong here), so it is unclear what exact code you are referring to.

**Comment by Jinboasltw** [comment]
That's weird. I refer to the openNSx.m from their github resp. https://github.com/BlackrockNeurotech/NPMK/blob/master/NPMK/openNSx.m
Seem FieldTrip use an old version of openNSx.

Yes. I understand that the code in external/npmk is not under control of the FieldTrip team. The problem is that the importing of blackrock is handled by ft_preprocessing func as the tutorial said. However, it seem the ft_preprocessing not applying the coverting.  

Follow the FieldTrip tutorial：
```matlab
cfg = [];
cfg.dataset = 'yourfile.nsX'
% you can specify additional preprocessing options, such as filters
data = ft_preprocessing(cfg)
```

Seem this code call ft_read_data for io， within this function I found:
```matlab
 case 'blackrock_nsx'
    % use the NPMK toolbox for the file reading
    ft_hastoolbox('NPMK', 1);
    % ensure that the filename contains a full path specification,
    % otherwise the low-level function fails
    p = fileparts(filename);
    if isempty(p)
      filename = which(filename);
    end
    
    chan_sel=ismember(deblank({hdr.orig.ElectrodesInfo.Label}),hdr.label); % matlab 2015a
    %chan_sel=contains({hdr.orig.ElectrodesInfo.Label},hdr.label); %matlab 2017a
    
    orig = openNSx(filename, 'channels',find(chan_sel),...
      'duration', [(begsample-1)*hdr.orig.skipfactor+1, endsample*hdr.orig.skipfactor],...
      'skipfactor', hdr.orig.skipfactor);
    
    d_min=[orig.ElectrodesInfo.MinDigiValue];
    d_max=[orig.ElectrodesInfo.MaxDigiValue];
    v_min=[orig.ElectrodesInfo.MinAnalogValue];
    v_max=[orig.ElectrodesInfo.MaxAnalogValue];
    
    %calculating slope (a) and ordinate (b) of the calibration
    b=double(v_min .* d_max - v_max .* d_min) ./ double(d_max - d_min);
    a=double(v_max-v_min)./double(d_max-d_min);
    
    %apply v = a*d + b to each row of the matrix
    dat=bsxfun(@plus,bsxfun(@times, double(orig.Data), a'),b');
```

as you can see, the output by openNSx is not converted to uv, its unit is 0.25uv.
```matlab
orig = openNSx(filename, 'channels',find(chan_sel),...
      'duration', [(begsample-1)*hdr.orig.skipfactor+1, endsample*hdr.orig.skipfactor],...
      'skipfactor', hdr.orig.skipfactor);
```
from openNXs:
```matlab
%   'uV':         Will read the spike waveforms in unit of uV instead of
%                 raw values. Note that this conversion may lead to loss of
%                 information (e.g. 15/4 = 4) since the waveforms type will
%                 stay in int16. It's recommended to read raw spike
%                 waveforms and then perform the conversion at a later
%                 time.
%                 DEFAULT: will read waveform information in raw.
```

**Comment by schoffelen** [comment]
If the blackrock folks have changed the code on their end, they may not have considered potential backward (in)compatibility issues that are related to software that depends on the code. It is unclear to me 
a) whether the older version of the code as shipped with FieldTrip is now invalid, i.e. does using that code 'under-the-hood' in ft_preprocessing lead to wrong scaling of data?
b) whether using the newer version of the blackrock code, with the current FT-code leads to wrong scaling?

This needs to be investigated thoroughly before any plan to address any potential issue can be made. I cannot contribute much to this, because I am not a blackrock user myself, and we only have limited amounts of test data on our end.

I suggest that you liaise with the blackrock support in order to find an answer to the above points. In the past we have been in touch with them https://github.com/fieldtrip/fieldtrip/issues/1323 but this referenced issue was not followed up at the time.

**Comment by Jinboasltw** [comment]
Thank you. I will try to liaise with the blackrock support.

**Comment by schoffelen** [comment]
Here is some old e-mail correspondence I found:

Hi Robert,
 
If FieldTrip is just using the NPMK plugin as it’s method for parsing files then this isn’t an issue, since NPMK will be compatible with the updated file-spec. I’ll leave the page as is, the main concern was if the software did its own parsing of our file types.
 
Thanks,
Thomas
 
From: Robert Oostenveld <[r.oostenveld@donders.ru.nl](mailto:r.oostenveld@donders.ru.nl)> 
Sent: Wednesday, June 23, 2021 12:15 PM
To: Thomas Lancaster <[tlancaster@blackrockmicro.com](mailto:tlancaster@blackrockmicro.com)>
Cc: Jan-Mathijs Schoffelen <[jan.schoffelen@donders.ru.nl](mailto:jan.schoffelen@donders.ru.nl)>
Subject: Re: Blackrock File-Spec Changes
 
Hi Thomas, 
 
Thanks. We are not active users of Blackrock at the Donders in Nijmegen, but other users of FieldTrip may be. 
 
I suggest this is added to the page [https://www.fieldtriptoolbox.org/getting_started/blackrock/](https://urldefense.com/v3/__https://www.fieldtriptoolbox.org/getting_started/blackrock/__;!!HJOPV4FYYWzcc1jazlU!t2bGjReKD5FDbW_MNJ6Y-RzbDMErDFYUt0zzyqyS-q_iWqX8N48mjSyxQ1LpVW5dFxQO4tVZ$), which is a MarkDown page that can be editted here [https://github.com/fieldtrip/website/blob/master/getting_started/blackrock.md](https://urldefense.com/v3/__https://github.com/fieldtrip/website/blob/master/getting_started/blackrock.md__;!!HJOPV4FYYWzcc1jazlU!t2bGjReKD5FDbW_MNJ6Y-RzbDMErDFYUt0zzyqyS-q_iWqX8N48mjSyxQ1LpVW5dFzGNreyB$). Feel free to make an edit to taht page and send it as a pull request (just click on the pencil button at the right upper corner of the page).
 
best regards,
Robert
 
 


On 23 Jun 2021, at 19:53, Thomas Lancaster <[tlancaster@blackrockmicro.com](mailto:tlancaster@blackrockmicro.com)> wrote:
 
Hi Robert and Jan-Mathijs,
 
We wanted to reach out to cover some changes coming to Blackrock Microsystems file formats. Since FieldTrip supports Blackrock’s file formats, we wanted to reach out to you and detail the changes in our file specifications. This effort is to ensure that you’re properly equipped to answer questions that may come in from users, and to allow you an opportunity to update your integration if needed.
 
The two major changes are as follows:
Timestamps are now stored as unsigned 64-bit integers instead of 32-bit integers.
We’ve added a new packet to define when a file starts, stops, pauses, or is resumed.
 
Some other minor changes have been made, but we don’t expect that they are significant enough to change the usage parameters of our file formats.
Below is a link to the latest file-spec document we’ve produced, which includes the above changes.
[https://www.blackrockmicro.com/wp-content/ifu/LB-0023-7.00_NEV_File_Format.pdf](https://urldefense.com/v3/__https:/www.blackrockmicro.com/wp-content/ifu/LB-0023-7.00_NEV_File_Format.pdf__;!!HJOPV4FYYWzcc1jazlU!rFz98xQoKVxh0qT19pL0G-SArlY_pqJiK4R_ofu57EEYXZgGKH9nSGqoYjZCw-_OilSVFsHGmRc$)
 
Please let us know if you have any questions, or if this inquiry needs to be redirected.
 
Sincerely,
Thomas Lancaster
Support Engineer
Blackrock Microsystems

**Comment by schoffelen** [comment]
and:

Hi Jan-Mathijs,
 
Yes, it should be true for the latest version on github, which is 5.5.2.0 if I’m recalling correctly. The code should be almost completely backwards compatible (works with specs 2.3 and 3.0; 2.3 was released in 2011), and we recommend going ahead with the upgrade.
 
Thanks for your help!
- Thomas
 
From: Schoffelen, J.M. (Jan Mathijs) <[janmathijs.schoffelen@donders.ru.nl](mailto:janmathijs.schoffelen@donders.ru.nl)> 
Sent: Thursday, June 24, 2021 2:03 PM
To: Thomas Lancaster <[tlancaster@blackrockmicro.com](mailto:tlancaster@blackrockmicro.com)>
Cc: Oostenveld, R. (Robert) <[robert.oostenveld@donders.ru.nl](mailto:robert.oostenveld@donders.ru.nl)>; Schoffelen, J.M. (Jan Mathijs) <[janmathijs.schoffelen@donders.ru.nl](mailto:janmathijs.schoffelen@donders.ru.nl)>
Subject: Re: Blackrock File-Spec Changes
 
Hi Thomas,
 
If you say 'NPMK will be compatible with the updated file-spec’ I guess you mean that this is true for the latest version of NPMK on github? Is that code also backwards compatible? If so, we may consider updating the version of the code that is shipped in fieldtrip/external/npmk to avoid unexpected functional behavior with the new fileformat.
 
Best wishes,
Jan-Mathijs
 
 
 


On 24 Jun 2021, at 21:56, Thomas Lancaster <[tlancaster@blackrockmicro.com](mailto:tlancaster@blackrockmicro.com)> wrote:
 
Hi Robert, 
 
If FieldTrip is just using the NPMK plugin as it’s method for parsing files then this isn’t an issue, since NPMK will be compatible with the updated file-spec. I’ll leave the page as is, the main concern was if the software did its own parsing of our file types.
 
Thanks,
Thomas

**Comment by schoffelen** [comment]
Hi @Jinboasltw what is the status of this? Any news from the blackrock folks?

**Comment by schoffelen** [comment]
Hi @Jinboasltw what is the status of this? Any news from the blackrock folks?

**Comment by schoffelen** [comment]
Hi @Jinboasltw how would you propose to take this forward?

**Comment by schoffelen** [comment]
Closing for now due to lack of interest of the main stakeholder. Feel free to reopen when appropriate

**Comment by Jinboasltw** [comment]
Hi, sorry for my late response. I just notice this message here.

For correct importing black rock data with fieldtrip, I have to change some code of fieldtrip.

Here is the original version in `ft_read_data.m`
```matlab
d_min=[orig.ElectrodesInfo.MinDigiValue];
d_max=[orig.ElectrodesInfo.MaxDigiValue];
v_min=[orig.ElectrodesInfo.MinAnalogValue];
v_max=[orig.ElectrodesInfo.MaxAnalogValue];

b=double(v_min .* d_max - v_max .* d_min) ./ double(d_max - d_min);
a=double(v_max-v_min)./double(d_max-d_min);
```

Here, the `a` is wrong. Because, `d_min`, `d_max`, `v_min`, `v_max` all is within `int16` format. It‘s value range is [-32768,32767], so the `d_max-d_min` with over this limits. After a simple modification, all work is done:
```matlab    
d_min=double([orig.ElectrodesInfo.MinDigiValue]);
d_max=double([orig.ElectrodesInfo.MaxDigiValue]);
v_min=double([orig.ElectrodesInfo.MinAnalogValue]);
v_max=double([orig.ElectrodesInfo.MaxAnalogValue]);
```

<img width="2549" alt="Screenshot 2023-03-15 at 08 56 50" src="https://user-images.githubusercontent.com/6925515/225176080-5713b4cb-e6a7-4318-b658-60fce2955dd0.png">

**Comment by schoffelen** [comment]
Thanks for picking this up again!
Is the format of your data sufficiently generic, so that your proposed change does not break the code for people who might have slightly differently formatted data (e.g. using older acquisition systems, or different recording parameters)?
If so, could you please make a pull request (PR) with your suggested code changes, and also send us a small test data file, so that we can use that for our battery of test functions on our end?

**Comment by Jinboasltw** [comment]
Yes. Our data is a generic data format from blackrock system without any custom modification. Beside, the changes will ensure the parameter `b` will not exceeding the limit of int16.

I will make the PR, and the data will be send to you with dropbox links within the PR.

**Comment by Jinboasltw** [comment]
@schoffelen Here is my PR: Update ft_read_data.m #2213
