### ISSUE TITLE
lineattributes_common does not apply matrix RGB linecolor values to the figures 

### ISSUE THREAD

**Issue by duygu-sahin** [fieldtrip/fieldtrip#2112]
**lineattributes_common does not apply a matrix RGB linecolor **
In the previous versions, multiplots' and singleplots' line colors could be adjusted with a simple matrix, not necessarily defined for each channel but defined only once. 
One example for three lines would be : 

cfg = [];
cfg.showlabels = 'yes';
**cfg.linecolor**  = [125 15 77
			 125 122 246
			 53 64 85]./255;
cfg.linewidth   = 0.6;

**To Reproduce**
1. Preparing the configurations for multiplot like:
cfg = [];
cfg.showlabels = 'yes';
**cfg.linecolor**  = [125 15 77
			 125 122 246
			 53 64 85]./255;
cfg.linewidth   = 0.6;
cfg.layout=layout;

2. Running the multiplot function
ft_multiplotER(cfg, grAvgT1L1, grAvgT1L2, grAvgT1L3);

**Expected behavior**
The expected behaviour would be the lines being plotted in the colors specified as burgundy, purple and gray.
However the lineattributes function reverts them back to blue, red and green.

**Environment and versions (please complete the following information):**
 - Operating System: [e.g. Windows 10]
 - MATLAB version [e.g. R2022a]
 - FieldTrip version [most recent master branch from github downloaded on 23rd of September 2022]

**Personal Fix**
Changing the first if statement to isfield and adding one more elseif statement under the first if statement works.

The added elseif statement checks for the existence of the linecolor field, it being a double and a matrix and then checks for whether the matrix uses values equal and under one. If not fixes by dividing the values to 255. 

% linecolor
if ~isfield(cfg, 'linecolor')  % the first statement 
  cfg.linecolor = [
    0    0    1
    0.75 0    0
    0    1    0
    0.44 0.19 0.63
    0    0.13 0.38
    0.5  0.5  0.5
    1    0.75 0
    1    0    0
    0.89 0.42 0.04
    0.85 0.59 0.58
    0.57 0.82 0.31
    0    0.69 0.94
    1    0    0.4
    0    0.69 0.31
    0    0.44 0.75];
elseif isfield(cfg, 'linecolor') && isa(cfg.linecolor, 'double') && ismatrix(cfg.linecolor) % The added elseif statement
    if (mean(mean(cfg.linecolor)) <= 1)
        cfg.linecolor = cfg.linecolor;
    else
        cfg.linecolor = cfg.linecolor./255;
    end
...

**Comment by schoffelen** [comment]
Thanks for reporting this. I can imagine something is going wrong with the logic in handling the different ways in which the linecolor can be specified in the caller function. It would be great if you could post your suggested changes in a Pull Request. This would give more visible credit to you for providing the fix. Are you game for giving it a shot?

This being said, the suggested changes pasted in your comment makes me somewhat confused, because the 'scaffold' of the if-else statement looks different from what I see in the repository version of the code. Notably, cfg.linecolor is always defined (because by default it is defined empty, as per line 62 of the current code).

Then (and this is what seems to be going wrong for you) on line 86 it states if ~isequal(cfg.linecolor, 'spatial'), and this overrules any Nx3 specification by the user. So I would an && ~isempty(cfg.linecolor) to that line, rather than the changes you suggested.

Then, we could build in an additional check for all values <=1, but I'd rather rely on the all(all(, than on the mean(mean( heuristic. Also, a conversion from integer valued 0-255 specifications might be a good addition, but also in that case I would build in a check whether the numbers are as expected (and perhaps throw a warning if the conversion is taking place).

**Comment by schoffelen** [comment]
Since I didn't hear back from @duygu-sahin I went ahead and provide a fix in PR #2113

**Comment by schoffelen** [comment]
This will become available in the release version of FT soon.
