### ISSUE TITLE
Add support for the SimNIBS LUT.txt file to ft_read_atlas

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#2151]
@ualsbombe please give it a try

**Comment by ualsbombe** [comment]
Please have a look at this pull request
https://github.com/fieldtrip/fieldtrip/pull/2156

output at the moment looks like this
![billede](https://user-images.githubusercontent.com/17312936/206724529-3d18cc83-d9ba-44b7-ae21-4fe39d51a33c.png)
based on this input 
![billede](https://user-images.githubusercontent.com/17312936/206724678-32436aa1-0b30-485c-93f0-916b5a5d4ce5.png)

At the moment, most of the cell entries in tissuelabels are empty because I made them match the indices from the look-up table that jump from 10 to 100 to 500.

I will upload my test script next and make sure that it is compatible with the path @robertoostenveld  has uploaded

**Comment by ualsbombe** [comment]
hmm, realised that I am not sure how to make a test script for this: would I have to exchange my personal path (see `path` above) with this `/home/common/matlab/fieldtrip/data/test/original/simnibs`?

**Comment by schoffelen** [comment]
this has been addressed with PR #2156
