### ISSUE TITLE
Lack of data using the function load_xdf

### ISSUE THREAD

**Issue by Lorenzo4321** [fieldtrip/fieldtrip#2163]
Hello everyone!

These days I was analyzing my data (EEG, Force and Markers), collected with LabRecorder.
In two subjects, when I use the Matlab formula load_xdf, I got the message "I got a block of zero length, scanning forward to next block boundary forward scan reached end of the file with no matches.".

Looking at the resulting Matlab structure, I have only a small amount of data (30 MB) even if the XDF files still contain all the data (501 and 472 MB, respectively). I hope they are not irreversibly damaged.

Used code:
data = load_xdf(strcat(xdf_Fold, name, '.xdf'));
Data with issues:
https://www.dropbox.com/home/Files_with_issue_LorenzoGuarnieri

Thanks so much in advance!

**Comment by schoffelen** [comment]
Hi Lorenzo,

The link to the files in dropbox does not work for me.

Also, the load_xdf function is not maintained by us, so we cannot comment on it being faulty, or whether you have an issue with your data.

Also, the load_xdf function that is shipped with fieldtrip (in fieldtrip/external) seems to be older than the most recent load_xdf version on github. The older function does not explicitly throws the warning that you mentioned in your post, so that suggests that you use a different version of load_xdf than the one which is shipped with FieldTrip.

I think that you need to consult with your lab's technician / supervisor to look into this in more detail. Once you have found out that it is not a problem with your data, you need to consult with the people who maintain the load_xdf code.

**Comment by robertoostenveld** [comment]
Please see https://github.com/xdf-modules/xdf-Matlab/tree/master where the `load_xdf` originates from and is being maintained. FieldTrip just includes a copy of that function in the `fieldtrip/external` directory.
