### ISSUE TITLE
File-IO failing on Henson Wakeman sub-emptyroom

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#2171]
This is using File-IO of Dec 12, 2022

![Screen Shot 2023-01-23 at 4 04 42 PM](https://user-images.githubusercontent.com/1872705/214180157-e1d95c48-720e-406f-b8db-d6c211414f0c.png)

**Comment by arnodelorme** [comment]
https://openneuro.org/datasets/ds000117/versions/1.0.5

**Comment by robertoostenveld** [comment]
that is expected and correct behaviour. If you were to read the file, the MEG signals would be all messed up due to the internal active shielding having overcompensated the environmental noise by also feeding back some parts of the brain signal. MaxFilter should be applied here for correct MEG data, or you should explicitly specify the option `checkmaxfilter` as False. The latter allows you to process non-MEG signals and triggers.
