### ISSUE TITLE
error with dipole scan + EEG precomputed leadfield 

### ISSUE THREAD

**Issue by mcpiastra** [fieldtrip/fieldtrip#2188]
hi, I have been trying to compute a dipole scan with an EEG pre-computed leadfield and timelocked data.
This is the code I used for the dipole scan:
```
input_fem = [];
input_fem.time = 1;
input_fem.label = avg_787.label;
input_fem.elec = elec_787;
input_fem.avg = avg_787.avg;

cfg_dipfit = [];
cfg_dipfit.numdipoles   = 1;                              
cfg_dipfit.headmodel    = [];
cfg_dipfit.sourcemodel  = lf_787;
cfg_dipfit.gridsearch   = 'yes';                           
cfg_dipfit.nonlinear    = 'no';
cfg_dipfit.elec         = elec_787;                           
cfg_dipfit.latency      = 0.01;                               
cfg_dipfit.channel      = 'EEG';
cfg_dipfit.reducerank   = 'no';

dipfit              = ft_dipolefitting(cfg_dipfit,input_fem);
```
where avg,elec,lf_787 are the timelocked data, elec file and leadfield for dataset 787, resp.

The error:
```
Unrecognized field name "cond".

Error in eeg_infinite_dipole (line 50)
cond     = vol.cond;

Error in ft_compute_leadfield (line 488)
      lf = eeg_infinite_dipole(dippos, sens.elecpos, headmodel);

Error in ft_dipolefitting (line 578)
      lf = ft_compute_leadfield(dip.pos, sens, headmodel,
      leadfieldopt{:});

Error in show_results_787 (line 83)
dipfit              = ft_dipolefitting(cfg_dipfit,input_fem);
```
is given by the fact that after identifying the dipole with minimum error (ft_dipolefitting line 497), the leadfield is computed again in ft_dipolefitting line 578, where the headmodel is assigned to be "infinite", instead of retrieving the leadfield that is already computed.

**Comment by mcpiastra** [comment]
after discussing it with @schoffelen, I will make some changes in my local fork and see if I can fix it locally.
The idea would be to copy the corresponding leadfield along with the dipole that gives the minimum error, so that this leadfield can be reused in line 578 for the "compute the model potential distribution and the residual variance".

**Comment by mcpiastra** [comment]
I do not know how to change the label btw

**Comment by schoffelen** [comment]
Indeed, just to add some info:
The context is to perform ft_dipolefitting on FEM-precomputed leadfields. The only sensible approach is then to use cfg.gridsearch = 'yes', and cfg.nonlinear = 'no'

Yet, irrespective of whether cfg.nonlinear was yes or no, the final solution will be computed by a call to ft_compute_leadfield, given the optimal dipole parameters. This is impractical in the context of a FEM headmodel, since it will require a lengthy re-computation. Hence MC's workaround to add an empty headmodel to ft_dipolefitting. This - in the context of EEG - leads to a low-level error, since an infinite volume conductor for EEG expects a conductivitiy to be specified. 

The idea thus is to add to the (intermediate) dip structure the (possibly already precomputed) leadfield corresponding to the optimal solution during the gridsearch, which allows a bypass of the re-computation of the leadfield in the final part of the code. Clearly, the leadfield corresponding to the optimal grid point(s) will need to be removed if cfg.nonlinear = 'yes'.

**Comment by mcpiastra** [comment]
I created a pull request #2339
The corresponding leadfield mentioned above was already saved at line 420 in the variable lf, now the code will check if the variable lf exists or not, and recompute the leadfield only if lf does not exist.
