### ISSUE TITLE
De-meaning biosemi data after ft_preprocessing?

### ISSUE THREAD

**Issue by alexisdmacintyre** [fieldtrip/fieldtrip#2200]
Unless I explicitly re-define `cfg.preproc.demean = 'yes';` for every new `cfg`, `ft_databrowser` doesn't work correctly for my biosemi data. This is a bit confusing when practicing along with the tutorials, including this [biosemi-specific documentation](https://www.fieldtriptoolbox.org/example/biosemi/). The docs and biosemi instruction manual do make it clear that you need to deal with offline referencing, but it seems as a reader that this would have been taken care of by `ft_preprocessing` the first time?

I run this code to get started:

```
cfg = [];

cfg.dataset = eegFilePath;

% Define trials
cfg.trialfun = 'ft_trialfun_my_function';
[cfg] = ft_definetrial(cfg);

% Load EEG data
cfg.preproc.reref = 'yes';
cfg.refmethod = 'average;
cfg.channel = 1:64;
cfg.preproc.refchannel = 'all';
cfg.preproc.demean = 'yes';
cfg.elec = elec;
trialsData = ft_preprocessing(cfg);

working_cfg = cfg; % Keep this for later
```
Any subsequent call to other fieldtrip functions after resetting the `cfg` will cause me the same issue, but here is one example with resampling:

```
cfg = [];
cfg.resamplefs = workingFs;
cfg.detrend = 'yes';


% cfg.demean = 'yes'; % Un-commenting this line does not fix my issue
cfg.preproc = cfg_working.preproc; % Only this versions works

data_fixed = ft_resampledata(cfg, trialsData); % Edited: should be the output from from ft_processing
ft_databrowser(cfg, trialsData);
```
If I follow the biosemi example analysis (and omit adding the extra de-meaning fields in each new  `cfg`), my data end up looking like this:

![ex](https://user-images.githubusercontent.com/55560694/221668271-7fb345a7-4e09-4782-b3f7-34ad89254324.png)

My question is whether this just a problem for `ft_databrowser`, or if my data are not properly de-meaned for further analysis? I am using a recently cloned version of fieldtrip with MATLAB 2020b. Either way, it seems that adding a warning for users of biosemi data where necessary, biosemi-speicifc fields are missing could help make this step clearer.

**Comment by schoffelen** [comment]
Hi Alexis @alexisdmacintyre, I think that this would be a question that is better suited for our e-mail discussion list, so that it reaches a larger audience, it will reach more people potentially benefitting from the discussion, and more people who are able to chime in.

I quickly tried to understand what you report, but I am still a bit confused.

1) the first section of your code creates a variable called trialsData, but later on you use the variable data_fixed as input to ft_resampledata and ft_databrowser
2) I could not find easily back in the online documentation that you referenced above, the exact section that causes the confusion that you describe in the pasted code example
3) In your subsequent calls to ft_resampledata and ft_databrowser, you don't clear the cfg in between, so it would require some explicit code checking to evaluate which defined options are functional for any (or both) of the function calls
4) ft_databrowser does not produce an output argument, and the 'processing' options are - if functional - only effective within the scope of the function. In other words they are applied in order to change the morphology of the visualized signals, not to change the signals in the stored variables.

Perhaps those considerations might already point you into the right direction, but if not, feel free to ask your reformulated question on the fieldtrip discussion list.

**Comment by alexisdmacintyre** [comment]
Hi @schoffelen ! Thanks for your reply. Sorry, I was pasting snippets from longer code to try to make things clear but just made it more confusing. The data I show here should just be the same "trialsData" (i.e., the output from` ft_processing`) and each `cfg` should be cleared between fieldtrip functions. 

This doesn't change my problem: so long as I don't explicitly include a .preproc field inside every new cfg, my biosemi data look something like the screenshot (unlike the tutorial I linked, where this field is not explicitly added), but perhaps some users on the discussion list will recognise the issue.

**Comment by robertoostenveld** [comment]
Hi Alexis, you seem to be mixing up the demeaning and the re-referencing. 

From https://www.biosemi.com/faq/cms&drl.htm 

> Regardless of the reference selected in ActiView, ActiView always only saves the raw signals, not referenced. In your analysis software, you can select any electrode or combination of electrodes to be the "reference"; the choice is made entirely in software. When no reference is selected in your analysis software, then the signals will be displayed with respect to the CMS electrode. Displaying in raw mode, will not provide the full CMRR, and should only be used as a quick check of the electrodes. Only after a reference is selected, the full 80 dB CMRR is achieved.

hence according to Biosemi you should re-reference to obtain the best common mode rejection; the 50 or 60Hz in your screenshot (and other noise) will also be way smaller when you re-reference.

The ft_preprocessing and the ft_databrowser function does not know about the details of the amplifier, or the file format, or whether your data has been processed in external software and then written back to disk in BDF format. So it does not automatically select the most optimal configuration; that remains up to you.

The email list would indeed be a better way to ask support from others experienced with the Biosemi system and file format.
