### ISSUE TITLE
write a getting started with SimNIBS page 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#2266]
under  https://www.fieldtriptoolbox.org/getting_started/

**Comment by robertoostenveld** [comment]
As discussed with @jduemose and @schoffelen, to be based on https://www.fieldtriptoolbox.org/tutorial/headmodel_eeg_fem/but use a better EEG subject with two MR contrasts

**Comment by robertoostenveld** [comment]
The new page is there, mostly empty for now.

**Comment by jduemose** [comment]
Thanks, I will have a look. Btw, let me know if you find/have a suitable example subject (with a decent T1 and EEG electrode positions) in your tutorial repository that you want me to use.

**Comment by robertoostenveld** [comment]
Have a look at https://www.fieldtriptoolbox.org/faq/what_types_of_datasets_and_their_respective_analyses_are_used_on_fieldtrip/#meg-audodd and the tutorials in which it is used. It might be that the T1 is not of the greatest quality, but I am not 100% sure.

**Comment by jduemose** [comment]
Hey hope you are enjoying the summer!

I have now created a first version which you can find here https://github.com/jduemose/website/blob/master/getting_started/simnibs.md. I included a few illustrations/screenshots which are located in https://github.com/jduemose/website/tree/master/assets/img/getting_started/simnibs. I am not able to view them though (do I need to build the website locally in order to do that?) but I tried to include them as in the other FEM tutorial.

I just used the same MR image as in the other FEM tutorial (https://www.fieldtriptoolbox.org/tutorial/headmodel_eeg_fem). It is not super (e.g., resolution-wise) but fine to illustrate the concepts. I wasn't able to find a better scan in the database but we can also consider adding our ernie model perhaps? That has T1 and T2 as far as I know. I can talk to Axel (our PI) when I get back from vacation depending on what you guys think.

I will be on holidays for the next few weeks so take your time and let me know what you think.

**Comment by schoffelen** [comment]
Hi @jduemose Jesper, first of all our apologies for having dropped this for so long! I think we should have merged your suggested getting started page right away, because it's (more or less) fully functional. 

I just tried it, with a fresh install of Simnibs 4.1.0 and it runs through nicely. In order to also give you the digital credits, would you mind (and have the time) to create a PR out of the referenced page in your fork of the website repo?

Then, you may consider changing the following piece of code:

```
% matlab
fwd = load fem_Subject01/Subject01_leadfield_elec_subsampling-10000-fwd.mat;
src = load fem_Subject01/Subject01_leadfield_elec_subsampling-10000-src.mat;
morph = load fem_Subject01/Subject01_leadfield_elec_subsampling-10000-morph.mat;
```

In my matlab, this does not work. If you remove 'fwd = ' and 'src = ' the load command will automatically assign the variables fwd and src in matlab memory (because they are called like this in the mat files). Also, when I ran the simnibs pipeline for the forward model, on my end no 'morph' file was generated, so I could not load it in...

**Comment by schoffelen** [comment]
https://github.com/fieldtrip/website/pull/824
