### ISSUE TITLE
Adding all subfolders of FieldTrip seems to cause built-in uistack to fail

### ISSUE THREAD

**Issue by raacampbell** [fieldtrip/fieldtrip#2283]
**Describe the bug**
If the user adds all subfolders of FieldTrip  to their path the MATLAB built-in uistack to fails. A full description can be found here:
https://github.com/raacampbell/shadedErrorBar/issues/24

I have no idea how this happens (see thread above) but presumably you have a function that should be named differently or be in a `private` sub-directory and is not. 

**To Reproduce**
1. Add all FieldTrip sub-dirs to path.
2. Install [shadedErrorBar](https://github.com/raacampbell/shadedErrorBar).
3. Running the examples of shadedErrorBar will fail (see thread cited above).

**Expected behavior**
FieldTrip should not break MATLAB built-ins. 

**Environment and versions (please complete the following information):**
 - Operating System: Unknown
 - MATLAB version: 2021a
 -  FieldTrip version: Unknown
 -
**Additional context**
I am the dev of shadedError bar not the original reporter of the bug

**Comment by hisunjiang** [comment]
I had this problem when using [shadedErrorBar](https://github.com/raacampbell/shadedErrorBar) and FieldTrip.

### Environment and versions
- Operating System: win10
- MATLAB version: 2021a
- FieldTrip version: fieldtrip-20230613

### Raised error
When running examples provided in the shadedErrorBar repo., the following error was raised:
```
Error using strfind
Search term must be a text or pattern scalar.

Error in contains (line 88)
tf = ~cellfun(@isempty, strfind(s, pattern));

Error in matlab.ui.internal.prepareFigureFor

Error in uistack (line 69)
    matlab.ui.internal.prepareFigureFor(morphFig, mfilename('fullpath'))

Error in shadedErrorBar>makePlot (line 259)
        uistack(H.mainLine,'top')

Error in shadedErrorBar (line 158)
H = makePlot(x,y,errBar,lineProps,transparent,patchSaturation,plotAxes);

Error in test (line 9)
shadedErrorBar(x,y,{@mean,@std},'lineprops','-b','patchSaturation',0.33)

```

**Comment by robertoostenveld** [comment]
Please see https://www.fieldtriptoolbox.org/faq/should_i_add_fieldtrip_with_all_subdirectories_to_my_matlab_path/

Rather than adding all subfolders (which will for sure cause errors, for example with https://github.com/fieldtrip/fieldtrip/tree/master/compat) only the top-level path should be added by hand and all others by [ft_defaults](https://github.com/fieldtrip/fieldtrip/blob/master/ft_defaults.m) (at initial startup) and [ft_hastoolbox](https://github.com/fieldtrip/fieldtrip/blob/master/utilities/ft_hastoolbox.m) (upon demand).

**Comment by robertoostenveld** [comment]
since the error message above mentions the `contains` function 

```
Error in contains (line 88)
tf = ~cellfun(@isempty, strfind(s, pattern));
```

I suspect that the folder [matlablt2016b](https://github.com/fieldtrip/fieldtrip/tree/master/compat/matlablt2016b) folder was added to the path. That should only be added to the path for MATLAB versions less than 2016b, as prior to that MATLAB release the contains function did not yet exist.

**Comment by robertoostenveld** [comment]
See also #899

**Comment by raacampbell** [comment]
Have you considered making this a package and importing locally to a function based on MATLAB version? That would effectively automate the process of adding folders to the path based on MATLAB version. Also the errors we are finding here would never occurr.

**Comment by robertoostenveld** [comment]
We have been distributing FieldTrip as a zip file for 15 years, and with the very small team we are already struggling to keep up with our own research besides supporting others that use the software that we share. So it might happen, but don't hold your breath.

I believe this was also brought up in https://www.fieldtriptoolbox.org/development/project/code_review/#322-private-directories-versus-packages.  Perhaps @contsili can look into packaging as part of the [MATLAB Community Toolbox Training Project](https://github.com/fieldtrip/fieldtrip/projects/8).

**Comment by robertoostenveld** [comment]
As I believe the original report to be a user error, I will close this issue for now.
