### ISSUE TITLE
Error in ft_defaults

### ISSUE THREAD

**Issue by ThomasKoenigBern** [fieldtrip/fieldtrip#2333]
**Describe the bug**

I got the following messages and errors in ft_defaults:

Unrecognized function or variable 'ft_warning'.

Error in ft_defaults (line 201)
  ft_warning('FieldTrip is not yet on your MATLAB path, adding %s', strrep(ftPath, '\\', '\')); 

the cause was that my path to FieldTrip is "'D:\Dropbox (PUK-TRC)\Documents\MATLAB\FieldTrip'"

which made the code on line 202 

if isempty(regexp(path, [ftPath pathsep '|' ftPath '$'], 'once'))

return true, and falsely indicating that FieldTrip was not on the path, because the parentheses in my path were not evaluated literally by regexp

I fixed this by adding 

ftPath = strrep(ftPath, '(', '\(');
ftPath = strrep(ftPath, ')', '\)');

before line 202

It may be worth including this in future versions of the toolbox, as others may run into the same issue.

**Environment and versions (please complete the following information):**
 - Operating System: Windows 11
 - MATLAB version R2022b
 - FieldTrip version: fieldtrip-20231025

**Additional context**

**Comment by schoffelen** [comment]
Thanks for reporting @ThomasKoenigBern.
We need to look into this a bit deeper for a more generic solution, because when I try to replicate this on linux your suggested solution does not work, i.e.

y = '/somedir:/someotherdir:/a(b)c';
x = '/a(b)c';

indeed returns empty, if I do:

regexp(y, [x pathsep '|' x '$'], 'once')

but if I do:
x2 = strrep(x, '(', '(');
x2 = strrep(x2, ')', ')');

as per your suggested fix, I still get an empty output.

However, if I convert x to a matlab string (rather than char):

strx = string(x);

>> regexp(y,[strx pathsep '|' strx '$'], 'once')

ans =

  1×5 cell array

    {0×0 double}    {[9]}    {0×0 double}    {0×0 double}    {0×0 double}

**Comment by robertoostenveld** [comment]
You write "Unrecognized function or variable 'ft_warning'". 

ft_warning should have been defined here https://github.com/fieldtrip/fieldtrip/blob/a888df824b69c7e768276adbeffa695916aa3d27/ft_defaults.m#L84C25-L84C25

Rather than trying to solve it by making changes later in the code, my question is why line 84 was not executed properly. Could you use the MATLAB debugger to step through the code at those lines?

**Comment by schoffelen** [comment]
Dear @ThomasKoenigBern what is the status of this? It looks as if the ball is in your court. At the moment we are waiting for your input, in order to be able to close this issue (unless prompted otherwise, we believe it's a 'user error')

**Comment by ThomasKoenigBern** [comment]
Solved, thanks for the quick and perfect response.
