### ISSUE TITLE
CTF data in BIDS format results in inconsistent channel names 

### ISSUE THREAD

**Issue by arnodelorme** [fieldtrip/fieldtrip#2395]
Datasets from this BIDS dataset (and several others)

https://nemar.org/dataexplorer/detail?dataset_id=ds004011

Have channels labeled xxxxx-1609 (for example MLO44-1609) and File-IO will not return locations for these channels. Is this the expected location. Can we strip the "-1609" and use channel locations from other files?

Tx

**Comment by robertoostenveld** [comment]
The "1609" corresponds to the MEG site, i.e. a sort of serial number of the particular CTF system. The one here at Donders is "4304".

There will be small differences between sites due to variation in hardware construction of the dewar insert, but I expect those to be small. If you'd want to replace the sensor positions, I suggest you would use another "1609" dataset for that. However, I would be more worried about _why_ those files don't have position information for those channels. It  suggests that something is wrong with those channels.  

Is it the same for all MEG files in that dataset? I don't know the authors, but looking at the preregistration at https://osf.io/x7t6p it looks to me that data was recorded on the CTF system at the NIH core facility in Bethesda. 

Do you have other data from that system? It would be interesting to go over all shared CTF datasets (and idem probably for Neuromag and BTi) and look up the serial numbers to see which ones come from the same machine/lab.

**Comment by arnodelorme** [comment]
These are 2 MEG datasets from the same group

https://openneuro.org/datasets/ds004278/versions/1.0.1
https://openneuro.org/datasets/ds004212/versions/2.0.0

**Comment by arnodelorme** [comment]
It is the same problem with these two other experiments.

**Comment by robertoostenveld** [comment]
Hi Arno,

I made the splitting of the channel labels in the header and grad structure more generic and believe that this would address your issue. Could you try replacing your ft_read_header with this one https://github.com/robertoostenveld/fieldtrip/blob/f6579ee131c8c9c4bbb6d7891738697d3e6de22a/fileio/ft_read_header.m 

and let me know if it works for you?

**Comment by arnodelorme** [comment]
OK, will try again and keep you posted. Thanks Robert.

**Comment by robertoostenveld** [comment]
I am back at my desk and have been able to test myself with `ds004011/sub-01/meg/sub-01_task-occlusion_run-01_meg.ds`. The update to the code solves the issue, hence I will merge with the main branch and upcoming release. 

By the way, the issue is due to the data being converted to BIDS by a tool that respects the "-1609" endings in the channels.tsv, which was clearly not FieldTrip data2bids. The dataset_description.json regretfully does  not mention the conversion tool, as that would have helped to establish tighter standards.

**Comment by arnodelorme** [comment]
Let us know when you merge and we will try it.

**Comment by robertoostenveld** [comment]
I have merged it and it is part of the latest master and the tagged [20240326](https://github.com/fieldtrip/fieldtrip/releases/tag/20240326) version. 

Moving the splitting of channel labels on the `-` to a later place in the ft_read_header code did result in a bunch of regression errors (chantype and sensype, grad.balance, and some other small things), but all of those have been resolved now and all regression tests pass again. I am quite confident that it will work for you.

**Comment by arnodelorme** [comment]
Thanks. Will try

**Comment by arnodelorme** [comment]
It is working fine now.

**Comment by robertoostenveld** [comment]
thanks for the feedback!
