### ISSUE TITLE
Forward problem solution simbio: a discrepancy in our simulations

### ISSUE THREAD

**Issue by VlastaKoudelka** [fieldtrip/fieldtrip#2423]
Dear Fieldtrip Developers,

Thank you for all your efforts in maintaining Fieldtrip. We have been using Fieldtrip for our research for long time, and now we are facing a discrepancy in our simulations. Here is the context:

- We have been developing an ESI method for EEG using a surface EEG implant.
- We develop, simulate, and measure fabricated phantoms to validate the forward and inverse solutions.
- We investigate various solutions to the forward problem (see [this article](https://ieeexplore.ieee.org/abstract/document/9868355) for more detail).

The issue:

We have a rectangular-shaped phantom with electrodes on the surface and testing dipoles inside the volume conduction models. Through a series of simulations, we conducted the following experiment.

We considered two variants of the model shown in Figure 1:

1. Model 1 is composed of one layer (one tissue) and is represented by one volumetric mesh (a tetrahedral mesh).
2. The same model, but with two layers (two tissues) (Model 2), both having the same conductivity (depicted in Figure 1).
3. Both head models have the same conductivity value of 0.33 S/m.
4. A testing dipole is located inside the volume (far from the boundaries).

<img width="290" alt="phantom mesh" src="https://github.com/fieldtrip/fieldtrip/assets/13536400/3ca789ae-bf60-4d64-8859-2602fa14041d">

Fig. 1 A testing model, electrode are marked with red dots
We expected to obtain almost the same results for Models 1 and 2, but this was not the case. Figure 2 and 3 depict leadfields of the two models due to a testing dipole.

![image](https://github.com/fieldtrip/fieldtrip/assets/13536400/057c29c4-b669-4b68-a8fe-0ddfeb868fbf)

Fig. 2 Leadfield comparison between MODEL 1 and 2, first half of the electrode set

![image (1)](https://github.com/fieldtrip/fieldtrip/assets/13536400/73b4fe18-39d1-4af3-ac89-826e29c7f961)

Fig. 3 Leadfield comparison between MODEL 1 and 2, second half of the electrode set

Our question is why the results are so drastically different. We believe that this issue (and its solution) could potentially affect a broader research community.

Thank you for your assistance.

Best regards,
Vlastimil Koudelka

**Comment by schoffelen** [comment]
without any additional code it is hard for use to comment on this.

are you sure that in your code you enforce SI units prior to passing on the geometries to the lower level simbio code?

also, have you consider to contact the simbio folks as well?

**Comment by DavidKuratko** [comment]
Hello,
thank you for your reply. 

I uploaded our FT codes to my Google drive:
https://drive.google.com/drive/folders/15Lh9k4kAkaNXB562MVL0zI64D6na2MlG?usp=drive_link

I also added .txt for dipole and electrode positions plus .mat files of 3D models.

There are two FT codes - first one is for Model 1 (one tissue) and the second one for Model 2 (two tissues). Nevertheless, both codes are almost the same (the difference is in tissue assignment - volume.rho).

Thank you for your help in advance.

Best regards,
David Kuratko

**Comment by schoffelen** [comment]
We don't have the bandwidth to look into this in detail. If I were to diagnose this, I would start off by going through the code line by line, and investigate the equality of the objects along the way. My suspicion is that that simbio compiled code just generates different system matrices, which is not something that FieldTrip can solve. 
Once you have confirmed for yourself that it's a simbio issue, I suggest that you reach out to the simbio folks.

**Comment by VlastaKoudelka** [comment]
I understand and thank you for the suggestions, we checked everything in the code and finally decided to create the meshes out of the artificially generated MRI scans to rule out the possibility that it is due to our meshes. If you consider this result interresting, I can put new results here ones its computed. If not, you can possibly close the issue now. Thank you.

**Comment by schoffelen** [comment]
Hi @VlastaKoudelka I spend some time looking at your code, and indeed realized that the base topologies of the meshes are already different (i.e. a different number of vertices + volume elements). I would have assumed initially that you only changed the tissue compartment. As such, one could still have the assumption that - even with a different parcellation of the volume (i.e. differently shaped tetraeders) - the forward models should come out the same. This is beyond our knowledge (and influence sphere) For such a discussion I think you should take it up with the Simbio folks in Muenster, I am pinging @mcpiastra here, who used to work in the group that developed simbio, if she has time she might be able to point you to someone who could/would think along.

By the way, I cleaned up your code a bit, and added a test case where I used the 2-compartment model (the one which has the most vertices and tetraeders), and explicitly defined a single tissue compartment there (setting ```volume.tissue(:) = 1,  volume tissuelabel = {'brain'}```. This creates a leadfield that is the same as your '2' compartment model. This suggests indeed that the cause of the observed difference is due to differences in the topology of the mesh

**Comment by johaenns** [comment]
Hi,

from the data you provided it seems that something went wrong in your meshing process, so that in your second mesh your two compartments are not "connected". Normally, the nodes at the surface between tissue 1 and tissue 2 should be part of both tetrahedrons in tissue 1 and in tissue 2. In your meshes it seems to me you have one set of nodes that is only found in tissue 1 and one set of nodes that is only found in tissue 2 at this boundary. I could only find 6 nodes that are part of both tissue 1 and tissue 2. 

This picture shows the nodes and edges belonging to tissue 1 (gray) and the nodes and edges belonging to tissue 2 (pink) for a part of the shared boundary of these two compartments, and you can clearly see that these are two different sets of points/triangles:

![tissue_boundary](https://github.com/user-attachments/assets/99f3a47e-ec64-4519-b30b-71e503c16ad3)

Accordingly, there is no physical connection between the two tissues and the computation has to fail for this mesh. Once you could resolve this problem in your meshing, I would hope that the computation works properly.

**Comment by VlastaKoudelka** [comment]
Thank you both @schoffelen and @johaenns for processing this. @DavidKuratko, could you please check the mesh of model 2 once again and possibly run the simmulation again for the correted mesh? Then we need to figure out what is the source of this mismatch. Its the metter of our investigation out of the FT-simbio pipeline. However, It would be appropriate to show the final results (the corrected ones) before closing this issue as solved.

**Comment by DavidKuratko** [comment]
Hello, 
thank you everyone for your help. I created a new mesh with both compartments connected and it resolved the issue. When I repeat the experiment mentioned above, I get almost the same results:
![Elpot_evenElec_newModel](https://github.com/user-attachments/assets/f71b4754-748f-4fb6-83ca-814a9af57053)
![Elpot_oddElec_newModel](https://github.com/user-attachments/assets/bc399bcb-a987-4e34-8044-3899c81f2707)

**Comment by schoffelen** [comment]
OK, thanks for the update @DavidKuratko and @VlastaKoudelka . I assume that the issue can be closed?

**Comment by VlastaKoudelka** [comment]
Hi everyone,

yes, the issue can be closed. And I've learned that we need to doublecheck the meshes in future. Thank you all for your efforts.

**Comment by schoffelen** [comment]
No worries, and keep up the good work!
