### ISSUE TITLE
MATLAB crash on Windows due to sparse matrix in read_trigger function

### ISSUE THREAD

**Issue by contsili** [fieldtrip/fieldtrip#2451]
**Describe the Bug**
MATLAB crashes at `read_trigger` (line 100) on the following code:

`if skewness(abs(diff(dat(i,:)))) > 5`

This issue occurs on Windows devices. The crash has been reproduced on two separate machines: a personal laptop and a Donders PC station.

**To Reproduce**
```
cfg = [];
cfg.dataset = '<OPM data>';  % Download from https://we.tl/t-U190lcH16V
cfg.trialdef.eventtype = 'ai61';
cfg.trialdef.prestim = 0.2;  % ISI varied from 0.8 to 1.2 seconds
cfg.trialdef.poststim = 0.4;
cfg = ft_definetrial(cfg);
```

**Expected Behavior**
MATLAB crashes on Windows devices but does not crash when run on the Donders Cluster or on macOS.

**Environment and Versions** 

- Operating System: Windows 10
- MATLAB Versions: 2020B, 2021b, 2022a, 2023b
- FieldTrip Version: 74c5a8e18

**Additional Context**
Upon further investigation, it was identified that the issue arises from `dat ` variable being a sparse double matrix. When converted to a full matrix, MATLAB no longer crashes. The issue seems to originate from the low-level function `fiff_read_raw_segment()` at the following lines (121-126):

```
if ~isempty(cal)
    cal = sparse(cal);
end
if ~isempty(mult)
    mult = sparse(mult);
end
```

**Comment by schoffelen** [comment]
I haven't tried to reproduce this, but I looked into the history of the fiff_read_raw_segment file, and the sparse allocation tot he calibration coefficients has been there already before I (= JM) started meddling with this code.

Thinking it over, I suggest to do a call to full() in ft_read_data just after the call(s) to fiff_read_raw_segment. @contsili would you be willing to make this into a PR (so that you will get (even more) credits in the electronic trace of the resolution of this issue)?

**Comment by contsili** [comment]
@schoffelen thank you for looking into this. I will do it.
