### ISSUE TITLE
ft_volumelookup test script fails

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#512]
@smg211 or @StolkArjen can you please fix it? Please try out the test script.

=== test_ft_volumelookup FAILED in 29 seconds
Error using ft_volumelookup (line 362)
Reference to non-existent field 'querymethod'.
Error in test_ft_volumelookup (line 43)

**Comment by StolkArjen** [comment]
Hey @smg211, the specific test operation is trying to find labels corresponding to a mask (i.e. mask2label):

mri.mask  = mask4;
cfg       = [];
cfg.atlas = atlasfilename;
cfg.inputcoord = 'mni';
cfg.maskparameter = 'mask';
mask5     = ft_volumelookup(cfg, mri);

One of the latest additions to the code that seems to underlie the cause of the error is: 

if roi2label
..
cfg.querymethod        = ft_getopt(cfg, 'querymethod', 'sphere');
end

Uncommenting the if-end statements make ft_volumelookup run through, but the look-up part is slow. I don't know if this has always been like that (might well be). The queryrange option is 1 by default, so that means it looks only at 1 voxel of each maskvoxel at a time (instead of a radius of 1, thus 6 voxels), right?

For now, I'll remove the if-end statement to make sure the function runs through. But maybe you can double check this issue.

**Comment by StolkArjen** [comment]
see https://github.com/fieldtrip/fieldtrip/pull/513

**Comment by StolkArjen** [comment]
Btw, @robertoostenveld, just as a general note, ft_volumelookup could benefit from the same cfg.output option that is also implemented in ft_mvaranalysis and ft_regressconfound. Right now, the determination of mask2label, roi2label, roi2mask depends on relatively ambiguous input parameters. This works fine still but is likely to blow into pieces if we want to add new functionalities to ft_volumelookup at some point in the future. There's currently already some support for the cfg.output option in ft_volumelookup, i.e. to distinguish between roi2mask and roi2label.

**Comment by robertoostenveld** [comment]
ft_volumelookup was designed by Ingrid for a specific purpose (probably to locate ATL). Ideally I would like it to output a recognizable FT data structure. Right now its output cannot be fed into any other FT function.

**Comment by robertoostenveld** [comment]
this has been fixed with PR #513

**Comment by StolkArjen** [comment]
Another good point indeed.
