### ISSUE TITLE
Plot of ft_freqanalysis differ if cfg.keeptrials were set to 'yes' versus 'no'

### ISSUE THREAD

**Issue by suxpert** [fieldtrip/fieldtrip#670]
According to the tutorial, it seems that I need to add
```matlab
cfg.keeptrials = 'yes';
```
when calling `ft_freqanalysis` if I want to perform some statistics using `ft_freqstatistics`.

But I found that before I set `keeptrials` to 'yes' and after, the figure plotted via `ft_singleplotTFR` have much differences. Is that OK? Which should I believe to be true?

**Comment by robertoostenveld** [comment]
statistics needs repetitions to estimate the variance. Plotting needs an average. When you give trials to the plotting code instead of an average, it should compute an average on the fly, which should not be different from the average that is computed in freqanalysis itself.

Please be specific in which tutorial the problem applies and if possible upload screen shots that show the difference.

**Comment by suxpert** [comment]
```matlab
cfg            = [];
cfg.pad        = 'nextpow2';
% cfg.keeptrials = 'yes';
cfg.output     = 'pow';
cfg.foi        = 2: 140;
cfg.toi        = -0.2: 0.01: 0.6;
cfg.method     = 'mtmconvol';
cfg.taper      = 'hanning';
cfg.t_ftimwin  = ones(size(cfg.foi)) * 0.1;

cfg.trials = ctrl;
TFR_ctrl = ft_freqanalysis(cfg, epoch_data);


cfg = [];
cfg.baseline     = [-0.2, 0.05];
cfg.baselinetype = 'db'; 
cfg.zlim         = [-4, 4];
figure;
ft_singleplotTFR(cfg, TFR_ctrl);
```

Gives:
![nokeeptrials](https://user-images.githubusercontent.com/1191414/36629394-3c1604de-1990-11e8-9652-1cc38fd77613.png)

But with `cfg.keeptrials = 'yes'`, I've got:
![keeptrials](https://user-images.githubusercontent.com/1191414/36629396-4314f416-1990-11e8-84e8-111ad119a14d.png)

All others are the same.

**Comment by schoffelen** [comment]
with keeptrials = 'yes', the baseline correction is applied to every single trial, with keeptrials = 'no', the baseline correction is only applied to the average. Since the baseline operation that you have specified is the result of a division, this yields different results. In general, first averaging, then baseline correcting makes more sense

**Comment by suxpert** [comment]
If "first averaging, then baseline correcting" is the correct way, then how to perform statistics?
