### ISSUE TITLE
ft_appendsens and unique in CTF datasets

### ISSUE THREAD

**Issue by mjcourte** [fieldtrip/fieldtrip#804]
Hi all,

I'm trying to merge two-to-three CTF 275ch datasets into a single dataset for subsequent source localization. Using `ft_appenddata`, the data is merged, but the `.grad` and `.label` substructs are not. Therefore subsequent operations, namely lead fields for beamforming, fail. My workaround plan was to use `ft_appendsens`, to create the new `.grad` substructs, and insert them into the appended data structs. 

In `ft_appendsens`, the line 165 error is thrown, when trying to compare `unique(sens.chanpos, 'rows', 'stable' )` and `unique(sens.label, 'stable')`. In the function these are saved to `chanidx` and `labidx` respectively. This error is thrown as well when trying to `ft_appendsens(cfg, data1)`, with a single freshly imported dataset argument, so the error is before append operations. The function won't work because the way it is checking each dataset for internal consistency results in failure.

The relevant lines are 149-165 in [ft_appendsens.m](https://github.com/fieldtrip/fieldtrip/blob/master/ft_appendsens.m)

Applying `unique(chanidx, 'row', 'stable')` to a CTF275 dataset reduces the `size` from (302,3) to (285,3), which now mismatches with the labels of size (302,1). I believe that `unique` is causing a conflict with the fact that the ~27 reference channels (BG1 to R23) contain unique labels at the same physical positions in the reference array of a CTF MEG. 

I had a look around at the subfields (and concatenations of subfields) of `.grad` and checking `unique`, but none would match the number of unique labels.

Am I doing something wrong, and/or this error is working as intended? 

Thanks,
Matt

**Comment by Spaak** [comment]
Hi Matt,

If you want to combine data from different sessions and sensibly do source
analysis, the head position (as reflected in the .grad field) will need to
be (almost) the same across the sessions. If that is the case, you can
simply take the .grad from one of the sessions and put it in the appended
data structure.

However, if head position is not identical among sessions, perhaps it makes
more sense to do source analysis separately for the three sessions and then
combine at source level. The source coordinates (in a suitable coordinate
system) will be identical for the sessions, thus taking diferences in head
position into account.

Cheers,
Eelke

**Comment by mjcourte** [comment]
Hi Eelke,

Thanks for your suggestions. I'll admit my usage is unconventional. I'm looking to combine scans with intentionally different head positions, and importing the data with the sensors in head coordinates. I'm increasing the simultaneous effective channel count via this method, prior to beamforming.

Therefore, the new .grad struct would need to be an ordered concatenation of multiple .grad structs. I was assuming `ft_appenddata` and/or `ft_appendsens` would be the tool for the task. 

For now I can print pre-processed data back to CTF .ds and use their software to combine data in this manner, and re-import for source analysis. 

Whether or not `ft_appendsens` erring on ctf275 input should remain an issue here is up to you folks.

Thanks again,
Matt

**Comment by schoffelen** [comment]
Hmmm, ft_appendsens was designed by Arjen to take care of sensor/channel descriptions with non-overlapping sets of labels. ft_appenddata was designed to either append across the observation dimension (provided the channel labels are the same), or across the channel dimension, provided all channel labels are different. So these are not the right tools for the task. What you want could be achieved by ft_appenddata if you replace the labels in the data structures (and corresponding grad array structures) such that they are unique across datasets. Likewise for ft_appendsens. Otherwise the labels are duplicated and the bookkeeping will fail. Perhaps we should clarify the supported use-case in ft_appendsens better, and build in a check that throws an error if there is overlap in the sensor labels. @stolkarjen, what do you think?

**Comment by StolkArjen** [comment]
Not sure I fully grasp the use-case of @mjcourte or what 2017-Arjen was thinking. From a brief look at the print commands, though, it seems the function is pretty clear already on pruning sensors from the output with duplicate labels or locations?

**Comment by schoffelen** [comment]
well, I guess that the 2017 @StolkArjen wrote the function with ecog in mind, and not with MEG 2 grad arrays, which have a fully overlapping set of labels, but a fully disjoint set of coil positions, but within each grad array a set of non unique positions for each of the channels (since separate reference channels share coils). In other words the function is not robust against this use case, which admittedly is a bit odd.

**Comment by StolkArjen** [comment]
On the contrary, my guess is that 2017-Arjen had already made the function corona-proof. But yeah, your suggestion of replacing labels seems to be more appropriately documented on the website than in a low-level function like ft_appendsens.
