### ISSUE TITLE
ft_plot_slice shifts the volume a little bit

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#805]
try this

```
mri.unit = 'cm';
mri.dim = [2 2 2];
mri.anatomy = ones(2,2,2);
mri.transform = eye(4);
mri.transform(1,4) = -1;
mri.transform(2,4) = -1;
mri.transform(3,4) = -1;

ft_determine_coordsys(mri);
```

**Comment by schoffelen** [comment]
I think that this is not an issue. Currently, I am looking into some mesh generation business (noticing some unexpected behaviour in (possibly) the location/visualization of meshes relative to the anatomical from which they were derived. Specifically, using different mesh-methods, they seem to be differentely offset with respect to one another, and/or with respect to the co-visualized volume (using ft_plot_ortho), where there seems to be an interaction with the voxel resolution. Strange. 

Anyway, in the above example, I'd assume that you intended the origin to be exactly in the middle of the volume (i.e. at a corner point of the voxels, rather than in the center of one of them), right?

In that case, the proper transformation matrix would be inv([eye(3) mri.dim(:)./2; 0 0 0 1]);
This gives the crosshair in the middle. 

@KristijanArmeni this is related to the mesh generation business I was talking about earlier.

**Comment by schoffelen** [comment]
Sorry, I forgot the +1

mri.unit = 'cm';
mri.dim = [2 2 2];
mri.anatomy = ones(2,2,2);
mri.transform = inv([eye(3) (mri.dim(:)+1)./2; 0 0 0 1]);

ft_determine_coordsys(mri);

**Comment by schoffelen** [comment]
With respect to the 'unexpected behavior', it seems fine after all, but the discrepancy results from the way that ft_plot_slice does a (default) interpolation to a 1mm resolution, using a default interpmethod of 'nearest'. This leads to apparent shifts of the volume when it's binary.
