### ISSUE TITLE
ft_plot_slice fails on a volume with a single voxel

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#807]
try this

```
mri.unit = 'cm';
mri.dim = [1 1 1 ];
mri.anatomy = ones(1,1,1);
mri.transform = eye(4);

ft_determine_coordsys(mri);
```

**Comment by schoffelen** [comment]
this is interesting from a theoretical point of view, but not really from a practical point of view.

some causes of this can be easily caught:
- add trailing singleton in dim variable size(dat) = namelijk [1 1], rather than the expected [1 1 1]
- ensure that the resolution estimate is (0+eps)./(0+eps)


then the interpn fails, because this function expects the input data to have at least size 2x2x2

if interpn is not needed, e.g. when mri.transform(1:3,4) = -0.5, the plotting works.

So the question is: how much effort should be spent on this, or should we just throw an informative error in ft_plot_slice if any(dim==1)

**Comment by robertoostenveld** [comment]
I would opt for the informative error.

**Comment by schoffelen** [comment]
OK, done.
