### ISSUE TITLE
ft_combineplanar fails on data recorded in multiple blocks 

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#840]
... where the blocks are in different fif files, preprocessed and then appended. The grad structure will be slightly different, and hence removed by ft_appenddata.

The reason why ft_combineplanar is not because it cannot work (it uses pre-defined channel lists, not the grad), but only because it cannot detect the sensor type. I.e. ft_checkdata gives the error that it cannot detect that it is planar channels.

**Comment by schoffelen** [comment]
@robertoostenveld do you have any data in mind, e.g. W&H faces experiment? I recall coming across something similar myself but didn't bother to address it.
Alternatively, we could also leave this for now, since this looks like a use case that should occur more often in all kinds of pipelines, but there's no rumour about this on the discussion list. Therefore, it might be that people don't seem to suffer from this in general.

**Comment by robertoostenveld** [comment]
I think that this should indeed occur with the W&H dataset. I am downloading some of the fif files right now, will give it a try. 

There might be a general structure here: high-level FT functions with varargin should probably in all cases discard the inconsistent sensor metadata.

**Comment by schoffelen** [comment]
Not sure about your last remark: I could imagine some fancy stuff in ft_denoise_pca or so, with a separate 'refdata' argument, where the grad might be retained.

**Comment by robertoostenveld** [comment]
If I do preproc->planar->append->combine, then it fails. All other sequences seem to work. 

However, the W&H example I picked turned out to be problematic, since megplanar (follwed by combineplanar) don't work (without hacks) on neuromag data. Another challenge that it poses is that it contains both a grad and an elec, which means that ft_senstype fails ((it thinks it is EEG).

**Comment by robertoostenveld** [comment]
it was difficult to reproduce, and in the end mostly revealed other limitations of the code (e.g. that ft_senstype does not work properly with data structures that contains both MEG and EEG). Since nobody complained about it recently, I'll leave it as it is.

**Comment by schoffelen** [comment]
actually, there is also issue #1260 with an associated draft PR, where I was thinking a bit about the necessity of having both a grad and an elec in a data structure, while the numeric data is either only MEG, or only EEG. For one, it substantially slows down a lot of processing, since persistent variable trick does not work as robustly anymore in the sensor-array bookkeeping functions, but also I remember identifying some issue with inconsistent handling of grad/elec if both were present in the data structure
