### ISSUE TITLE
ft_freqanalysis rounding error failure

### ISSUE THREAD

**Issue by jdien07** [fieldtrip/fieldtrip#922]
In the attached test case, a frequency analysis of data with 1000Hz sampling rate fails to allow for foi ranging up to the Nyquist of 500 because ft_checkdata removes the .fsample field with:
266 data = ft_datatype_timelock(data, 'hassampleinfo', hassampleinfo);
It then reinstates the .fsample field at:
417 data = ft_datatype_raw(data, 'hassampleinfo', hassampleinfo);

which estimates .fsample:
242 fsample = 1/mean(diff(data.time{1}));

as

9.999999999999993e+02

which is smaller than the original fsample of 1000 and therefore the 500 foi fails as it is larger than the erroneous Nyquist limit.

My suggestion is to not remove the fsample field in the first place in ft_datatype_timelock since it doesn't really make sense to remove it and then put it back again, by deleting the responsible lines in ft_datatype_timelock:

157    % this field can be present in raw data, but is not desired in timelock data
158    timelock = removefields(timelock, {'fsample'});

but if its obsolescence is truly desired (I see it was deprecated back in 2011), then it should be estimated more precisely in ft_datatype_raw by taking the digits of significance of the sample times into account and rounding the fsample estimate accordingly.

[testCase.zip](https://github.com/fieldtrip/fieldtrip/files/2743316/testCase.zip)

fieldtrip-20190109, Matlab 2018b, OS X 10.14.2

**Comment by schoffelen** [comment]
numerical tolerance is a recurring issue. I wouldn't know how FieldTrip could determine the digits of significance given the floating point representation of the numbers to begin with. If anything, this requires knowledge of the 'original' delta-t, which makes the whole fsample discussion altogether circular.
This being said, perhaps we could add a bit of tolerance in the evaluation that is performed in ft_freqanalysis (i.e. rather than saying if any(cfg.foi>data.fsample/2) say something like any(cfg.foi>data.fsample/2+100*eps(data.fsample)) or so.
@robertoostenveld, shall I just include this (+creating a test function with Joe's data) in order to solve the issue?

**Comment by schoffelen** [comment]
[master 4862bc3] ENH - addressed issue 922, to allow for some numerical tolerance in an if statement
 2 files changed, 13 insertions(+), 1 deletion(-)
 create mode 100644 test/test_issue922.m

git push upstream master
Counting objects: 8, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 729 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/fieldtrip/fieldtrip.git
   426678c..4862bc3  master -> master
