### ISSUE TITLE
ft_warning off does not retain state correctly

### ISSUE THREAD

**Issue by robertoostenveld** [fieldtrip/fieldtrip#947]
@dmatthes1982 wrote by email

> today I've encountered a problem within the function ft_warning or rather ft_notification.
> 
> I was calling the following commands
> 
> ft_warning off; ft_topoplotIC(cfg, data); ft warning on;
> 
> Contrary to my expectations, ft_plot_topo was throwing a warning message. After closer examination, I found out, that one source of these problem is e.g. in line 364-366 in topoplot_common.
> 
> ws = ft_warning('off', 'FieldTrip:getdimord:warning_dimord_could_not_be_determined');
> [data] = ft_selectdata(tmpcfg, data);
> ft_warning(ws);
> 
> After executing the first command, ws is a structure and contains only the old state of 'FieldTrip:getdimord:warning_dimord_could_not_be_determined'. When I later execute the third command, ft_default.notifications.warning will be overwritten with the content of ws, all other former content (e.g. 'all', 'off') of this structure (ft_default.notifications.warning) is deleted.
> 
> I assume that the aim of the third line is to only reset the entry of 'FieldTrip:getdimord:warning_dimord_could_not_be_determined' not to overwrite the whole ft_default.notifications.warning structure.
> 
> Now, I'm not sure which fix you would prefer.
> 
> One could either modify the third line of this last code snippet to ft_warning(ws.state, ws.identifier) or change the handling of structures in ft_notifcation line 154-157 or change the return value of line one in the code snippet. The function ft_notification should then return the whole content of ft_default.notifications.warning and not only the old state of the entry to be changed.

**Comment by robertoostenveld** [comment]
I made an issue out of it so that it gets a number, which I can use in a test script `test_issue947.m`. 

```
global ft_default


%%

% the warning state is kept in the global ft_default structure
ft_default = [];

% both should show
ft_warning('a:a', 'a')
ft_warning('b:b', 'b')

%%

ft_warning('off', 'a:a')

% only b should show
ft_warning('a:a', 'a')
ft_warning('b:b', 'b')

%%

% the warning state is kept in the global ft_default structure
ft_default = [];

ft_warning('off')

% none of them should show
ft_warning('a:a', 'a')
ft_warning('b:b', 'b')

%%

ft_warning('on')

% both of them should show again
ft_warning('a:a', 'a')
ft_warning('b:b', 'b')

%%

% the warning state is kept in the global ft_default structure
ft_default = [];

ft_warning('off', 'a:a')
ft_warning('off', 'b:b')

% none of them should show
ft_warning('a:a', 'a')
ft_warning('b:b', 'b')

%%

% the warning state is kept in the global ft_default structure
ft_default = [];

wsa = ft_warning('off', 'a:a')
wsb = ft_warning('off', 'b:b')

% none of them should show
ft_warning('a:a', 'a')
ft_warning('b:b', 'b')

% revert the state of a
ft_warning(wsa)

% only a should show
ft_warning('a:a', 'a')
ft_warning('b:b', 'b')

% revert the state of b
ft_warning(wsb)

% both should show
ft_warning('a:a', 'a')
ft_warning('b:b', 'b')
```

Upon `ft_warning(wsa)` it starts breaking; as you describe the state of b gets lost.

**Comment by robertoostenveld** [comment]
I think that the best way to fix it is to change something on line 155 of ft_notification, where currently the input state `wsa` replaces the full state. 

How about 
```
if numel(varargin)==1 && isstruct(varargin{1})
  for i=1:numel(varargin{1})
    s = setstate(s, varargin{1}(i).identifier, varargin{1}(i).state);
  end
  ft_default.notification.(level) = s;
  return
end
```

**Comment by robertoostenveld** [comment]
the first would specifically switch it back on for `a:a`, leaving all others as they are. 

@dmatthes1982 could you see whether this solves your issue?

**Comment by robertoostenveld** [comment]
if  - with this change - I do 

```
ft_default = [];

wsa = ft_warning('off', 'a:a')
ft_warning('off')
ft_warning(wsa) % revert the state for a
ft_warning('a:a', 'a') % this shows
ft_warning('b:b', 'b') % this not
ft_warning('c:c', 'c') % this not
``` 

a does not show, whereas b and c do show. That is ok, right?

**Comment by robertoostenveld** [comment]
given lack of feedback, let's assume this is ok.

**Comment by NirOfir** [comment]
Hi,

Using ft_topoplotIC to plot ICA topographies (filedtrip version downloaded on 07/04/2020) still displays a warning of this type:
`Warning: could not determine dimord of "comp" in:

             label: {64×1 cell}
               cfg: [1×1 struct]
              topo: [64×1 double]
        topodimord: 'chan_comp'
              comp: 1
          unmixing: [1×64 double]
    unmixingdimord: 'chan_topochan'

 
 In getdimord>warning_dimord_could_not_be_determined at line 681
 In getdimord at line 631
 In ft_selectdata at line 188
 In topoplot_common at line 356
 In ft_topoplotIC at line 189`

I followed the same steps that are described in the first comment here. So this is what happens in lines 355-357 of ft_topolplot_common:
`ws = ft_warning('off', 'FieldTrip:getdimord:warning_dimord_could_not_be_determined');
[data] = ft_selectdata(tmpcfg, data);
ft_warning(ws);`

I think that line 355 is supposed to turn off the dimord warning, then line 356 averages over trials, and line 357 is supposed to reinstate the warnings to their old state (in other words, turn back dimord warnings). So I looked into ft_notification (called by ft_warning) and up to line 413 everything seems fine and the warning is turned off. However, lines 415-418:
`if strcmp(level, 'warning')
  % return to the original warning state
  warning(ws);
end`
override the change that was just applied to the warnings, and turn back all warnings. This happens because ws is created in lines 141-149:
`if strcmp(level, 'warning')
  ws = warning;
  % warnings should be on in general
  warning on
  % the backtrace is handled by this function
  warning off backtrace
  % the verbose message is handled by this function
  warning off verbose
end`
In the end, it seems like ft_notification turns off the dimord warning and turns it back on before returning. I don't really understand how FT deals with warning, so I don't know how to suggest a fix here.

Thanks!
