### ISSUE TITLE
Reference for method 'stephen' in `beamformer_sam.m`

### ISSUE THREAD

**Issue by mjcourte** [fieldtrip/fieldtrip#957]
Hi guys,

In Stephen Robinson's method of finding fixed orientation, you call lead field projections on orientations `L1` and `L2` before they are defined via `U` which is defined from `L1` and `L2`. This is circular as implemented, so I'm wondering if it this comes from a translation error from wherever you got this method. There must be some other definition of the 'first' set of `L1` and `L2` that has been omitted, otherwise the 'stephen' method is trying to do matrix operations on vectors.

https://github.com/fieldtrip/fieldtrip/blob/f9a654fda0d9e93be6f1f0a9197a949a1e0f800e/inverse/beamformer_sam.m#L191-L220

Could you provide me a link to a paper used for this algorithm?

Thanks,
Matt

**Comment by schoffelen** [comment]
I don't have a clue, perhaps you can google a bit (or check Vrba & Robinson's signal processing in MEG paper (2001)). I believe that the original code has come to us through either Arjan or Gareth. Either way, the sam-beamformer is probably not actively used at all, so it's not surprising that it does not work. (although it is a bit surprising that it seems hardly functional to begin with). Is there a particular reason you want to use SAM, rather than LCMV?

**Comment by robertoostenveld** [comment]
The SAM beamformer implementation was shared with us by Gareth Barnes. Perhaps ask him?

**Comment by mjcourte** [comment]
Thank you both. I'll try to track down this approach in one of the papers and/or from Gareth. 

I'm using SAM because I'm trying to benchmark some analysis against some older results that only used SAM, and the code for which has been lost to time. If I get the method working I will pass it back this repo.

**Comment by schoffelen** [comment]
Top!
